### ISSUE TITLE
direct processing of xml

### ISSUE THREAD

**Issue by JuliaLawall** [GumTreeDiff/gumtree#1]
It could be useful to take xml abstract syntax trees directly as input, for example, if one wants to work on a language for which a parser does not already exist.

**Comment by jrfaller** [comment]
This is a very good idea. Since we are planning to handle XML format also, using the DOM as a tree, I think we need to have a special option in the command line for that, such as --no-parsing? We could also take JSON serialized trees as input.

**Comment by jrfaller** [comment]
This has been fixed by floreal's commit.
