### ISSUE TITLE
Parsing incorrect code

### ISSUE THREAD

**Issue by ArtyomLobanov** [GumTreeDiff/gumtree#101]
Hello!
Is it possible to know if parsed code was incorrect?

Example:
`final TreeContext context = generator.generateFromFile("a.java");`

a.java
```
class Main {
    public static void main(String[] args) {
        Scanner s = new Scanner(System.in);
        for (int i = 0; i < 5; i++) {
            int t = s.nextInt(1);
        }
        s.close() // Semicolon missed
    }
}
```
No exception was thrown and it looks like TreeContext hasn't method to check if AST was built correctly.

Thank you!

**Comment by jrfaller** [comment]
Hi!

This is currently not possible, and I am not sure every parser we have furnish this information via an Exception. However this sure would be an interesting feature...

**Comment by jrfaller** [comment]
OK I managed to get that feature for every parser implemented in Java. It is not working for external parsers (srcml, cgum, pythonparser), but it's a start. SyntaxException is a runtime exception.
