### ISSUE TITLE
Gumtree to match and diff two sub/partial AST in Java

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#106]
@jrfaller

Currently, the gumtree requires to parse a java class into an AST with a compilation unit before the matching phase. If the class contains complex methods, the AST can be very deep, which makes the matching too time-consuming. (According to my evaluation, the parsing/action generating/clustering phases cost no more than 1~4 seconds, but the matching phase can be as long as 50 seconds.)

Therefore, I am wondering if the gumtree can accept partial AST, which can be cut out from the complete AST (since most parser requires a complete compilation unit to generate AST).

**Comment by Symbolk** [comment]
Done with Eclipse JDTParser or JavaParser. 

For JDTParser, set the kind to parse code snippets:

```java
generator.setKind(ASTParser.K_STATEMENTS);
```

For JavaParser, call corresponding parse API:

```java
Node node = JavaParser.parseXXX("...."); // parseBlock(String blockStatement)
```

**Comment by jrfaller** [comment]
Hi!

This is a cool idea, however not all parsers are capable of handling that, therefore I am not sure how to deal with it in the TreeGenerator interface...

BTW, you wrote that you have cases of diff taking 50 seconds, could you share me the files, I am trying to establish a benchmark of complex diff cases to have data to help speed-up the algorithms!

Cheers!

**Comment by Symbolk** [comment]
> Hi!
> 
> This is a cool idea, however not all parsers are capable of handling that, therefore I am not sure how to deal with it in the TreeGenerator interface...
> 
> BTW, you wrote that you have cases of diff taking 50 seconds, could you share me the files, I am trying to establish a benchmark of complex diff cases to have data to help speed-up the algorithms!
> 
> Cheers!

Glad that you are back~

Some time ago I was trying to use gumtree to diff some java files in the project AOSP, where there were some files with long methods (>500 lines) and long classes (>5000 lines). Of course, this is a rare case in most projects, but it did slow down gumtree sharply. Considering that more than half of the code was unchanged in the two side, so I wondered if gumtree could diff at a smaller scale (say, just one method).

However, after studying the code, I found that gumtree is designed to be language-dependent, which is a very good merit. So whether it can diff incomplete code depends on whether the parser can parse that code to build ITree.

I think you can find many such huge source files in  the AOSP project, such as Activity.java, ActivityThread.java, Notification.java in android/base/core.

**Comment by jrfaller** [comment]
Thanks for your answer.

You're right, it's always possible to implement a new generator, i.e. a JavaStatementTreeGenerator to be able to diff non-complete code fragments. I took a look in JavaParser for instance and it is able to parse imports, block, statements, ... However there are too numerous to have them all. I am wondering if I furnish some, like block which could be useful?

Thanks you for the pointer, I will try to see what is causing the delay in the files you mention, I will try with this one : https://github.com/aosp-mirror/platform_frameworks_base/blob/e80b45506501815061b079dcb10bf87443bd385d/core/java/android/app/ActivityThread.java

**Comment by jrfaller** [comment]
OK, it must depends on the version of the files, because with current GumTree (v2.1.2), the diff of the two last versions of ActivityThread.java takes only one or two secs.

**Comment by Symbolk** [comment]
> OK, it must depends on the version of the files, because with current GumTree (v2.1.2), the diff of the two last versions of ActivityThread.java takes only one or two secs.

Another possible reason could be complex and large-scale changes. I was trying to diff two versions of one file that have a far distance on the commit graph, say one at Android 8.0 and another at Android 9.0.

**Comment by jrfaller** [comment]
Tried between pie-release and oreo-release. Much more changes, some strange output ;) but diff time still very fast.

**Comment by Symbolk** [comment]
> Tried between pie-release and oreo-release. Much more changes, some strange output ;) but diff time still very fast.
