### ISSUE TITLE
Serializable Classes

### ISSUE THREAD

**Issue by ali-ghanbari** [GumTreeDiff/gumtree#113]
Please make all Ct* classes Serializable so that we can store them on the disk. For some purposes, we cannot afford to keep all the stuff in memory.

Thank you!

**Comment by jrfaller** [comment]
Hi!
Sorry but  could you be a little more specific about the classes because I can find only one class beginning by Ct : 

find . -iname "Ct*"
./gen.c/src/main/java/com/github/gumtreediff/gen/c/CTreeGenerator.java
