### ISSUE TITLE
add support for advanced diff summary

### ISSUE THREAD

**Issue by monperrus** [GumTreeDiff/gumtree#115]
Nice points by @Symbolk

https://github.com/GumTreeDiff/gumtree/issues/112#issuecomment-442301929
> Why we diff? Because we want to understand the changes, so the format should serve for change comprehension. In fact, someone has modified Gumtree output format but getting a distingushed paper~ (See [FudanSELab/CLDIFF](https://github.com/FudanSELab/CLDIFF))
> 
> I customized Gumtree for personal use, for meaningful diff summary, including:
> 
> ```
> Action Name
> Parent Node Type: Target Node Type
> Target Node Content Before Action
> Line Range & Column Range Before Action
> Target Node Content After Action (if exists)
> Line Range & Column Range After Action (if exists)
> ```
> 
> For example:
> 
> ```
> Move
> CompilationUnit::ImportDeclaration
> import com.beust.jcommander.Parameter;
> 12, 273
> import com.beust.jcommander.Parameter;
> 1, 0
> ```
> 
> So, basically you can read it as a phrase: "Move ImportDeclaration 'import com.beust.jcommander.Parameter;' in CompilationUnit from (12, 273) to (1, 0)".

https://github.com/GumTreeDiff/gumtree/issues/112#issuecomment-442751424

> I'd like to, but one major concern here.
> 
> As we know, Gumtree parses multple languages with various backends (parser), but for each of the supported languages, the definition of AST Node Type and the way to get ranges is different. Since I only use Gumtree to diff Java, so I only implement the Java version.
> 
> To generalize the output format, some refactoring must be done.
> 
> BTW, I made a pr earlier to fix a bug (#110 ), but it seems @jrfaller did not merge it.

**Comment by jrfaller** [comment]
I like very much this textual format. I think there is no problem to have it language independant since these informations are available in all our generators (and normally I took care that the range are homogeneously computed).

@Symbolk where can I read the code of your text formatter?

**Comment by Symbolk** [comment]
@jrfaller Ok, I will push my code to the forking repo (https://github.com/Symbolk/gumtree) by this weekend.

**Comment by jrfaller** [comment]
@Symbolk nice!!!

**Comment by jrfaller** [comment]
@Symbolk I guess this is commit Symbolk/gumtree@7fdc5712b86b70201d4834eb192f41d7769491cd ? Thanks!

**Comment by Symbolk** [comment]
> @Symbolk I guess this is commit [Symbolk/gumtree@7fdc571](https://github.com/Symbolk/gumtree/commit/7fdc5712b86b70201d4834eb192f41d7769491cd) ? Thanks!

Yeah, but I only implemented the location info (i.e. Range) for Action and ITree and for Java currently, do you think it deserves a pull request, or other languages should be implemented?

**Comment by jrfaller** [comment]
Hi @Symbolk I have updated the textual output of diff using many of your ideas! Thanks for the discussion (and closing this issue).
