### ISSUE TITLE
Compare at low Granularity

### ISSUE THREAD

**Issue by spyyes** [GumTreeDiff/gumtree#120]
I noticed that Gumtree compares the code at a low granularity.
For example, when comparing the 2 code snippets below:

**Code Snippet 1**
![image](https://user-images.githubusercontent.com/28469648/50721761-9b511d00-10ff-11e9-9e38-dad422c6ed86.png)

** Code Snippet 2**
![image](https://user-images.githubusercontent.com/28469648/50721752-87a5b680-10ff-11e9-9ad4-917ccd11ea36.png)

When comparing the 2 snippets, it cannot identify the differences.

The code I used as below:
`	ITree src = Generators.getInstance().getTree(file1).getRoot();				
		ITree dst = Generators.getInstance().getTree(file2).getRoot();
		Matcher m = Matchers.getInstance().getMatcher(src, dst);
		m.match();	
		ActionGenerator g  = new ActionGenerator(src, dst, m.getMappings());
		g.generate();
		List<Action> actions = g.getActions();
`

**Comment by monperrus** [comment]
Hi Peiyi,

Thanks for your bug report.

Just tested your example with the Spoon backend of Gumtree: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/commit/922564b717c53eb6ec97b38dd69ce726a1bf2602

Works for me.

**Comment by jrfaller** [comment]
This is odd since there is a new parameter... Did you try with the javaparser backend (`-g java-javaparser`)?

**Comment by jrfaller** [comment]
it seems that it is caused by a syntax error, maybe JDT is not compatible with this syntax?

Could you send me the real file?

Cheers.

**Comment by jrfaller** [comment]
I believe it comes from enqueue() which is a method invocation directly in the class body?

**Comment by monperrus** [comment]
FYI, varargs works out of the box in Gumtree-spoon: https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/test/java/gumtree/spoon/AstComparatorTest.java#L1663
