### ISSUE TITLE
How to run gumtree under Ubuntu

### ISSUE THREAD

**Issue by Kaka727** [GumTreeDiff/gumtree#123]
I have unzipped the file /dist/build/distributions but there is no binary code as follows
![image](https://user-images.githubusercontent.com/33283686/51224844-c7cc2b00-1982-11e9-9af4-f51d880ce83a.png)

Thus the commend gumtree cannot found 
![image](https://user-images.githubusercontent.com/33283686/51224822-acf9b680-1982-11e9-875b-20c2babd5183.png)
 
What's wrong?

**Comment by jrfaller** [comment]
just go in gumtree/bin/ and voilà!
