### ISSUE TITLE
How to get webdiff output in java?

### ISSUE THREAD

**Issue by kimsbrian** [GumTreeDiff/gumtree#124]
I'm having a little trouble understanding how to turn the list of actions into something human readable like the webdiff. For example, a simple insert statement "System.out.println("Anything"); turns into 5 inserts instead of one insert like "System.out.println("Anything");" on line X. I'm quite unfamiliar with AST's if anyone could help me out. I understand that this is not a troubleshooting forum and if this is not acceptable, I'm very sorry.

**Comment by jrfaller** [comment]
There is no such thing implemented in GumTree. However, you can implement a new pretty printer of diff, by using actions and source and destination file contents, like we do in webdiff client for instance.
