### ISSUE TITLE
Is gen.javaparser available by Maven now?

### ISSUE THREAD

**Issue by 11510746** [GumTreeDiff/gumtree#128]
I only find one based on Eclipse JDT

**Comment by monperrus** [comment]
FYI, there are 4 different "Gumtree for Java",

  * JDT backend (default)
  * Spoon backend, see SpoonLabs/gumtree-spoon-ast-diff
    <https://github.com/SpoonLabs/gumtree-spoon-ast-diff/> for how to use it.
  * JavaParser backend 
  * srcML backend

(I'd recommend the Spoon backend, but I'm biased :-)

**Comment by jrfaller** [comment]
Hi!

No sorry I have yet to release the version to maven.

**Comment by jrfaller** [comment]
OK it has been released!

**Comment by monperrus** [comment]
Cool, but I don't see it https://search.maven.org/search?q=gumtree

Any idea?

**Comment by jrfaller** [comment]
https://search.maven.org/search?q=g:com.github.gumtreediff
