### ISSUE TITLE
not-so-great diff output for chain syntax

### ISSUE THREAD

**Issue by ycaxgjd** [GumTreeDiff/gumtree#129]
Hey, [this](https://github.com/ycaxgjd/tmp/blob/master/chain_syntax.png) is one diff output for chain syntax.
It looks not so great comparing with [this](https://github.com/ycaxgjd/tmp/blob/master/multilines_string.png), one diff output for multilines string.

**Comment by jrfaller** [comment]
Hi,

Yes it is not great. Can you post the files first the first case somewhere?

**Comment by ycaxgjd** [comment]
Here they are
https://github.com/ycaxgjd/tmp/blob/master/oldChainSyntax.java
https://github.com/ycaxgjd/tmp/blob/master/newChainSyntax.java

**Comment by jrfaller** [comment]
I reproduce your behavior, I think this is due to how I represent MethodInvocation, I modified the output of JDT because it is ambiguous for `a.b()` and `a(b)` but it seems to complicate the diff of call chains. However I am not sure how to deal with this...

**Comment by ycaxgjd** [comment]
I have no idea either :(

**Comment by jrfaller** [comment]
mmm same behavior with javaparser and JDT :(
