### ISSUE TITLE
Extend Generators.getTree() to accept as input the contents of a file (as String or InputStream)

### ISSUE THREAD

**Issue by tsantalis** [GumTreeDiff/gumtree#132]
Currently, Generators.getTree() accepts only a file path.
This is very restrictive when working with blobs directly from a `.git` folder.
It would be great to enable file contents as input in the form of String on InputStream.

**Comment by jrfaller** [comment]
Thanks for you feedback! I see the problem. I will add a utility function to hava a tree from a Reader to, which is already implemented in the TreeGenerator interface. Would it do the trick?

**Comment by tsantalis** [comment]
I am using jgit, which provides the following API for loading git objects
```
ObjectLoader loader = repository.open(objectId);
ObjectStream stream = loader.openStream();
```
`org.eclipse.jgit.lib.ObjectStream` extends `java.io.InputStream`
Then, I am using a StringWriter to extract the file contents as follows:
```
StringWriter writer = new StringWriter();
IOUtils.copy(loader.openStream(), writer);
```
If you want to make it super-flexible you can have a method `getTreeFromFileContents(String)`
that accepts the file contents as String,
or `getTree(java.io.InputStream)`
or `getTree(java.io.Reader)` as you suggested

**Comment by tsantalis** [comment]
Alternatively, I can use
```
new JavaParserGenerator().generateFromReader();
new JavaParserGenerator().generateFromStream();
new JavaParserGenerator().generateFromString();
```

**Comment by jrfaller** [comment]
mmm I might have answered too fast. Unfortunately, without the file name the generator registry cannot know which tree generator to use to load a given string (could be Java code, could  be C code), therefore I am not sure how to deal with that. Currently, the registry use the file extension to decide. Therefore I am not convinced that the registry is the good place to have this method, unless you have an idea ;). However, you can still use directly the methods your mention from a given generator.

**Comment by tsantalis** [comment]
getTree(String content) can have an additional parameter `language` as an enumerated type with all supported languages as constants.
Based on the passed argument, you can instantiate the corresponding generator.

I tried to run gumtreediff on blobs using directly the JavaParserGenerator,
but I noticed the diff output is different compared to the Generators.getTree() approach.
Is there an explanation for that?

**Comment by jrfaller** [comment]
Yes I thought of that but in this case I am not sure why one would want to use the registry, if he already knows the language, he can directly choose the right parser non? Maybe for languages that have several parsers?

I am curious about the difference you note, normaly the only job of the Registry is to redirect the String or File to the right tree generator, therefore it should make no difference at all.

**Comment by jrfaller** [comment]
ok another solution would be to do similarly to the following method : `public TreeContext getTree(String generator, String file)` since it already takes as input the generator name.

**Comment by tsantalis** [comment]
Regarding the diff output difference:
The commit analyzed is https://github.com/JetBrains/intellij-community/commit/7ed3f273ab0caf0337c22f0b721d51829bb0c877
[diff1.txt](https://github.com/GumTreeDiff/gumtree/files/2965780/diff1.txt) is the diff with `Generators.getTree()` approach
[diff2.txt](https://github.com/GumTreeDiff/gumtree/files/2965781/diff2.txt) is the diff with `new JavaParserGenerator().generateFromString()` approach
[input.zip](https://github.com/GumTreeDiff/gumtree/files/2965808/input.zip) contains the java files given as input

**Comment by tsantalis** [comment]
Regarding the generator name passed as a String:
This is not so safe as an API, because you allow to pass any String value.
Replacing that with an `enum`, would make it more safe.

**Comment by jrfaller** [comment]
OK regarding the first problem, I understand now, the default tree generator used when parsing Java is JdtTreeGenerator, and by hand you use JavaParserGenerator, therefore the diffs are different. If you use `new JdtTreeGenerator()` you'll have the same result.

Regarding your second suggestion, I agree that it is not safe, but for plugins in GumTree we are in an open world assumption, meaning that we want to allow developers to add generators, clients or matchers that are not part of the "official" distribution, that's why do no use an enum. We could ask for a subclass of TreeGenerator but if you already have the class at hand you can instantiate directly.

**Comment by tsantalis** [comment]
Indeed, with `new JdtTreeGenerator()` I am getting the same diff.
I have one final question. I am using `action.getNode().getType()` to get the ASTNode type.
Is this the same int as the named constants declared in Eclipse JDT ASTNode?
Can I do something like `action.getNode().getType() == ASTNode.SIMPLE_NAME`
to get actions on SimpleName nodes?

**Comment by jrfaller** [comment]
Yes it is!

Additionnally you can look into the getTypeLabel method that requires the TreeContext et gives you the label of the type.
