### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by umabalaji18** [GumTreeDiff/gumtree#136]
Hi,

I was using gumtree through this command for one whole day 
gumtree webdiff C:\Users\User\script1\GT\classA.java C:\Users\User\script1\GT\classB.java
and http://127.0.0.1:4567 I was using this to see the output in the browser.

Suddenly I am getting 500 Internal Server Error, I tried clearing all the cache and cookies as well. But it is not working for a long time. Is it a server issue ?

**Comment by jrfaller** [comment]
No, I think  it's an  error with the files or parser. Try just parsing the files (gumtree parse).

**Comment by jrfaller** [comment]
Did you manage to try parsing?

**Comment by jrfaller** [comment]
I am closing this since I do not have enough information to reproduce the bug.
