### ISSUE TITLE
Docker image on mac

### ISSUE THREAD

**Issue by njeans** [GumTreeDiff/gumtree#137]
I tried building the docker image on mac and it failed. Is there a prebuilt image available?

<img width="1674" alt="Screen Shot 2019-04-08 at 10 48 47 AM" src="https://user-images.githubusercontent.com/12213974/55733705-4cf83680-59ec-11e9-8e7b-22d4d1c90953.png">

**Comment by jrfaller** [comment]
normally ocaml is OK now and dockerfile should build.

**Comment by jrfaller** [comment]
sorry there was an additional bug. it is fixed now.
