### ISSUE TITLE
rhino doesn't support es6?

### ISSUE THREAD

**Issue by wz649588** [GumTreeDiff/gumtree#139]
Hello. I'm using this tool to get the diff between .js files. It seems the Rhino parser can't parse .js files in es6 version (import or export or class). I'm wondering if I used it correctly......Any solutions?

**Comment by jrfaller** [comment]
apparently, not fully : http://mozilla.github.io/rhino/compat/engines.html

the solution would be to use another parser, do you know any?

**Comment by wz649588** [comment]
Thanks for your reply. I searched for a long time about it. It seems only the estree tool (such as esprima) can handle latest version of es javascript. However what they are going to output is javascript Object instead of AstNode in java....... I'm thinking if it's possible to convert the estree(javascript Object) to java AstNode, do you think it's easy or not? Or do you think writing a js diff based on javascript is more easier? Thank you.

**Comment by wz649588** [comment]
And another solution I can get is to first convert the latest version .js file to compatible ES5 .js file by using  a tool called babel, which is based on javascript, and then by using your tool to get the parsing result. But my advisor encouraged me to use the estree...... hmmm

**Comment by morandat** [comment]
What about javax.script.* ?
There is maybe, not for tomorow, something to do with.

**Comment by jrfaller** [comment]
estree tool is a cool solution too, we have several external parser in GumTree and also a standard exchange format.

**Comment by wz649588** [comment]
Just found that you have a .json parser and can convert a .json to  an Itree, which is great. Since estree is a kind of a java Object as well as a .json file, so maybe I'm going to try it out.

**Comment by jrfaller** [comment]
yes you can try that ;) our json parser in rhino by the way.

however I think that you won't have as good result as having directly a JS AST!

**Comment by wz649588** [comment]
I tried the json parser, it works pretty well. So this is my current solution to the es6 javascript diff problem, first use esprima(or whatever estree tool) to get the json file of the estree, then use your json parser and diff tool to get the difference. Thank you.

**Comment by jrfaller** [comment]
OK nice to know that it works!
