### ISSUE TITLE
JSON format output from gumtree

### ISSUE THREAD

**Issue by ChunghaSung** [GumTreeDiff/gumtree#144]
Hi, I am trying to import the output of gumtree (both AST and diff output) as JSON format to Python program.

I saw some issues related with importing AST from Python to Gumtree, but I could not find the other way around..

Could you let me know if there is a way to pass the object of output (AST and diff) as JSON format to python?

**Comment by jrfaller** [comment]
There is a JSON output format for the diff that you can use. Take a look into ActionIoUtils. Cheers.

**Comment by ChunghaSung** [comment]
Is there to get JSON format of AST?

I looked them and it is JSON of diff.

**Comment by monperrus** [comment]
For Java, there is one in [gumtree-spoon](https://github.com/SpoonLabs/gumtree-spoon-ast-diff/)

See @martinezmatias's class `Json4SpoonGenerator`:  https://github.com/SpoonLabs/gumtree-spoon-ast-diff/blob/master/src/main/java/gumtree/spoon/builder/Json4SpoonGenerator.java
