### ISSUE TITLE
Question about using APIs to set up options

### ISSUE THREAD

**Issue by ChunghaSung** [GumTreeDiff/gumtree#145]
Hi, I am trying to use APIs in my Javacode instead of using client.

But, I am not sure how to set up options such as using "srcML" for C and setting the default path of "srcML".

Based on the code, it looks like I need to access Client or Context from Generator.. but, I am not sure how to set up these options.

Right now, I am running diff for two files like this.

```
Run.initGenerators();
srcTreeContext = Generators.getInstance().getTree(srcPath);
dstTreeContext = Generators.getInstance().getTree(dstPath);
srcTree = srcTreeContext.getRoot();
dstTree = dstTreeContext.getRoot();
Matcher m = Matchers.getInstance().getMatcher(srcTree, dstTree); // retrieve the default matcher
m.match();
ActionGenerator g = new ActionGenerator(srcTree, dstTree, m.getMappings());
g.generate();
actions = g.getActions();
```

Please give me some suggestions.. it would be really helpful for me to use it.

**Comment by jrfaller** [comment]
Hi!

If you are using directly GumTree from java, you can directly instantiate a SrcmlTreeGenerator. To change the default path of srcml, you have system property `gt.srcml.path`.

**Comment by ChunghaSung** [comment]
Thank you! :)
