### ISSUE TITLE
AST from String

### ISSUE THREAD

**Issue by farhaanbukhsh** [GumTreeDiff/gumtree#147]
So this is more of an information than an issue, what I am trying to do is call or use GumTree form a python backend using PY4J, now we have already generated AST in python, can I somehow serialise it in python and send to GumTree and deserialise it there and use it? 

so I was thinking about this:

AST --> converted as string --> send to GumTree --> Take the string and convert it into TreeContext to be used --> getMappings / Action and send back

Help will be highly appreciated

**Comment by jrfaller** [comment]
Hi!

This is great news, our python convertor is not working really well in some cases, therefore it would be really nice to have better tree generator for python. Your idea is right the process is to have a python program that produces a XML in a dedicated format that will be loaded by GumTree that will then be able to diff python files.

You can see the current implementation for python here :

https://github.com/GumTreeDiff/gumtree/tree/develop/gen.python/src/main/java/com/github/gumtreediff/gen/python

and the python program is here :

https://github.com/GumTreeDiff/pythonparser

The XML format is like that :
```
<tree type="12" label="" typeLabel="method_declaration" pos="12"
length="22>
  <tree type ="2" label="foo()" typeLabel="identifier" pos="12" length="5"/>
  <tree type="8" label="" typeLabel="block" pos="18" length="4>
    ...
  </tree>
</tree>
```

**Comment by farhaanbukhsh** [comment]
No, what I was actually talking about is sending AST from Py4J to GumTree Java program, is there a way I can achieve it? Sorry for the miscommunication 😄 

We need a way to send across ASTs because we already have generated ASTs and we don't want to spend more effort doing the same in GumTree. So if we could do something on these lines it would be great.

**Comment by farhaanbukhsh** [comment]
How can I get more information of the XML format and then what function to use to load it in GumTree?

**Comment by jrfaller** [comment]
You can look into TreeIoUtils
