### ISSUE TITLE
Discussion: Would Tree-sitter be useful for GumTree?

### ISSUE THREAD

**Issue by zokier** [GumTreeDiff/gumtree#148]
Hi, I just stumbled upon this project which seems pretty neat indeed. Sorry if this post is out of place here.

[Tree-sitter](http://tree-sitter.github.io/tree-sitter/) is a parser library developed for the popular Atom editor to provide syntax highlighting there. What made me think that it might be something of use for GumTree is that it already has a number of parsers available for different languages, and hopefully more coming in the future. So it possibly could be a relatively quick way of expanding the language coverage of GumTree, providing unified API for the syntax trees of the supported languages.

This is purely just FYI, I don't know if this is interesting for you. Unfortunately I do not right now have the resources to contribute here :(

**Comment by jrfaller** [comment]
Hi!

Thanks a lot for the pointer.

**Comment by indolering** [comment]
Have you seen [JSitter](https://github.com/JetBrains/jsitter)?  It is is actively maintained by JetBrains   and is [currently](https://github.com/tree-sitter/tree-sitter/pull/360) the best route for using Tree-sitter in Java.

**Comment by jrfaller** [comment]
Thanks for the pointer! It would be really cool to integrate it with GumTree!

**Comment by indolering** [comment]
> Thanks for the pointer!

There was also some talk about using the WASM build, which is _possible_ but the state of WASM and Graal.js make it a PITA.  I can tell you more if you want.

> It would be really cool to integrate it with GumTree!

Yeah, I've always run into problems with ANTLR.  The performance is bad (and the main developer doesn't care) and many of the grammars don't handle new or broken syntax well.  It might be **possible** to hack a rough AST from a Language Server using `foldingRange` and `documentSymbol`, but they can also be slow and it would require a lot of work.

OTOH, Tree-sitter is designed to handle broken code, parse everything in milliseconds, and is commercially supported by Github.  It would be awesome if GumTree could suddenly handle the ~26 languages supported by Tree-sitter!

**Comment by indolering** [comment]
Oh, and ANTLR can't handle common formats like Markdown!  But Tree-sitter (with it's LGR parser) can.

**Comment by jrfaller** [comment]
Any of you two have already used JSitter?

**Comment by indolering** [comment]
Nope, I don't use Java in my day-to-day.

**Comment by jrfaller** [comment]
Damn, if only I had the snippet that allows to create an AST from a stream it would be able to quickly integrate it. I will try to find an intern!

**Comment by indolering** [comment]
> Damn, if only I had the snippet that allows to create an AST from a stream I would be able to quickly integrate it. I will try to find an intern!

Post a request asking for one!

**Comment by jrfaller** [comment]
Hi all,

I made some progress using the tree-sitter parse -q -x command.

Example output

```
<program>
  <import_declaration>import
    <scoped_identifier>
      <scoped_identifier type="scope">
        <identifier type="scope">java</identifier>
.
        <identifier type="name">util</identifier>
</scoped_identifier>
.
      <identifier type="name">Random</identifier>
</scoped_identifier>
;</import_declaration>

  <class_declaration>
    <modifiers>public</modifiers>
class
    <identifier type="name">Example</identifier>

    <class_body type="body">{
      <method_declaration>
        <modifiers>public</modifiers>

        <void_type type="type">void</void_type>

        <identifier type="name">hello</identifier>

        <formal_parameters type="parameters">()</formal_parameters>

        <block type="body">{
          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"Hello everybody!"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"This code is a magnificent example"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"For the ASE 2014 conference"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"It draws a number at random"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"Adds 10"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"Multiplies by 10"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <string_literal>"And displays it"</string_literal>
)</argument_list>
</method_invocation>
;</expression_statement>

          <local_variable_declaration>
            <type_identifier type="type">Random</type_identifier>

            <variable_declarator type="declarator">
              <identifier type="name">r</identifier>
=
              <object_creation_expression type="value">new
                <type_identifier type="type">Random</type_identifier>

                <argument_list type="arguments">()</argument_list>
</object_creation_expression>
</variable_declarator>
;</local_variable_declaration>

          <local_variable_declaration>
            <integral_type type="type">int</integral_type>

            <variable_declarator type="declarator">
              <identifier type="name">i</identifier>
=
              <method_invocation type="value">
                <identifier type="object">r</identifier>
.
                <method_invocation_name type="name">
                  <identifier>nextInt</identifier>
</method_invocation_name>

                <argument_list type="arguments">()</argument_list>
</method_invocation>
</variable_declarator>
;</local_variable_declaration>

          <expression_statement>
            <assignment_expression>
              <identifier type="left">i</identifier>
+=
              <decimal_integer_literal type="right">10</decimal_integer_literal>
</assignment_expression>
;</expression_statement>

          <expression_statement>
            <assignment_expression>
              <identifier type="left">i</identifier>
*=
              <decimal_integer_literal type="right">10</decimal_integer_literal>
</assignment_expression>
;</expression_statement>

          <expression_statement>
            <method_invocation>
              <field_access type="object">
                <identifier type="object">System</identifier>
.
                <identifier type="field">out</identifier>
</field_access>
.
              <method_invocation_name type="name">
                <identifier>println</identifier>
</method_invocation_name>

              <argument_list type="arguments">(
                <identifier>i</identifier>
)</argument_list>
</method_invocation>
;</expression_statement>
}</block>
</method_declaration>
}</class_body>
</class_declaration>
</program>
```

**Comment by quentinLeDilavrec** [comment]
Hi all,

I have a working version of GumTree that uses tree-sitter through JNI.
In fact, I tried and build over 2 existing projects :
- [jsitter](https://github.com/JetBrains/jsitter) and,
- [java-tree-sitter](https://github.com/serenadeai/java-tree-sitter).

I've updated both to the latest version of tree-sitter (core and grammars).
And I should say that _jsitter_ might not be the best route to a maintainable use of _tree-sitter_ (It seems that it is not actively maintained anymore).
Actually, I started with _java-tree-sitter_, it took me something like 1 hour to integrate,
while yesterday, just upgrading _jsitter_ took me the full day (integration was fast as It was my second time integrating a parser :) ).
The reason lie in the way _jsitter_, for performance reasons, uses _Unsafe_ to access though direct memory mapping to an internal tree-sitter data-structure. So it is not very stable. But I should say that it must be faster and that I prefer the repository structure.

On the side of how exactly it integrates with Gumtree, _java-tree-sitter_ is setup to package a jar that contains a single compiled library (.so, .dll or .dylib) for the core and grammars. So it is easy to load but not modular. For _jsitter_, the core is loaded similarly but for each language there is an additional library to load (for now, I manually copy it to src/main/resources/).
It is more modular, but I am not sure about how the language libraries should be handled (maybe a jar for each language is the best, but I have not tried yet).

Note: For now, I only focused on parsing java code, but other languages should be really easy to integrate.

**Comment by jrfaller** [comment]
Hi Quentin and thanks a lot for your analysis.

The downside I see with jsitter/java-tree-sitter is that it requires dedicated native code for a given OS, am I right? If it's the case it will be kind of a burden to integrate (for instance a maven dep for each OS?). However the decoders are easy to create as it consists only in parsing a GumTree compatible XML. We can work out a "generic" caller I believe that do not care of which particular tree-sitter implementation it launches.

The way I see it is that tree-sitter is kick ass because it has the potential to parse a wide range of language, so the best IMHO would be to have only one "gumtree-sitter" project that is compatible with as many language supported by tree-sitter as possible, and one gumtree-sitter-generator that calls and decodes the stuff produced by the aforementioned project.

WDYT ?

**Comment by quentinLeDilavrec** [comment]
You are right, it needs a native library. So what about making a jar which only contains the java "header" and let the user install the OS dependent library elsewhere?

I see your point on just decoding an XML output and just get more language for GumTree.
But I also see performances gains in using tree-sitter.
Actually, I would like to make use of the rest of the tree-sitter API.
I think it might avoid recreating an entire GumTree Tree for each version.

About sharing only one tree-sitter generator for all the handled languages, I totally agree but to be clean I believe that the generator registering mechanism should be extended a bit.

**Comment by jrfaller** [comment]
Hi Quentin,

You're right I did forget about the performance potential of tree-sitter. However, currently the parsers are dropped as soon as the gumtree AST is built, and I believe that changing this behavior would induce a drastic change of the internal code of generators, and a drastic change of the API, and would be kind of a burden since only tree-sitter would benefit from that. So maybe the best is to do this by hand by maintaining the tree-sitter AST outside gumtree, and giving the possibility for tree-sitter generators to supply an already made AST to speed-up parsing. Do you happen to know how the incremental parsing is handled at the API viewpoint in tree-sitter?

I agree that the generator registry is not ideal, do you have more specific idea on how to proceed?

Cheers.

**Comment by indolering** [comment]
Can't Graal interpret LLVM at runtime now?

**Comment by quentinLeDilavrec** [comment]
Maybe we can quickly benchmark each approach? Is there some already established way of benchmarking performances of Gumtree?

For the use of incremental parsing, I looked at it in details.
To use incremental parsing, it needs the last CST and the set of edited ranges,
but contrary to syntax highlighting in IDEs when parsing commits, it is not readily available data.
Even so, I have some ideas about how to use it in my particular use case. :)

I also found some old repo packaging native libraries for multiple OSes on https://github.com/java-native-access/jna, namely https://github.com/protonail/leveldb-jna and https://github.com/protonail/jna-bolt.

For now, I did not mess with the generator registry, so I have no particular opinion about it.
An easy fix is to pass a parser instance to the generator.


I don't know much about this feature of Graal, do you have some links? an example repo?

**Comment by jrfaller** [comment]
Yes you are right, we do not have such thing as an edited range in GumTree since we work outside any editor. Therefore it might not be worth it to break the API ;)

I think the right way to do it is therefore for you to create a custom tree-generator, where you control the constructor and can supply the information you need to perform incremental parsing. Even better, we can have a "classic" tree-sitter generator that does the classic job of creating a GumTree AST, this generator deal with all tree-sitter compatible languages. Then you can extend it to add incremental parsing.

WDYT?

**Comment by indolering** [comment]
> I don't know much about this feature of Graal, do you have some links? an example repo?

 The basics is that Graal interprets LLVM bitcode directly.  [Popular intro blogpost](https://blog.plan99.net/graal-truffle-134d8f28fb69), but Google is your friend. 

> Maybe we can quickly benchmark each approach?

IIRC there is a ~20% performance hit vs pure C.  However, Graal is often faster than calling out to native because it is able to eliminate memcopies across the FFI.

**Comment by quentinLeDilavrec** [comment]
Ok, @jrfaller I will do a PR when it's ready.

@indolering I thought that you had a specific idea in mind. Just telling me that I should use a tech over another without good arguments won't go far. By the way, jsitter is not impacted by memcopies overhead, because it directly read the native memory of tree-sitter, so in the end, it will be faster than using Graal.

**Comment by indolering** [comment]
> @indolering I thought that you had a specific idea in mind. 

I suggested interpreting the LLVM bitcode directly to save you the effort of maintaining platform specific ports or relying on user installed libraries.

> Just telling me that I should use a tech over another without good arguments won't go far.

My apologies if "Google is your friend" came across as a passive aggressive comment; I honestly spent some time trying to find specific benchmarks and better links, but then gave up and figured you would be better off digging into it on your own.  I don't have experience with C and haven't even touched Java in years.

>  By the way, jsitter is not impacted by memcopies overhead, because it directly read the native memory of tree-sitter, so in the end, it will be faster than using Graal.

Graal will JIT the LLVM bitcode and I don't see even a 2x slowdown as a big deal; running Gumtree is a high latency operation that is generally only done during commit.  But if you are willing to put in the effort, go for it!  😄.
