### ISSUE TITLE
Comparing python sources doesn't work on Windows

### ISSUE THREAD

**Issue by KOLANICH** [GumTreeDiff/gumtree#151]
I have tried to overcome that with a cmd script put into various dirs without any success.

**Comment by jrfaller** [comment]
ok thanks for the BR. Just for info you can use the docker image of Gumtree on windows that will resolve this problem. Also, the python parser is not very good and have not been really tested, unfortunately.

**Comment by jrfaller** [comment]
I am tagging this help wanted since I do not have a Windows machine ;)

**Comment by jrfaller** [comment]
And well there might be a good parser here : https://github.com/davidhalter/parso (posting this here to remember the link)

**Comment by KOLANICH** [comment]
> Just for info you can use the docker image of Gumtree on windows that will resolve this problem. 

No, I cannot.

>And well there might be a good parser here : https://github.com/davidhalter/parso (posting this here to remember the link)

It may be. But I don't understand why do you think that just `ast` is not enough for this use case.

**Comment by jrfaller** [comment]
For instance this : https://github.com/gristlabs/asttokens/issues/27

**Comment by lavenzg** [comment]
Is there a version of gumtree using the parso parser? The current python parser cannot handle a few python files in my current project.

**Comment by lavenzg** [comment]
Maybe the reason of failures is that ASTs on python2 and pyton3 are different. I changed the pythonparser module to python3, it can fix some failures, but it fails on some other python files.
Finally I have to replace asttokens with parso. Now it works on my current collected python files.

**Comment by jrfaller** [comment]
@lavenzg I have updated pythonparser a bit to simplify the code and to have it produce a XML directly compatible with gumtree. Could you show me how I can change asttokens to parso? A pull-request would be great :)

**Comment by jrfaller** [comment]
ok all, we have now parso backed python parser, therefore I will close all python related issues, post new issues for the matter of python integration in GumTree.
