### ISSUE TITLE
How can I generate TreeContext from files?

### ISSUE THREAD

**Issue by chijianlei** [GumTreeDiff/gumtree#158]
I have used Gumtree from nearly one year but there are many issues in the old version of srcml generator and jdt generator. When I try to use the latest develop branch I find that the method named gen.TreeGenerator.generatefromfile() is deleted. It seems that a new Generator class is used. I'm not sure how can I utilize it, parse the local file and generate the TreeContext now.

By the way, what's the difference between develop branch and master branch? I'm curious about that. Maybe I should use the latest master branch?

Thanks!

**Comment by chijianlei** [comment]
I think I know how to parse the local file and generate the TreeContext now.
However, there is one bug I find in Jdtgenerator, plz see #159

**Comment by jrfaller** [comment]
OK closing this ;)
