### ISSUE TITLE
Server internal error when viewing a diff via git

### ISSUE THREAD

**Issue by hrj** [GumTreeDiff/gumtree#16]
I am trying to use gumtree with git. After launching gumtree via difftool, I am able to browse to `localhost:4754` but when trying to view the diff via this URL: `http://127.0.0.1:4754/fr/labri/gumtree/client/diff0`, it just returns this message:
```
SERVER INTERNAL ERROR: Serve() returned a null response.
```

There is no message in the terminal.

**Comment by jrfaller** [comment]
Hi!

Thanks for the report. Usually this is the sign that something went wrong when computing the diff. Can you post the error message shown in the console?

Cheers.

**Comment by hrj** [comment]
Hi,

There was no error message in the console, only in the browser window. If it matters, my git version is 1.9.1.

**Comment by jrfaller** [comment]
OK, Git must be hiding the underlying error message. Would it be possible for you to use gumtree directly from the command line (for instance just clone your git repo into two different folders in a temp directory, checkout the wanted versions, remove the .git, and run GumTree client) and to report the error message?

**Comment by jrfaller** [comment]
OK I have updated the VCS integration page and normally it should be functioning.
