### ISSUE TITLE
No generator found for file: 1.java

### ISSUE THREAD

**Issue by tzpranto** [GumTreeDiff/gumtree#160]
I am trying to get tree diff of two java files using the API. When I run the code I get the error No generator found. Should I specify anything explicitly in any place for java parser? 
can you be more specific about this "Note that if you want to have all available commands and parsers at your disposal, you need to set up the classpath to include the projects of the gumtree distribution."?

System.out.println("Starting API test");
        Run.initGenerators();
        String file1 = "1.java";
        String file2 = "2.java";
        File tempFile = new File(file2);
        boolean exists = tempFile.exists();
        if(exists) System.out.println("File exists"); //returns true

        try {
            ITree src = Generators.getInstance().getTree(file1).getRoot();
            ITree dst = Generators.getInstance().getTree(file2).getRoot();
            Matcher m = Matchers.getInstance().getMatcher(src, dst); // retrieve the default matcher
            m.match();
            m.getMappings(); // return the mapping store
        } catch (Exception e) {
            e.printStackTrace();
        }

**Comment by jrfaller** [comment]
If you know what is the kind of file you parse you can instantiate directly the good kind of generators, i.e. JdtTreeGenerator in your case.
