### ISSUE TITLE
How to link content of diff and parsed AST?

### ISSUE THREAD

**Issue by KingGoldXu** [GumTreeDiff/gumtree#161]
Hello!
I used `gumtree diff file1.java file2.java` to get diff like this:

```
Insert ImportDeclaration(27) into CompilationUnit(823) at 13
Insert QualifiedName: okhttp3.Headers(26) into ImportDeclaration(27) at 0
Insert SimpleType: Headers(321) into VariableDeclarationStatement(327) at 0
Update SimpleName: Header(320) to Headers
...
```

then I used `gumtree parse file1.java` and `gumtree parse file2.java` to get the json format of AST.
But I don't know which node in AST is the number(for example 27) in diff match with, for there is no index numbers in json AST.
How can I get the match or How to attach a index to each node in AST?

Thanks

**Comment by monperrus** [comment]
See https://github.com/SpoonLabs/gumtree-spoon-ast-diff/ Best regards, --Martin

**Comment by jrfaller** [comment]
In the latest develop commits, we have updated textual diff to include text position of elements such as :

~~~~
insert-node
---
Modifier: public [448,454]
to
MethodDeclaration [448,556]
at 0
===
~~~~

Would it work for you?

If you really need the AST node (GumTree's version of it anyway) I suggest to use the Java API and not the command line.
