### ISSUE TITLE
No generator error when parse C file

### ISSUE THREAD

**Issue by Crystallee612** [GumTreeDiff/gumtree#163]
I want to use an API example to parse a C file (test1.c), but I received the following error:

Exception in thread "main" java.lang.UnsupportedOperationException: No generator found for file: test1.c
	at com.github.gumtreediff.gen.Generators.getTree(Generators.java:42)
	at Xtest.main(Xtest.java:18)

The code snippet is:

public class Xtest {
    public static void main(String[] args) {
        Run.initGenerators();
        String file = "test1.c";
        TreeContext tc = null; // retrieve the default generator for the file
        {
            try {
                tc = Generators.getInstance().getTree(file);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
        ITree t = tc.getRoot(); // return the root of the tree
        System.out.println(TreeIoUtils.toLisp(tc).toString());
    }
}

My dependencies are:

<dependencies>
		<dependency>
			<groupId>com.github.gumtreediff</groupId>
			<artifactId>client</artifactId>
			<version>2.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.github.gumtreediff</groupId>
			<artifactId>core</artifactId>
			<version>2.1.2</version>
		</dependency>
		<dependency>
			<groupId>com.github.gumtreediff</groupId>
			<artifactId>gen.c</artifactId>
			<version>2.1.2</version>
		</dependency>
	</dependencies>

**Comment by jrfaller** [comment]
If you know first hand what is the file type, I advise you to use directly the TreeGenerator subclass you want, instead of using the registry (which can be a  pain to  use because we use classindex).

Cheers!
