### ISSUE TITLE
Gumtree problem diff python files

### ISSUE THREAD

**Issue by lucaresearch** [GumTreeDiff/gumtree#165]
Hi,

sorry for the disturb, your gumtree project is amazing! 

I did not find the solution online for my problem. I am trying to use gum tree for a diff between two python files. i copied pythonparser file on /tmp and I added it on the system path, but when, for example, I run: ./gumtree diff main.cpp main2.cpp

the output is a generic error without other information:

** Error while running client diff: java.lang.RuntimeException:

The same error using two .cpp files.

I tried also copy pythonparser in usr/bin folder that is in my system path, but the same problem. Do you know why?

![gumtree](https://user-images.githubusercontent.com/26833315/65753803-028c8280-e110-11e9-841b-8f14e6ab7fdd.png)

**Comment by jrfaller** [comment]
Could you attach the code of your two files?

Regards!

**Comment by njuxc** [comment]
I have a same problem when using gumtree for Python.

**Comment by jrfaller** [comment]
do you have the files so I can reproduce?

**Comment by hayleefay** [comment]
I get the same error as above when I run it with python files.
![image](https://user-images.githubusercontent.com/12599305/72631363-26bfd980-3922-11ea-85b3-9b4ca67c5d1d.png)
Here are the files:
```python
#one.py
test1 = 1
test2 = 2
```
```python
#two.py
test1 = 3
test2 = 4
```

**Comment by jrfaller** [comment]
Hi @hayleefay and thanks for your report!

I used your two files and everything works as expected for me.

Did you try that with the latest commit from develop and pythonparser?

Cheers!

**Comment by hayleefay** [comment]
Thanks for the response, @jrfaller ! I was using the latest release v2.1.2 (Elm) with the latest commit from pythonparser. I built gumtree from source instead to be on the latest commit from develop, but I am still getting the same error. Java files work great, but not python.

Am I doing something wrong with pythonparser? I downloaded the file and put it in my path and made it executable.

**Comment by hayleefay** [comment]
@jrfaller, I found my issues! First, I was using Python 3.7 instead of (RIP) 2.7 and, second, I didn't have the dependencies needed for the pythonparser.

**Comment by jrfaller** [comment]
Thanks for the feedback @hayleefay! This is not good that GumTree do not work with Python 3.7. I am not sure however that's is possible to write a backward compatible parser for both versions. Too bad I do not have enough time to look at Python support seriously.
W.r.t. your problem, it should be fixed by improving pythonparser install guide, I will open an issue there!

@lucaresearch if your are still on this :) can you try @hayleefay solution?

**Comment by jrfaller** [comment]
Ok there is now a new parso backed parser for python, closing this. Feel free to post a new issue in case of problems.
