### ISSUE TITLE
license change: double license GPL-MIT?

### ISSUE THREAD

**Issue by monperrus** [GumTreeDiff/gumtree#167]
Some companies do not use Gumtree because it is under GPL (eg @henrikplate's at SAP).

What about moving to a double license GPL-MIT? (as we've done for Spoon recently).

**Comment by jrfaller** [comment]
Hi @monperrus !

I am not sure of what you are asking. The current license of GumTree is LGPL v3, not GPL, which is already very flexible. What would be wrong with the LGPL license that would warrant the use of a MIT license?

Cheers!

**Comment by monperrus** [comment]
Cool. What is GPL at some point in the past?

**Comment by monperrus** [comment]
@henrikplate is LGPL ok at SAP?

**Comment by jrfaller** [comment]
Hi Martin, I believe it has always been a LGPL project since we wanted to enable using the project without too many legal consequences.

**Comment by henrikplate** [comment]
The decision to use [ChangeDistiller](https://www.ifi.uzh.ch/en/seal/research/tools/changeDistiller.html) (Apache License v2) in favor of GumTree was taken at a time when our project was not yet open source. At that time, and for commercial projects in general, the Apache License is simply a no-brainer, while the LGPL requires a little more thought and - potentially - interactions with the respective IP/legal departments. Now that the project is open source, I guess it would be easily possible to switch to GumTree.

**Comment by jrfaller** [comment]
OK good to know, I will consider this when choosing the license for my next tool!
