### ISSUE TITLE
No generator found

### ISSUE THREAD

**Issue by HickeyHsu** [GumTreeDiff/gumtree#168]
TreeContext tc = Generators.getInstance().getTree(file);

java.lang.UnsupportedOperationException: No generator found for file: /home/hickey/dev/data/test_dataset/test.java

I knew that i can use JdtTreeGenerator directly if i know the file to be parsed is .java; however i want to know how to solve this problem if im not sure the type of file to be parsed?

**Comment by jrfaller** [comment]
You managed to do it ?
