### ISSUE TITLE
Does getType return the same integer between sessions and for all trees in java?

### ISSUE THREAD

**Issue by EikeStein** [GumTreeDiff/gumtree#169]
Hi,
As the title says I need to know if the type of a tree is constant over different tree(-context)s and sessions. So for example, if MethodDeclaration always has type-value 31.

For a larger project I am currently writing a bunch of helper methods, such as "find all methods" and I would prefer if those methods only parameter was the Tree and not the treecontext as well (for getting the typeLabel).

Thanks!

**Comment by jrfaller** [comment]
Hi!

Good question ;)

Normally if you retrieve the latest version of GumTree on the develop branch the type is no longer an integer but a string (in fact a Type object which has a String attribute). Also, typeLabel are no longer present since they are the same as the types. You can rely on these as they are stable. Cheers!

**Comment by EikeStein** [comment]
Thanks for the fast response! 

I can't get it to work. To integrate gumtree in my project I used the gradle feature of sourceControl like so:

`sourceControl {
    gitRepository("https://github.com/GumTreeDiff/gumtree.git") {
        producesModule("com.github.gumtreediff:gumtree")
    }
}` 

in my settings.gradle file

And include it via 

`
    implementation('com.github.gumtreediff:gumtree') {
        version {
            branch = 'develop'
        }
    }`

When I now try to build the project I get the attached exceptions [exceptions.txt](https://github.com/GumTreeDiff/gumtree/files/3902964/exceptions.txt). 

I am pretty new to all this java config stuff with gradle and everything, that I am pretty lost tbh. If this is not caused by gumtree related config, could you point me in the right direction, how I could include the current gumtree develop-branch in my gradle project instead?

Thank you very much!  



``

**Comment by jrfaller** [comment]
Hi!

I never tried to have the dependency to git via gradle. You cannot simply clone the project and add your code to it?

Cheers.
