### ISSUE TITLE
Understanding the jsondiff output and mapping jsondiff output to AST

### ISSUE THREAD

**Issue by zylizy** [GumTreeDiff/gumtree#173]
We have feed the gumtree two small programs, sum.js and product.js (as shown below), in json format that generated by esprima, but we had some issues with it. 
a) How do we interpret the value of the keys: "tree", "parent", "label" and "at".
b) How do we get the AST from gumtree, and how do we map the jsondiff output to the generated AST? 

'use strict'
const sum = (a, b) => {
	let answer = a + b;
	return answer;
};
console.log(sum(6, 7));

import 'test.js';
const product = (a, b) => {
	let answer = a * b;
	return answer;
};
console.log(product(6, 7));

the generated jsondiff output:
"./gumtree jsondiff sum.js product.js"

{
  "matches": [
    {
      "src": "String: \"name\" [3721,3727]",
      "dest": "String: \"name\" [3704,3710]"
    },
    {
      "src": "STRING [1026,1029]",
      "dest": "STRING [1009,1012]"
    },
    {
      "src": "OBJECT [3315,4549]",
      "dest": "OBJECT [3298,4536]"
    },
    {
      "src": "String: \"type\" [964,970]",
      "dest": "String: \"type\" [947,953]"
    },
    {
      "src": "String: \"name\" [1654,1660]",
      "dest": "String: \"name\" [1637,1643]"
    },
    {
      "src": "ARRAY [4071,4495]",
      "dest": "ARRAY [4058,4482]"
    },
    {
      "src": "String: \"Identifier\" [3951,3963]",
      "dest": "String: \"Identifier\" [3934,3946]"
    },
    {
      "src": "OBJECT [1119,3012]",
      "dest": "OBJECT [1102,2995]"
    },
    {
      "src": "FIELD [3127,3141]",
      "dest": "FIELD [3110,3124]"
    },
    {
      "src": "FIELD [2208,2406]",
      "dest": "FIELD [2191,2389]"
    },
    {
      "src": "ARRAY [377,3195]",
      "dest": "ARRAY [356,3178]"
    },
    {
      "src": "String: \"type\" [1820,1826]",
      "dest": "String: \"type\" [1803,1809]"
    },
    {
      "src": "STRING [3538,3550]",
      "dest": "STRING [3521,3533]"
    },
    {
      "src": "FIELD [2806,2826]",
      "dest": "FIELD [2789,2809]"
    },
    {
      "src": "FIELD [2271,2291]",
      "dest": "FIELD [2254,2274]"
    },
    {
      "src": "FIELD [3301,4549]",
      "dest": "FIELD [3284,4536]"
    },
    {
      "src": "FIELD [3637,3756]",
      "dest": "FIELD [3620,3739]"
    },
    {
      "src": "FIELD [3576,3593]",
      "dest": "FIELD [3559,3576]"
    },
    {
      "src": "FIELD [3675,3695]",
      "dest": "FIELD [3658,3678]"
    },
    {
      "src": "STRING [507,519]",
      "dest": "STRING [486,498]"
    },
    {
      "src": "FIELD [1654,1670]",
      "dest": "FIELD [1637,1653]"
    },
    {
      "src": "OBJECT [1770,2452]",
      "dest": "OBJECT [1753,2435]"
    },
    {
      "src": "OBJECT [304,3234]",
      "dest": "OBJECT [283,3217]"
    },
    {
      "src": "String: \"params\" [731,739]",
      "dest": "String: \"params\" [714,722]"
    },
    {
      "src": "String: \"declarations\" [361,375]",
      "dest": "String: \"declarations\" [340,354]"
    },
    {
      "src": "String: \"name\" [3993,3999]",
      "dest": "String: \"name\" [3976,3982]"
    },
    {
      "src": "FIELD [2345,2356]",
      "dest": "FIELD [2328,2339]"
    },
    {
      "src": "FALSE [3136,3141]",
      "dest": "FALSE [3119,3124]"
    },
    {
      "src": "String: \"id\" [695,699]",
      "dest": "String: \"id\" [678,682]"
    },
    {
      "src": "FIELD [545,558]",
      "dest": "FIELD [524,541]"
    },
    {
      "src": "String: \"const\" [3217,3224]",
      "dest": "String: \"const\" [3200,3207]"
    },
    {
      "src": "OBJECT [3649,3756]",
      "dest": "OBJECT [3632,3739]"
    },
    {
      "src": "FIELD [2097,2108]",
      "dest": "FIELD [2080,2091]"
    },
    {
      "src": "STRING [326,347]",
      "dest": "STRING [305,326]"
    },
    {
      "src": "String: \"type\" [3853,3859]",
      "dest": "String: \"type\" [3836,3842]"
    },
    {
      "src": "String: \"arguments\" [4058,4069]",
      "dest": "String: \"arguments\" [4045,4056]"
    },
    {
      "src": "OBJECT [118,245]",
      "dest": "OBJECT [142,263]"
    },
    {
      "src": "STRING [180,192]",
      "dest": "STRING [204,213]"
    },
    {
      "src": "STRING [1908,1911]",
      "dest": "STRING [1891,1894]"
    },
    {
      "src": "String: \"type\" [1454,1460]",
      "dest": "String: \"type\" [1437,1443]"
    },
    {
      "src": "String: \"type\" [499,505]",
      "dest": "String: \"type\" [478,484]"
    },
    {
      "src": "FIELD [3375,3774]",
      "dest": "FIELD [3358,3757]"
    },
    {
      "src": "String: \"name\" [2097,2103]",
      "dest": "String: \"name\" [2080,2086]"
    },
    {
      "src": "String: \"CallExpression\" [3861,3877]",
      "dest": "String: \"CallExpression\" [3844,3860]"
    },
    {
      "src": "String: \"callee\" [3375,3383]",
      "dest": "String: \"callee\" [3358,3366]"
    },
    {
      "src": "String: \"ReturnStatement\" [2697,2714]",
      "dest": "String: \"ReturnStatement\" [2680,2697]"
    },
    {
      "src": "STRING [2031,2043]",
      "dest": "STRING [2014,2026]"
    },
    {
      "src": "String: \"+\" [1908,1911]",
      "dest": "String: \"*\" [1891,1894]"
    },
    {
      "src": "String: \"Identifier\" [3538,3550]",
      "dest": "String: \"Identifier\" [3521,3533]"
    },
    {
      "src": "String: \"type\" [136,142]",
      "dest": "String: \"type\" [160,166]"
    },
    {
      "src": "OBJECT [1245,2617]",
      "dest": "OBJECT [1228,2600]"
    },
    {
      "src": "String: \"ArrowFunctionExpression\" [644,669]",
      "dest": "String: \"ArrowFunctionExpression\" [627,652]"
    },
    {
      "src": "STRING [4143,4152]",
      "dest": "STRING [4130,4139]"
    },
    {
      "src": "STRING [2697,2714]",
      "dest": "STRING [2680,2697]"
    },
    {
      "src": "String: \"MemberExpression\" [3415,3433]",
      "dest": "String: \"MemberExpression\" [3398,3416]"
    },
    {
      "src": "OBJECT [1408,2494]",
      "dest": "OBJECT [1391,2477]"
    },
    {
      "src": "STRING [4237,4240]",
      "dest": "STRING [4224,4227]"
    },
    {
      "src": "OBJECT [4300,4469]",
      "dest": "OBJECT [4287,4456]"
    },
    {
      "src": "FIELD [210,231]",
      "dest": "FIELD [231,249]"
    },
    {
      "src": "OBJECT [0,4595]",
      "dest": "OBJECT [0,4582]"
    },
    {
      "src": "String: \"b\" [1026,1029]",
      "dest": "String: \"b\" [1009,1012]"
    },
    {
      "src": "FALSE [3467,3472]",
      "dest": "FALSE [3450,3455]"
    },
    {
      "src": "FIELD [3993,4006]",
      "dest": "FIELD [3976,3993]"
    },
    {
      "src": "String: \"object\" [3494,3502]",
      "dest": "String: \"object\" [3477,3485]"
    },
    {
      "src": "String: \"Identifier\" [972,984]",
      "dest": "String: \"Identifier\" [955,967]"
    },
    {
      "src": "OBJECT [610,3163]",
      "dest": "OBJECT [593,3146]"
    },
    {
      "src": "FIELD [361,3195]",
      "dest": "FIELD [340,3178]"
    },
    {
      "src": "FIELD [4230,4240]",
      "dest": "FIELD [4217,4227]"
    },
    {
      "src": "String: \"name\" [1018,1024]",
      "dest": "String: \"name\" [1001,1007]"
    },
    {
      "src": "FIELD [61,90]",
      "dest": "FIELD [61,88]"
    },
    {
      "src": "String: \"operator\" [1896,1906]",
      "dest": "String: \"operator\" [1879,1889]"
    },
    {
      "src": "String: \"script\" [4585,4593]",
      "dest": "String: \"module\" [4572,4580]"
    },
    {
      "src": "String: \"a\" [867,870]",
      "dest": "String: \"a\" [850,853]"
    },
    {
      "src": "String: \"init\" [1762,1768]",
      "dest": "String: \"init\" [1745,1751]"
    },
    {
      "src": "OBJECT [1534,1716]",
      "dest": "OBJECT [1517,1699]"
    },
    {
      "src": "String: \"VariableDeclarator\" [1462,1482]",
      "dest": "String: \"VariableDeclarator\" [1445,1465]"
    },
    {
      "src": "String: \"console\" [3584,3593]",
      "dest": "String: \"console\" [3567,3576]"
    },
    {
      "src": "STRING [3951,3963]",
      "dest": "STRING [3934,3946]"
    },
    {
      "src": "FALSE [3096,3101]",
      "dest": "FALSE [3079,3084]"
    },
    {
      "src": "String: \"type\" [2271,2277]",
      "dest": "String: \"type\" [2254,2260]"
    },
    {
      "src": "STRING [4001,4006]",
      "dest": "STRING [3984,3993]"
    },
    {
      "src": "String: \"BinaryExpression\" [1828,1846]",
      "dest": "String: \"BinaryExpression\" [1811,1829]"
    },
    {
      "src": "FIELD [4385,4395]",
      "dest": "FIELD [4372,4382]"
    },
    {
      "src": "FIELD [3258,3287]",
      "dest": "FIELD [3241,3270]"
    },
    {
      "src": "NUMBER [4394,4395]",
      "dest": "NUMBER [4381,4382]"
    },
    {
      "src": "FIELD [1283,1312]",
      "dest": "FIELD [1266,1295]"
    },
    {
      "src": "FIELD [3082,3101]",
      "dest": "FIELD [3065,3084]"
    },
    {
      "src": "String: \"body\" [1203,1209]",
      "dest": "String: \"body\" [1186,1192]"
    },
    {
      "src": "String: \"type\" [3407,3413]",
      "dest": "String: \"type\" [3390,3396]"
    },
    {
      "src": "String: \"sourceType\" [4571,4583]",
      "dest": "String: \"sourceType\" [4558,4570]"
    },
    {
      "src": "String: \"b\" [2353,2356]",
      "dest": "String: \"b\" [2336,2339]"
    },
    {
      "src": "String: \"answer\" [2876,2884]",
      "dest": "String: \"answer\" [2859,2867]"
    },
    {
      "src": "String: \"left\" [1961,1967]",
      "dest": "String: \"left\" [1944,1950]"
    },
    {
      "src": "String: \"Program\" [14,23]",
      "dest": "String: \"Program\" [14,23]"
    },
    {
      "src": "String: \"type\" [4135,4141]",
      "dest": "String: \"type\" [4122,4128]"
    },
    {
      "src": "STRING [1828,1846]",
      "dest": "STRING [1811,1829]"
    },
    {
      "src": "String: \"generator\" [3038,3049]",
      "dest": "String: \"generator\" [3021,3032]"
    },
    {
      "src": "String: \"name\" [2345,2351]",
      "dest": "String: \"name\" [2328,2334]"
    },
    {
      "src": "String: \"type\" [1283,1289]",
      "dest": "String: \"type\" [1266,1272]"
    },
    {
      "src": "FIELD [104,245]",
      "dest": "FIELD [132,263]"
    },
    {
      "src": "STRING [2105,2108]",
      "dest": "STRING [2088,2091]"
    },
    {
      "src": "OBJECT [2764,2922]",
      "dest": "OBJECT [2747,2905]"
    },
    {
      "src": "String: \"type\" [2806,2812]",
      "dest": "String: \"type\" [2789,2795]"
    },
    {
      "src": "String: \"sum\" [553,558]",
      "dest": "String: \"product\" [532,541]"
    },
    {
      "src": "String: \"body\" [1111,1117]",
      "dest": "String: \"body\" [1094,1100]"
    },
    {
      "src": "FIELD [2868,2884]",
      "dest": "FIELD [2851,2867]"
    },
    {
      "src": "String: \"argument\" [2752,2762]",
      "dest": "String: \"argument\" [2735,2745]"
    },
    {
      "src": "ARRAY [1211,2986]",
      "dest": "ARRAY [1194,2969]"
    },
    {
      "src": "FIELD [4334,4351]",
      "dest": "FIELD [4321,4338]"
    },
    {
      "src": "String: \"id\" [1528,1532]",
      "dest": "String: \"id\" [1511,1515]"
    },
    {
      "src": "OBJECT [2651,2956]",
      "dest": "OBJECT [2634,2939]"
    },
    {
      "src": "OBJECT [3385,3774]",
      "dest": "OBJECT [3368,3757]"
    },
    {
      "src": "FIELD [29,4565]",
      "dest": "FIELD [29,4552]"
    },
    {
      "src": "String: \"type\" [61,67]",
      "dest": "String: \"type\" [61,67]"
    },
    {
      "src": "STRING [972,984]",
      "dest": "STRING [955,967]"
    },
    {
      "src": "String: \"a\" [2105,2108]",
      "dest": "String: \"a\" [2088,2091]"
    },
    {
      "src": "STRING [3584,3593]",
      "dest": "STRING [3567,3576]"
    },
    {
      "src": "OBJECT [395,3181]",
      "dest": "OBJECT [374,3164]"
    },
    {
      "src": "Number: 7 [4394,4395]",
      "dest": "Number: 7 [4381,4382]"
    },
    {
      "src": "FIELD [3494,3615]",
      "dest": "FIELD [3477,3598]"
    },
    {
      "src": "STRING [3415,3433]",
      "dest": "STRING [3398,3416]"
    },
    {
      "src": "String: \"Identifier\" [2814,2826]",
      "dest": "String: \"Identifier\" [2797,2809]"
    },
    {
      "src": "String: \"type\" [3258,3264]",
      "dest": "String: \"type\" [3241,3247]"
    },
    {
      "src": "STRING [2353,2356]",
      "dest": "STRING [2336,2339]"
    },
    {
      "src": "STRING [4436,4439]",
      "dest": "STRING [4423,4426]"
    },
    {
      "src": "FIELD [2570,2583]",
      "dest": "FIELD [2553,2566]"
    },
    {
      "src": "String: \"raw\" [4429,4434]",
      "dest": "String: \"raw\" [4416,4421]"
    },
    {
      "src": "OBJECT [771,900]",
      "dest": "OBJECT [754,883]"
    },
    {
      "src": "NUMBER [4195,4196]",
      "dest": "NUMBER [4182,4183]"
    },
    {
      "src": "FIELD [859,870]",
      "dest": "FIELD [842,853]"
    },
    {
      "src": "OBJECT [930,1059]",
      "dest": "OBJECT [913,1042]"
    },
    {
      "src": "STRING [69,90]",
      "dest": "STRING [69,88]"
    },
    {
      "src": "String: \"type\" [417,423]",
      "dest": "String: \"type\" [396,402]"
    },
    {
      "src": "OBJECT [2217,2406]",
      "dest": "OBJECT [2200,2389]"
    },
    {
      "src": "String: \"let\" [2578,2583]",
      "dest": "String: \"let\" [2561,2566]"
    },
    {
      "src": "FIELD [3792,4535]",
      "dest": "FIELD [3775,4522]"
    },
    {
      "src": "String: \"ExpressionStatement\" [69,90]",
      "dest": "String: \"ImportDeclaration\" [69,88]"
    },
    {
      "src": "ARRAY [3805,4535]",
      "dest": "ARRAY [3788,4522]"
    },
    {
      "src": "FIELD [1528,1716]",
      "dest": "FIELD [1511,1699]"
    },
    {
      "src": "String: \"type\" [636,642]",
      "dest": "String: \"type\" [619,625]"
    },
    {
      "src": "String: \"type\" [3675,3681]",
      "dest": "String: \"type\" [3658,3664]"
    },
    {
      "src": "STRING [3266,3287]",
      "dest": "STRING [3249,3270]"
    },
    {
      "src": "FIELD [602,3163]",
      "dest": "FIELD [585,3146]"
    },
    {
      "src": "String: \"type\" [1149,1155]",
      "dest": "String: \"type\" [1132,1138]"
    },
    {
      "src": "FIELD [4186,4196]",
      "dest": "FIELD [4173,4183]"
    },
    {
      "src": "String: \"Literal\" [4143,4152]",
      "dest": "String: \"Literal\" [4130,4139]"
    },
    {
      "src": "NULL [701,705]",
      "dest": "NULL [684,688]"
    },
    {
      "src": "FIELD [731,1085]",
      "dest": "FIELD [714,1068]"
    },
    {
      "src": "FIELD [1584,1604]",
      "dest": "FIELD [1567,1587]"
    },
    {
      "src": "FIELD [3943,3963]",
      "dest": "FIELD [3926,3946]"
    },
    {
      "src": "STRING [1592,1604]",
      "dest": "STRING [1575,1587]"
    },
    {
      "src": "String: \"value\" [171,178]",
      "dest": "String: \"value\" [195,202]"
    },
    {
      "src": "String: \"6\" [4237,4240]",
      "dest": "String: \"6\" [4224,4227]"
    },
    {
      "src": "FIELD [3903,4032]",
      "dest": "FIELD [3886,4019]"
    },
    {
      "src": "String: \"kind\" [2570,2576]",
      "dest": "String: \"kind\" [2553,2559]"
    },
    {
      "src": "String: \"callee\" [3903,3911]",
      "dest": "String: \"callee\" [3886,3894]"
    },
    {
      "src": "String: \"type\" [318,324]",
      "dest": "String: \"type\" [297,303]"
    },
    {
      "src": "String: \"arguments\" [3792,3803]",
      "dest": "String: \"arguments\" [3775,3786]"
    },
    {
      "src": "FIELD [964,984]",
      "dest": "FIELD [947,967]"
    },
    {
      "src": "STRING [644,669]",
      "dest": "STRING [627,652]"
    },
    {
      "src": "String: \"value\" [4385,4392]",
      "dest": "String: \"value\" [4372,4379]"
    },
    {
      "src": "String: \"'use strict'\" [217,231]",
      "dest": "String: \"'test.js'\" [238,249]"
    },
    {
      "src": "String: \"name\" [3576,3582]",
      "dest": "String: \"name\" [3559,3565]"
    },
    {
      "src": "String: \"VariableDeclarator\" [425,445]",
      "dest": "String: \"VariableDeclarator\" [404,424]"
    },
    {
      "src": "FIELD [3407,3433]",
      "dest": "FIELD [3390,3416]"
    },
    {
      "src": "STRING [217,231]",
      "dest": "STRING [238,249]"
    },
    {
      "src": "String: \"Literal\" [144,153]",
      "dest": "String: \"Literal\" [168,177]"
    },
    {
      "src": "String: \"Identifier\" [813,825]",
      "dest": "String: \"Identifier\" [796,808]"
    },
    {
      "src": "FIELD [3333,3357]",
      "dest": "FIELD [3316,3340]"
    },
    {
      "src": "String: \"value\" [4186,4193]",
      "dest": "String: \"value\" [4173,4180]"
    },
    {
      "src": "FIELD [1896,1911]",
      "dest": "FIELD [1879,1894]"
    },
    {
      "src": "String: \"kind\" [3209,3215]",
      "dest": "String: \"kind\" [3192,3198]"
    },
    {
      "src": "String: \"property\" [3637,3647]",
      "dest": "String: \"property\" [3620,3630]"
    },
    {
      "src": "STRING [2279,2291]",
      "dest": "STRING [2262,2274]"
    },
    {
      "src": "Number: 6 [4195,4196]",
      "dest": "Number: 6 [4182,4183]"
    },
    {
      "src": "String: \"Identifier\" [3683,3695]",
      "dest": "String: \"Identifier\" [3666,3678]"
    },
    {
      "src": "OBJECT [4101,4270]",
      "dest": "OBJECT [4088,4257]"
    },
    {
      "src": "String: \"type\" [3333,3339]",
      "dest": "String: \"type\" [3316,3322]"
    },
    {
      "src": "FIELD [3209,3224]",
      "dest": "FIELD [3192,3207]"
    },
    {
      "src": "STRING [4342,4351]",
      "dest": "STRING [4329,4338]"
    },
    {
      "src": "FIELD [636,669]",
      "dest": "FIELD [619,652]"
    },
    {
      "src": "FIELD [1762,2452]",
      "dest": "FIELD [1745,2435]"
    },
    {
      "src": "String: \"sum\" [4001,4006]",
      "dest": "String: \"product\" [3984,3993]"
    },
    {
      "src": "FIELD [1018,1029]",
      "dest": "FIELD [1001,1012]"
    },
    {
      "src": "FIELD [2023,2043]",
      "dest": "FIELD [2006,2026]"
    },
    {
      "src": "FIELD [3038,3056]",
      "dest": "FIELD [3021,3039]"
    },
    {
      "src": "STRING [3729,3734]",
      "dest": "STRING [3712,3717]"
    },
    {
      "src": "STRING [14,23]",
      "dest": "STRING [14,23]"
    },
    {
      "src": "FIELD [499,519]",
      "dest": "FIELD [478,498]"
    },
    {
      "src": "String: \"ExpressionStatement\" [3266,3287]",
      "dest": "String: \"ExpressionStatement\" [3249,3270]"
    },
    {
      "src": "OBJECT [3827,4517]",
      "dest": "OBJECT [3810,4504]"
    },
    {
      "src": "FIELD [1454,1482]",
      "dest": "FIELD [1437,1465]"
    },
    {
      "src": "String: \"id\" [467,471]",
      "dest": "String: \"id\" [446,450]"
    },
    {
      "src": "STRING [2876,2884]",
      "dest": "STRING [2859,2867]"
    },
    {
      "src": "String: \"init\" [602,608]",
      "dest": "String: \"init\" [585,591]"
    },
    {
      "src": "STRING [3683,3695]",
      "dest": "STRING [3666,3678]"
    },
    {
      "src": "String: \"expression\" [3301,3313]",
      "dest": "String: \"expression\" [3284,3296]"
    },
    {
      "src": "String: \"type\" [805,811]",
      "dest": "String: \"type\" [788,794]"
    },
    {
      "src": "FIELD [6,23]",
      "dest": "FIELD [6,23]"
    },
    {
      "src": "OBJECT [1969,2158]",
      "dest": "OBJECT [1952,2141]"
    },
    {
      "src": "String: \"name\" [2868,2874]",
      "dest": "String: \"name\" [2851,2857]"
    },
    {
      "src": "String: \"type\" [6,12]",
      "dest": "String: \"type\" [6,12]"
    },
    {
      "src": "String: \"VariableDeclaration\" [326,347]",
      "dest": "String: \"VariableDeclaration\" [305,326]"
    },
    {
      "src": "FIELD [3721,3734]",
      "dest": "FIELD [3704,3717]"
    },
    {
      "src": "FIELD [467,580]",
      "dest": "FIELD [446,563]"
    },
    {
      "src": "FIELD [4058,4495]",
      "dest": "FIELD [4045,4482]"
    },
    {
      "src": "String: \"answer\" [1662,1670]",
      "dest": "String: \"answer\" [1645,1653]"
    },
    {
      "src": "FIELD [171,192]",
      "dest": "FIELD [195,213]"
    },
    {
      "src": "FIELD [1111,3012]",
      "dest": "FIELD [1094,2995]"
    },
    {
      "src": "FIELD [695,705]",
      "dest": "FIELD [678,688]"
    },
    {
      "src": "FIELD [3455,3472]",
      "dest": "FIELD [3438,3455]"
    },
    {
      "src": "String: \"log\" [3729,3734]",
      "dest": "String: \"log\" [3712,3717]"
    },
    {
      "src": "FIELD [2752,2922]",
      "dest": "FIELD [2735,2905]"
    },
    {
      "src": "String: \"type\" [3943,3949]",
      "dest": "String: \"type\" [3926,3932]"
    },
    {
      "src": "OBJECT [3504,3615]",
      "dest": "OBJECT [3487,3598]"
    },
    {
      "src": "OBJECT [3913,4032]",
      "dest": "OBJECT [3896,4019]"
    },
    {
      "src": "String: \"type\" [1584,1590]",
      "dest": "String: \"type\" [1567,1573]"
    },
    {
      "src": "STRING [1291,1312]",
      "dest": "STRING [1274,1295]"
    },
    {
      "src": "STRING [3217,3224]",
      "dest": "STRING [3200,3207]"
    },
    {
      "src": "FIELD [4429,4439]",
      "dest": "FIELD [4416,4426]"
    },
    {
      "src": "String: \"7\" [4436,4439]",
      "dest": "String: \"7\" [4423,4426]"
    },
    {
      "src": "STRING [425,445]",
      "dest": "STRING [404,424]"
    },
    {
      "src": "FIELD [4135,4152]",
      "dest": "FIELD [4122,4139]"
    },
    {
      "src": "FIELD [136,153]",
      "dest": "FIELD [160,177]"
    },
    {
      "src": "STRING [1157,1173]",
      "dest": "STRING [1140,1156]"
    },
    {
      "src": "String: \"computed\" [3455,3465]",
      "dest": "String: \"computed\" [3438,3448]"
    },
    {
      "src": "String: \"type\" [2023,2029]",
      "dest": "String: \"type\" [2006,2012]"
    },
    {
      "src": "String: \"expression\" [3082,3094]",
      "dest": "String: \"expression\" [3065,3077]"
    },
    {
      "src": "STRING [4585,4593]",
      "dest": "STRING [4572,4580]"
    },
    {
      "src": "FIELD [2689,2714]",
      "dest": "FIELD [2672,2697]"
    },
    {
      "src": "ARRAY [37,4565]",
      "dest": "ARRAY [37,4552]"
    },
    {
      "src": "STRING [553,558]",
      "dest": "STRING [532,541]"
    },
    {
      "src": "STRING [1662,1670]",
      "dest": "STRING [1645,1653]"
    },
    {
      "src": "String: \"Identifier\" [1592,1604]",
      "dest": "String: \"Identifier\" [1575,1587]"
    },
    {
      "src": "String: \"right\" [2208,2215]",
      "dest": "String: \"right\" [2191,2198]"
    },
    {
      "src": "FALSE [3051,3056]",
      "dest": "FALSE [3034,3039]"
    },
    {
      "src": "String: \"body\" [29,35]",
      "dest": "String: \"body\" [29,35]"
    },
    {
      "src": "FIELD [805,825]",
      "dest": "FIELD [788,808]"
    },
    {
      "src": "FIELD [1350,2532]",
      "dest": "FIELD [1333,2515]"
    },
    {
      "src": "FIELD [1203,2986]",
      "dest": "FIELD [1186,2969]"
    },
    {
      "src": "String: \"use strict\" [180,192]",
      "dest": "String: \"test.js\" [204,213]"
    },
    {
      "src": "FIELD [1820,1846]",
      "dest": "FIELD [1803,1829]"
    },
    {
      "src": "String: \"Identifier\" [2031,2043]",
      "dest": "String: \"Identifier\" [2014,2026]"
    },
    {
      "src": "FIELD [4571,4593]",
      "dest": "FIELD [4558,4580]"
    },
    {
      "src": "STRING [144,153]",
      "dest": "STRING [168,177]"
    },
    {
      "src": "String: \"CallExpression\" [3341,3357]",
      "dest": "String: \"CallExpression\" [3324,3340]"
    },
    {
      "src": "FIELD [3853,3877]",
      "dest": "FIELD [3836,3860]"
    },
    {
      "src": "String: \"raw\" [210,215]",
      "dest": "String: \"raw\" [231,236]"
    },
    {
      "src": "STRING [867,870]",
      "dest": "STRING [850,853]"
    },
    {
      "src": "STRING [2578,2583]",
      "dest": "STRING [2561,2566]"
    },
    {
      "src": "FIELD [3530,3550]",
      "dest": "FIELD [3513,3533]"
    },
    {
      "src": "STRING [3861,3877]",
      "dest": "STRING [3844,3860]"
    },
    {
      "src": "FIELD [318,347]",
      "dest": "FIELD [297,326]"
    },
    {
      "src": "String: \"BlockStatement\" [1157,1173]",
      "dest": "String: \"BlockStatement\" [1140,1156]"
    },
    {
      "src": "String: \"type\" [4334,4340]",
      "dest": "String: \"type\" [4321,4327]"
    },
    {
      "src": "String: \"expression\" [104,116]",
      "dest": "String: \"source\" [132,140]"
    },
    {
      "src": "String: \"async\" [3127,3134]",
      "dest": "String: \"async\" [3110,3117]"
    },
    {
      "src": "STRING [1462,1482]",
      "dest": "STRING [1445,1465]"
    },
    {
      "src": "ARRAY [741,1085]",
      "dest": "ARRAY [724,1068]"
    },
    {
      "src": "String: \"VariableDeclaration\" [1291,1312]",
      "dest": "String: \"VariableDeclaration\" [1274,1295]"
    },
    {
      "src": "String: \"raw\" [4230,4235]",
      "dest": "String: \"raw\" [4217,4222]"
    },
    {
      "src": "String: \"type\" [2689,2695]",
      "dest": "String: \"type\" [2672,2678]"
    },
    {
      "src": "String: \"name\" [545,551]",
      "dest": "String: \"name\" [524,530]"
    },
    {
      "src": "String: \"Identifier\" [2279,2291]",
      "dest": "String: \"Identifier\" [2262,2274]"
    },
    {
      "src": "String: \"type\" [3530,3536]",
      "dest": "String: \"type\" [3513,3519]"
    },
    {
      "src": "FIELD [417,445]",
      "dest": "FIELD [396,424]"
    },
    {
      "src": "String: \"Identifier\" [507,519]",
      "dest": "String: \"Identifier\" [486,498]"
    },
    {
      "src": "STRING [3341,3357]",
      "dest": "STRING [3324,3340]"
    },
    {
      "src": "FIELD [1149,1173]",
      "dest": "FIELD [1132,1156]"
    },
    {
      "src": "OBJECT [47,294]",
      "dest": "OBJECT [47,273]"
    },
    {
      "src": "STRING [2814,2826]",
      "dest": "STRING [2797,2809]"
    },
    {
      "src": "String: \"declarations\" [1350,1364]",
      "dest": "String: \"declarations\" [1333,1347]"
    },
    {
      "src": "OBJECT [473,580]",
      "dest": "OBJECT [452,563]"
    },
    {
      "src": "STRING [813,825]",
      "dest": "STRING [796,808]"
    },
    {
      "src": "ARRAY [1366,2532]",
      "dest": "ARRAY [1349,2515]"
    },
    {
      "src": "String: \"Literal\" [4342,4351]",
      "dest": "String: \"Literal\" [4329,4338]"
    },
    {
      "src": "FIELD [1961,2158]",
      "dest": "FIELD [1944,2141]"
    },
    {
      "src": "OBJECT [3244,4559]",
      "dest": "OBJECT [3227,4546]"
    },
    {
      "src": "String: \"name\" [859,865]",
      "dest": "String: \"name\" [842,848]"
    }
  ],
  "actions": [
    {
      "action": "update-node",
      "tree": "String: \"script\" [4585,4593]",
      "label": "\"module\""
    },
    {
      "action": "insert-node",
      "tree": "FIELD [102,118]",
      "parent": "OBJECT [47,273]",
      "at": 1
    },
    {
      "action": "insert-node",
      "tree": "String: \"specifiers\" [102,114]",
      "parent": "FIELD [102,118]",
      "at": 0
    },
    {
      "action": "insert-node",
      "tree": "ARRAY [116,118]",
      "parent": "FIELD [102,118]",
      "at": 1
    },
    {
      "action": "update-node",
      "tree": "String: \"expression\" [104,116]",
      "label": "\"source\""
    },
    {
      "action": "update-node",
      "tree": "String: \"ExpressionStatement\" [69,90]",
      "label": "\"ImportDeclaration\""
    },
    {
      "action": "update-node",
      "tree": "String: \"use strict\" [180,192]",
      "label": "\"test.js\""
    },
    {
      "action": "update-node",
      "tree": "String: \"'use strict'\" [217,231]",
      "label": "\"'test.js'\""
    },
    {
      "action": "update-node",
      "tree": "String: \"sum\" [553,558]",
      "label": "\"product\""
    },
    {
      "action": "update-node",
      "tree": "String: \"sum\" [4001,4006]",
      "label": "\"product\""
    },
    {
      "action": "update-node",
      "tree": "String: \"+\" [1908,1911]",
      "label": "\"*\""
    },
    {
      "action": "delete-node",
      "tree": "String: \"directive\" [259,270]"
    },
    {
      "action": "delete-node",
      "tree": "String: \"use strict\" [272,284]"
    },
    {
      "action": "delete-node",
      "tree": "STRING [272,284]"
    },
    {
      "action": "delete-node",
      "tree": "FIELD [259,284]"
    }
  ]
}

**Comment by jrfaller** [comment]
a) How do we interpret the value of the keys: "tree", "parent", "label" and "at".

Tree -> subtree on which the action is  applied
Parent -> New container of the subtree (for move and insert)
Label -> Text on the subtree's root
At -> Position inside the parent where the action is applied (for move and insert)

b) How do we get the AST from gumtree, and how do we map the jsondiff output to the generated AST?

You have the parse command  to get the AST. If you want to see it graphically you also have the webdiff command.
