### ISSUE TITLE
there is no JdtTreeGenerator.class in my jar

### ISSUE THREAD

**Issue by 645709712** [GumTreeDiff/gumtree#175]
Hi,Thank you for your awesome project!
I have a problem...
I use the gumtree by maven,and in my pom,I add
<dependency>
    <groupId>com.github.gumtreediff</groupId>
    <artifactId>core</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>client</artifactId>
            <version>2.1.2</version>
 </dependency>
but I cannot find the JdtTreeGenerator class,result in the problem of "No generator found for file:"...
So I want to know what's the problem here..thank you!

**Comment by Gracccce** [comment]
have you solved this problem

**Comment by Symbolk** [comment]
JdtTreeGenerator is contained in com/github/gumtreediff/gen/jdt, so you should also add dependency for com.github.gumtreediff.gen.jdt.

**Comment by Gracccce** [comment]
> JdtTreeGenerator is contained in com/github/gumtreediff/gen/jdt, so you should also add dependency for com.github.gumtreediff.gen.jdt.

谢谢，我解决这个问题了！但是我在运行的时候又遇到了另一个问题，就是Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/core/runtime/content/IContentTypeManager$IContentTypeChangeListener。我已经导入org.eclipse.core.runtime和org.eclipse.equinox.common这两个包了，但是还是报错，请问你有遇到过类似的问题吗？
