### ISSUE TITLE
Configure CompositeMatchers

### ISSUE THREAD

**Issue by jrfaller** [GumTreeDiff/gumtree#179]
With PR #178 we can now configure several single matchers. However, the complex matchers are mostly CompositeMatchers (such as ClassicGumtree and others). It's currently not possible to configure them, since CompositeMatcher do not implement the Configurable interface. However I think they could be configurable easily by 1) implementing the Configurable interface, 2) redefining configure to just call the configure of all matchers from the composite, forwarding the GumtreeProperties object. @martinezmatias WDYT? 

Side note, I think we should definitively create a ConfigurableMatcher interface extending Matcher and Configurable, because by hacking the code a little, it was annoying to perform the casts, @martinezmatias WDYT?

**Comment by martinezmatias** [comment]
Hi @jrfaller 

Actually, today I implemened that issue :)

**Comment by martinezmatias** [comment]
For the first point, I have already implemented:
```
	@Override
		public void configure(GumTreeProperties properties) {
			for (Matcher matcher : matchers) {
				matcher.configure(properties);
			}
		}
```

**Comment by martinezmatias** [comment]
I will implement the second one and I push both

**Comment by jrfaller** [comment]
> For the first point, I have already implemented:
> 
> ```
> 	@Override
> 		public void configure(GumTreeProperties properties) {
> 			for (Matcher matcher : matchers) {
> 				matcher.configure(properties);
> 			}
> 		}
> ```

You can call configure on something of type Matcher ?

**Comment by martinezmatias** [comment]
Sorry, a bit of context of that snippet:
The `CompositeMatcher` matcher implements Configurable. So, we can override the configure method.  It will call `configure` to the sub-matchers.

**Comment by martinezmatias** [comment]
Hi @jrfaller 
Implemented both points: https://github.com/martinezmatias/gumtree/commit/8890678b6721018995abe9a0359b0dae01555183

Test case is here: 
https://github.com/martinezmatias/gumtree/commit/8890678b6721018995abe9a0359b0dae01555183#diff-cee8fae00db9a17a1daedf34833aa7fcR214

WDYT?

**Comment by jrfaller** [comment]
This is OK for me! Thanks a lot! I will merge a PR :D

I am starting to wonder if Simon was right for the inheritance between Matcher and Configurable :) We will see if it's to annoying to always cast we will do it in the future.
