### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Marvinmw** [GumTreeDiff/gumtree#182]
Hi,
I use the jars from dist module in my small project. But After I use shadowjar to build an executable jar file with dependence, and execute it, java -jar.
It gives the error,
java.lang.UnsupportedOperationException: No generator found for file: data/pre/APLExplanation.java
        at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:55).

I use java 11.0.7 and IntelliJ. My small program can run in IntelliJ but cannot run using java -jar.
Here is my project build.gradle,

plugins{
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '6.0.0'
}
//group 'org.example'
//version '1.0-SNAPSHOT'
mainClassName = "lu.ScriptDiff"
repositories {
    mavenCentral()
}
}
shadowJar{
    manifest{
        attributes "Main-Class": mainClassName
    }
}
dependencies {
    compile fileTree(includes: ['*.jar'], dir: 'libs/gumtree-3.0.0-beta1-SNAPSHOT/lib')
    // https://mvnrepository.com/artifact/org.json/json
    compile group: 'org.json', name: 'json', version: '20090211'
    // https://mvnrepository.com/artifact/com.github.spullara.cli-parser/cli-parser
    compile group: 'com.github.spullara.cli-parser', name: 'cli-parser', version: '1.1.5'
    testCompile group: 'junit', name: 'junit', version: '4.12'

}

**Comment by Marvinmw** [comment]
If I do not use shadowjar, and include dependence by myself. I get the error, 

Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes

plugins{
    id 'java'
    id 'application'
   // id 'com.github.johnrengelman.shadow' version '6.0.0'
}

//version '1.0-SNAPSHOT'
sourceCompatibility = 1.9
mainClassName = "lu.ScriptDiff"
repositories {
    mavenCentral()
    jcenter()
}

dependencies {

    compile fileTree(includes: ['*.jar'], dir: 'libs/gumtree-3.0.0-beta1-SNAPSHOT/lib')
    // https://mvnrepository.com/artifact/org.json/json
    compile group: 'org.json', name: 'json', version: '20090211'
    // https://mvnrepository.com/artifact/com.github.spullara.cli-parser/cli-parser
    compile group: 'com.github.spullara.cli-parser', name: 'cli-parser', version: '1.1.5'
    testCompile group: 'junit', name: 'junit', version: '4.12'

}

jar {
    from {
        configurations.compile.collect {
            it.isDirectory() ? it : zipTree(it)
        }
        configurations.runtime.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
    manifest {
        attributes 'Implementation-Title': 'diff',
                'Implementation-Version': '0.1.0',
                'Built-Date': new Date(),
                'Main-Class':mainClassName
    }
}

**Comment by Marvinmw** [comment]
If I exlcude META_INFO above, I will get the same error with shadowjar
java.lang.UnsupportedOperationException: No generator found for file: data/pre/APLExplanation.java
	at com.github.gumtreediff.gen.TreeGenerators.getTree(TreeGenerators.java:55)
	at lu.ScriptDiff.computeASTDiff(ScriptDiff.java:41)
	at lu.ScriptDiff.main(ScriptDiff.java:79)

**Comment by jrfaller** [comment]
Hi!

I suspect this is because of classindex (https://github.com/atteo/classindex) we use to index the Tree Generators files, the clients, the matchers, ...

I think that it has to put an index file somewhere and maybe it has been lost when you repackage everything with shadow jar?

**Comment by Marvinmw** [comment]
Hi, I solve the problem . I declare TextGenerator by myself instead of getinstance.

**Comment by jrfaller** [comment]
Yes it will work because in this case you don't use classindex

**Comment by Marvinmw** [comment]
> Yes it will work because in this case you don't use classindex

there is the other bug and I will open a new issue.
