### ISSUE TITLE
Compare two .cpp files and get the changes on the method-level

### ISSUE THREAD

**Issue by digeo** [GumTreeDiff/gumtree#185]
First of all, congratulations for this great project! I am trying to use it on my research and I have the following problem:

I would like to compare two `cpp` files (i.e. `apiL.cpp` and `apiR.cpp`) where `apiR.cpp` is a newer revision of `apiL.cpp`. On `apiR.cpp` some methods/functions added, some methods/functions modified and some methods/functions deleted.
So far I have written the following code:

```
Run.initGenerators();

String srcFile = "/home/diff/apiL.cpp";
String dstFile = "/home/diff/apiR.cpp";

ITree src = new SrcmlCppTreeGenerator().generateFromFile(srcFile).getRoot();
ITree dst = new SrcmlCppTreeGenerator().generateFromFile(dstFile).getRoot();

Matcher m = Matchers.getInstance().getMatcher(src, dst);
		
ActionGenerator g = new ActionGenerator(src, dst, m.getMappings());
g.generate();
List<Action> actions = g.getActions();
```
My question is the following: what should I do in order to get diffs on the method-level between those two files?
Thank you in advance!

**Comment by jrfaller** [comment]
Hi and thanks for trying out GumTree!

Normally the list of actions is the diff, it includes all changes. I am not sure what you mean by "diff on the method-level"? Can you provide an example of what you want?

Cheers.

**Comment by digeo** [comment]
@jrfaller thank you very much for you fast response.
What I would like to achieve, is the following.
Let's say that the file `apiL.cpp` has the following functions:
```
void foo(){
...
}
void bar(){
...
}
void zxy(){
...
}
```

On the newer revision `apiR.cpp` the functions look like this:
```
void bar(){
...
print("function bar updated/modified")
}
void zxy(){
...
}
void newFunction(){
...
}
```

Where:
1. the function void `bar(){...}` **deleted**
2. the function `void bar(){... print("function bar updated/modified")}` **updated**, one print statement added
3. the function `void zxy(){...}` remained **unchanged**
4. a new function **inserted** `void newFunction(){...}`

Is there a way to get that kind of info and ideally the span of the methods (start at Line X ends at Line Y)?
Thank you in advance!

**Comment by jrfaller** [comment]
Hi!

Ok I understand your motivation.

Note that gumtree will produce "fine-grained" diff therefore for the `bar` function you will not have readily the information that it has been updated, you will rather have directly the inserted statement and will have to resort to some post processing to know that it belongs to the bar method. For the deleted / inserted method, if everything goes as expected however you will have the inserted / deleted subtree corresponding to the function declaration.

To have a quick clue of what you can get, I recommend you to update to the latest develop commit of GumTree and try the `gumtree textdiff` command on your pair of files.

Also I don't know if you are working on this for a PhD topic, but if you want you can contact me by mail to explain me your project it can interest us as we are also working on the API evolution topic in my research team!

Cheers.
