### ISSUE TITLE
Question about heuristic

### ISSUE THREAD

**Issue by martinezmatias** [GumTreeDiff/gumtree#186]
Hi @jrfaller 

A question about heuristic SimpleMatcher:
The threshold SIM_THRESHOLD (see [here](https://github.com/GumTreeDiff/gumtree/blob/develop/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/SimpleBottomUpMatcher.java#L53)) is never used. Actually, it was neither used before the refactoring we have done (see previous version [here](https://github.com/GumTreeDiff/gumtree/blob/69e33cea51f9c30367e0efb550c76cff2d63ca27/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/SimpleBottomUpMatcher.java#L34))

Is something missing there? or is that threshold not necessary and we should remove it?

Thanks!
Matias

**Comment by jrfaller** [comment]
Hi @martinezmatias! I believe you are right. It was used  when I first designed it, but I removed it to use an adaptative threshold (computed line 71).

I think we can remove it!

Cheers.

**Comment by martinezmatias** [comment]
The threshold not used was removed by commit c3aa079440c998924226a6de2fed87f601b70caf
