### ISSUE TITLE
any explanation for ZsMatcher?

### ISSUE THREAD

**Issue by wangxi761** [GumTreeDiff/gumtree#188]
sorry for the inconvenience, no relevant literature or description was found, can you briefly explain its principle?

**Comment by jrfaller** [comment]
I believe you will find everything you need in:

K. Zhang et D. Shasha, « Simple fast algorithms for the editing distance between trees and related problems », SIAM Journal of Computing, vol. 18, no 4,‎ 1989, p. 1245–1262.

Cheers!
