### ISSUE TITLE
Build error: Cannot find coveralls

### ISSUE THREAD

**Issue by csiefer2** [GumTreeDiff/gumtree#189]
I'm getting this error from gradle when I did ``gradle build -x test''.  I am using a proxy (and tried to set options to tell it the proxy settings, but have no idea if that worked), if that matters?

Ideas?

---------------------

* What went wrong:
Plugin [id: 'com.github.kt3k.coveralls', version: '2.6.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.kt3k.coveralls:com.github.kt3k.coveralls.gradle.plugin:2.6.3')
  Searched in the following repositories:
    Gradle Central Plugin Repository

**Comment by jrfaller** [comment]
Hi!

It's kind of weird, dependencies are managed by Gradle/Maven, and we have no problem like that in the CI. It probably come from your network settings.

Cheers!

**Comment by jrfaller** [comment]
Maybe try to use our gradle wrapper gradlew?

**Comment by jrfaller** [comment]
Coverall dependency has been removed from GumTree.
