### ISSUE TITLE
property gumtree.match.bu.size is not taken into account

### ISSUE THREAD

**Issue by monperrus** [GumTreeDiff/gumtree#19]
settnig  System.getProperty("gumtree.match.bu.size", "0") or  System.getProperty("gumtree.match.bu.size", "1000"); does not change anything, in particular the number of updates is not impacted

**Comment by jrfaller** [comment]
Normally, we have released a commit that fix this problem, can you test again?

**Comment by monperrus** [comment]
on maven central?

**Comment by jrfaller** [comment]
No, on the develop branch of this repository.

**Comment by monperrus** [comment]
thanks. Is there a Snapshot version of this branch deployed somewhere?

**Comment by jrfaller** [comment]
You can build your own by performing a `gradle build` (see wiki).

**Comment by monperrus** [comment]
`gradlew build` succeeds. How to install the snapshot version in `.m2` now? Thanks.

**Comment by jrfaller** [comment]
normally you have a tar.gz with everything you need in the build directory of `dist`

**Comment by monperrus** [comment]
I found the solution.

added
```
apply plugin: "maven"
group = "gumtree"
version = "3.0-SNAPSHOT"
```
in `core/build.gradle` and run `gradle install`.
Now I have the 3.0-SNAPSHOT in .m2

**Comment by monperrus** [comment]
OK, it works. Thanks a lot for the bug fix. When is it planned to be released on Maven Central?

**Comment by jrfaller** [comment]
I think we will make a release before the end of this year.
