### ISSUE TITLE
position and length of node not loaded from srcML1.0 xml 

### ISSUE THREAD

**Issue by baminmru** [GumTreeDiff/gumtree#191]
I think that gen.srcml parser contain error when processed position of node.
I use srcML V1.0.0
node output look like this:

`<name pos:start="4:3" pos:end="4:3">i</name>`

But gen.srcml can't to find position marker and always sets position and length of node to -1

**Comment by baminmru** [comment]
I'm try to fix problem for my own task.
Fix to AbstractSrcmlTreeGenerator
` private static final QName POSSTART = new  QName("http://www.srcML.org/srcML/position", "start", "pos");

    private static final QName POSEND = new  QName("http://www.srcML.org/srcML/position", "end", "pos");

.....

 private void setPos(ITree t, StartElement e) {
        if (e.getAttributeByName(POSSTART) != null) {
            String posStr =e.getAttributeByName(POSSTART).getValue();
            String[] chanks = posStr.split(":");
            int line = Integer.parseInt(chanks[0]);
            int column = Integer.parseInt(chanks[1]);
            t.setPos(lr.positionFor(line, column));
            setLength(t, e);
        }
    }

    private void setLength(ITree t, StartElement e) {
        if (t.getPos() == -1)
            return;
        if ( e.getAttributeByName(POSEND) != null) {
            String posStr =e.getAttributeByName(POSEND).getValue();
            String[] chanks = posStr.split(":");
            int line = Integer.parseInt(chanks[0]);
            int column = Integer.parseInt(chanks[1]);
            t.setLength(lr.positionFor(line, column) - t.getPos() + 1);
        }
    }

`

**Comment by jrfaller** [comment]
Hi and thanks for your interest for GumTree.

You mean that the way srcML parsers provide position has changed in this new version? Is it for every languages?

Could you provide a pull request with a passing test?

Cheers!

**Comment by baminmru** [comment]
I've tested for C and C++, and output has sape position tags.
[out_c.txt](https://github.com/GumTreeDiff/gumtree/files/5173717/out_c.txt)
[out_cpp.txt](https://github.com/GumTreeDiff/gumtree/files/5173718/out_cpp.txt)

**Comment by baminmru** [comment]
I'm sorry but I use separate project, and creating pull request  is little bit difficult for me.
full code for class is here:
https://github.com/jzuken/bugs-classification/blob/master/common/src/main/java/org/ml_methods_group/common/ast/srcmlGenerator.java

**Comment by jrfaller** [comment]
Ok thanks a lot for the pointer. Normally since has been close by the last commit.

Cheers!
