### ISSUE TITLE
Setting up GumTreeAPI

### ISSUE THREAD

**Issue by shreyjasuja** [GumTreeDiff/gumtree#192]
how to set up the environment for the API is not clear from Wiki, facing issue to integrate those snippets

**Comment by jrfaller** [comment]
Hi!

Can you be a little more precise on what the problem is?

**Comment by shreyjasuja** [comment]
hi, thanks for replying

 I am unable to execute this snippet in eclipse as mentioned in Wiki,

Run.initGenerators();
String srcFile = "file_v0.java";
String dstFile = "file_v1.java";
ITree src = Generators.getInstance().getTree(srcFile).getRoot();
ITree dst = Generators.getInstance().getTree(dstFile).getRoot();
Matcher defaultMatcher = Matchers.getInstance().getMatcher();
MappingStore mappings = defaultMatcher.match(src, dst);
EditScriptGenerator editScriptGenerator = new SimplifiedChawatheScriptGenerator();
EditScript actions = editScriptGenerator.computeActions(mappings);

**Comment by jrfaller** [comment]
OK and what is the error?

**Comment by shreyjasuja** [comment]
I tried to resolve dependency by giving the classpath of dist folder in Java Build Path > libraries > classpath but couldn't resolve the error

**Comment by jrfaller** [comment]
Are you using Gradle?

**Comment by shreyjasuja** [comment]
I am using it in Ecplise
The following are the errors:

`Run cannot be resolved
	ITree cannot be resolved to a type
	Generators cannot be resolved
	ITree cannot be resolved to a type
	Generators cannot be resolved
	Matcher cannot be resolved to a type
	Matchers cannot be resolved
	MappingStore cannot be resolved to a type
	EditScriptGenerator cannot be resolved to a type
	SimplifiedChawatheScriptGenerator cannot be resolved to a type
	EditScript cannot be resolved to a type`

**Comment by jrfaller** [comment]
You have to compile everything using Gradle. It might work with IntelliJ.

**Comment by shreyjasuja** [comment]
So this code snippet provided:

Run.initGenerators();
String srcFile = "file_v0.java";
String dstFile = "file_v1.java";
ITree src = Generators.getInstance().getTree(srcFile).getRoot();
ITree dst = Generators.getInstance().getTree(dstFile).getRoot();
Matcher defaultMatcher = Matchers.getInstance().getMatcher();
MappingStore mappings = defaultMatcher.match(src, dst);
EditScriptGenerator editScriptGenerator = new SimplifiedChawatheScriptGenerator();
EditScript actions = editScriptGenerator.computeActions(mappings); 

has to be executed using gradle?

Also, to mention I had installed gumtree using gradle itself and webdiff is working fine. But I wanted to use it through java code and then experiment with it.

**Comment by jrfaller** [comment]
No you can execute with what you want given that the classpath is correct. Classpath is most easily set up using IntelliJ / Gradle.

**Comment by shreyjasuja** [comment]
Okay, will try on IntelliJ once, if I face any problem will get back to you. Thanks for such an amazing open-source tool and also I do appreciate your efforts in actively maintaining this repo.

**Comment by jrfaller** [comment]
Thanks! I hope you'll get it working.
