### ISSUE TITLE
What is the command to parse a java file and dump into a json format?

### ISSUE THREAD

**Issue by Hareem-E-Sahar** [GumTreeDiff/gumtree#194]
I am running the following parse command in the docker but the resulting tree is not in the json format. 

docker run -v ~/testdir:/diff/left -v ~/testdir2:/diff/right -p 4567:4567 gumtreediff/gumtree parse left/filename.java

How can I change this command to get the output in json format?

**Comment by jrfaller** [comment]
By default, docker runs the `webdiff` command. However w.r.t. to your objective, you have to run the `textdiff` command. You can use docker in interactive mode or rebuild the container changing the entrypoint.

Cheers!

**Comment by Hareem-E-Sahar** [comment]
Thank you for your answer. Do you mean the textdiff would give output as JSON?
Actually, I rebuilt the docker and ran the parse command successfully except that the output of the command wasn't in JSON format which is what I need.
