### ISSUE TITLE
How do the numbers in the result from jsondiff relate to information dumped from the parse command

### ISSUE THREAD

**Issue by NunoCastanho** [GumTreeDiff/gumtree#196]
Hello. I've been experimenting with GumTree and a few questions have surfaced all around the same topic (I believe). 

1) How do the numbers (identifiers) of the subtrees that appear in the result from the `jsondiff` command relate to the information that the `parse` command gives? I know the `pos` field that appears in the result from parse is not the same thing.

This question is pertinent to me because if I see for example in the matches `{"src":26, "dest":30}` I'd like to know which subtrees those numbers identify by looking into their respective JSON dumps.

2) What's the algorithm to number the subtrees? I know the numbers identify the subtrees but I can't find the pattern for numbering them has the root is not the 0 for example, nor does it follow a depth-first or breadth-first approach. I know I can see the numbers of each subtree with the `dot` view for example.

**Comment by jrfaller** [comment]
Hi Nuno!

I believe the ids result from a post-order numbering, I don't think there is this information in the JSON unfortunately 😢

**Comment by NunoCastanho** [comment]
Thank you, that helps!
