### ISSUE TITLE
Not recognizing EditScriptGenerator and EditScript type

### ISSUE THREAD

**Issue by NunoCastanho** [GumTreeDiff/gumtree#197]
Hello.

I'm trying to use GumTree directly in the Java code. I've imported through Maven the `core`, `client` and `client.diff` modules. However, when running the code bellow neither `EditScriptGenerator` nor `EditScript` are recognized.

```
Run.initGenerators();
String srcFile = "Test.java";
String dstFile = "Test2.java";
ITree src = Generators.getInstance().getTree(srcFile).getRoot();
ITree dst = Generators.getInstance().getTree(dstFile).getRoot();
Matcher defaultMatcher = Matchers.getInstance().getMatcher(src, dst);
MappingStore mappings = defaultMatcher.getMappings();
EditScriptGenerator editScriptGenerator = new SimplifiedChawatheScriptGenerator();
EditScript actions = editScriptGenerator.computeActions(mappings);
```

The current imports I have on my `pom.xml` are:
```
<dependency>
    <groupId>com.github.gumtreediff</groupId>
    <artifactId>core</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
    <groupId>com.github.gumtreediff</groupId>
    <artifactId>client</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
    <groupId>com.github.gumtreediff</groupId>
    <artifactId>client.diff</artifactId>
    <version>2.1.2</version>
</dependency>
<dependency>
    <groupId>com.github.gumtreediff</groupId>
    <artifactId>gen.jdt</artifactId>
    <version>2.1.2</version>
</dependency>
```

Am I missing any? Because I've checked and both `EditScriptGenerator` and `EditScript` are in `core`

Thank you,
Nuno

**Comment by jrfaller** [comment]
Hi!

I believe this is due to the fact that this code only work for GumTree >= v3.0.0.

We have Maven SNAPSHOT packages for this version in the github registry, you can try them out (but it's kind of a pain to configure unfortunately).

Cheers.

**Comment by NunoCastanho** [comment]
Hi!

How would I get the edit script and edit actions with the 2.1.2 version then?

Thanks.

**Comment by jrfaller** [comment]
one of those : https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API/_history 😄
