### ISSUE TITLE
Configure the SNAPSHOT packages

### ISSUE THREAD

**Issue by NunoCastanho** [GumTreeDiff/gumtree#198]
Hey @jrfaller 

In #197 you've said `We have Maven SNAPSHOT packages for this version in the github registry, you can try them out (but it's kind of a pain to configure unfortunately).`

I'm trying to configure the `core` snapshot and I've added the `jar`, `module` and `pom` files available [here](https://github.com/GumTreeDiff/gumtree/packages/380621) and their respective `sha` keys to the gumtree folder in `.m2`. 

Maven still complains that it's missing the artifact. What am I missing? Can you help me?

Thanks, 
Nuno

**Comment by jrfaller** [comment]
Hi I think you have to look into GitHub doc on how to make GHP available to maven
