### ISSUE TITLE
Errors in Run.initGenerators()

### ISSUE THREAD

**Issue by Gracccce** [GumTreeDiff/gumtree#203]
Hi,Thank you for your awesome project!
I have a problem...
I use the gumtree by maven,and in my pom,I add

com.github.gumtreediff
core
2.1.2

com.github.gumtreediff
client
2.1.2

but this code can't work : Run.initGenerators();
Error:
Exception in thread "main" java.lang.NoClassDefFoundError: org/atteo/classindex/ClassIndex
	at com.github.gumtreediff.client.Run.initGenerators(Run.java:53)

**Comment by jrfaller** [comment]
Maybe try to update to the 3.0.0beta version we have on GitHub packages?

Cheers.

**Comment by Symbolk** [comment]
ClassIndex is included in the classindex-3.x.jar, so you have to also depend on it.

However, if you want to avoid more such problems when using it for Java, here is a list of the required libs to depend on:

![image](https://user-images.githubusercontent.com/14107297/102152104-4acbc800-3eaf-11eb-9f9c-27b4c824bbc2.png)

**Comment by jrfaller** [comment]
@Gracccce you managed to get it working?
