### ISSUE TITLE
Difference between delete-node and delete-tree (also insert-node and insert-tree)

### ISSUE THREAD

**Issue by RainRain1218** [GumTreeDiff/gumtree#207]
Thank you for the excellent GumTree! 
I am using gumtree from Docker, and I output the diff result in json format. I notice that there are two types of delete: "delete-node" and "delete-tree", in action list. And I want to know what is the difference between them. There is an example:

    {
      "action": "delete-tree",
      "tree": "Binary [55027,55050]"
    },
    {
      "action": "delete-tree",
      "tree": "ExprStatement [55354,55381]"
    },
    {
      "action": "delete-node",
      "tree": "Unary [55477,55498]"
    },
    {
      "action": "delete-node",
      "tree": "Binary [55447,55498]"
    },

My problems are:
a) What is the difference between delete-tree and delete-node?
b) What does the numbers in [] in "tree" mean? If there is _[num1, num2]_ in the "tree" after "delete-" action, does it mean all characters from _num1_ to _num2_ are deleted?

Thank you very much!

**Comment by usr-sse2** [comment]
delete-node deletes one leaf syntax node (it must have no children), and delete-tree deletes the node and all its descending nodes. If simplification is not used, for example, removing
```cs
if (f)
   a = 5;
```
would be reported like
```
delete-node name(a)
delete-node operator(=)
delete-node literal(5)
delete-node statement(name(a), operator(=), literal(5))
delete-node then_block(statement(name(a), operator(=), literal(5))
delete-node name(f)
delete-node condition(name(f))
delete-node if(condition(name(f)), then_block(statement(name(a), operator(=), literal(5)))
```
but if simplification is used, it would be one operation
```
delete-tree if(condition(name(f)), then_block(statement(name(a), operator(=), literal(5)))
```

**Comment by jrfaller** [comment]
Exactly!

And the numbers inside [] corresponds to the the affected character range inside the left file (because it's a deletion).

Cheers.
