### ISSUE TITLE
Difference between methods in CompositeMatchers.java 

### ISSUE THREAD

**Issue by algomaster99** [GumTreeDiff/gumtree#209]
I had a question regarding [the matchers](https://github.com/GumTreeDiff/gumtree/blob/develop/core/src/main/java/com/github/gumtreediff/matchers/CompositeMatchers.java#L84) implemented in the code. I wanted to understand how each of them is different from others. I couldn't find it in the docs and that's why I have opened this ticket as a question.

**Comment by jrfaller** [comment]
Hi!

It's true that many matchers have no documentation :(. I think it would be nice to put some JavaDoc at the class level to give an overview as it is done in https://github.com/GumTreeDiff/gumtree/blob/develop/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/GreedyBottomUpMatcher.java

However this will be a long term operation ;)

Cheers.

**Comment by algomaster99** [comment]
@jrfaller Yeah, sure. I am ready to document the matchers but I need to understand what each one of them do. Let's start with [SimpleBottomUpMatcher](https://github.com/GumTreeDiff/gumtree/blob/develop/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/SimpleBottomUpMatcher.java). If you can refer me some academic journals to read from, please do otherwise reading each code snippet might be too time consuming. :sweat_smile:

**Comment by jrfaller** [comment]
Haha sorry there is no publication of this algorithm yet...

I will do that myself since I know the code 😉

**Comment by algomaster99** [comment]
@jrfaller oh, okay. Thanks!

**Comment by jrfaller** [comment]
I'm closing this as we are discussing documentation in #215 now.
