### ISSUE TITLE
supported language question

### ISSUE THREAD

**Issue by jaygray0919** [GumTreeDiff/gumtree#210]
I should experiment before asking, but allow me to jump-the-gun:
  can we use GumTreeDiff to compare large JSON-LD graphs?

/jay gray

**Comment by jrfaller** [comment]
Hi!

We do not have a dedicated support for JSON, but maybe you can try it out my putting the `.js` extension to will lead to the use of the Rhino parser.

Also, maybe of interest you can look into our JSON specific differ : https://github.com/caohanyang/json_diff_rfc6902

Cheers.

**Comment by monperrus** [comment]
FYI, https://github.com/gnieh/diffson
