### ISSUE TITLE
GumTree API examples broken

### ISSUE THREAD

**Issue by s0nata** [GumTreeDiff/gumtree#214]
Hi,

I'm trying to use GumTreeDiff from Java source code to parse Java, and I tried to start with replicating examples from [GumTree-API](https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API) page. However, the APIs given in the examples seem to be out of date. I was only able to replicate the first example, and it still required a lot of API searching and adapting.

I am using GTD release 2.1.2 in a maven project, here are the dependencies:
```xml
   <!-- https://mvnrepository.com/artifact/com.github.gumtreediff/client -->
    <dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>client</artifactId>
      <version>2.1.2</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.github.gumtreediff/core -->
    <dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>core</artifactId>
      <version>2.1.2</version>
    </dependency>
    <!-- https://mvnrepository.com/artifact/com.github.gumtreediff/gen.javaparser -->
    <dependency>
      <groupId>com.github.gumtreediff</groupId>
      <artifactId>gen.javaparser</artifactId>
      <version>2.1.2</version>
    </dependency>
```
here is how I had to change the first example ("Computing the mappings between two trees"):

```java
package entry;

import com.github.gumtreediff.client.Run;
import com.github.gumtreediff.gen.Generators;
import com.github.gumtreediff.matchers.Mapping;
import com.github.gumtreediff.matchers.Matcher;
import com.github.gumtreediff.matchers.Matchers;
import com.github.gumtreediff.tree.ITree;

import java.io.IOException;
import java.util.Set;

public class ChangeAnalyzer {

    public static void gettingStartedExamples(){

        Run.initGenerators();

        String srcFile = "resources/samples/change/0_AdaptiveIsomorphismInspectorFactory.java";
        String dstFile = "resources/samples/change/1_AdaptiveIsomorphismInspectorFactory.java";
        ITree src;
        ITree dst;

        try {
            src = Generators.getInstance().getTree(srcFile).getRoot();
            dst = Generators.getInstance().getTree(dstFile).getRoot();
            Matcher defaultMatcher = Matchers.getInstance().getMatcher(src, dst);
            defaultMatcher.match();

            Set<Mapping> mappingSet = defaultMatcher.getMappingsAsSet();
            for (Mapping mapping : mappingSet) {
                System.out.println(mapping.toString());
            }
        } catch (IOException treeGenerationException) {
            System.out.println(treeGenerationException.getMessage());
            treeGenerationException.printStackTrace();
        }
    }
}
```
and here is the output produced:
```
...
(-2081085230@@,-2081085230@@)
(1536782779@@Graph,1536782779@@Graph)
(278051923@@,278051923@@)
(-1717083471@@,-1717083471@@)
(-1164581634@@,-1164581634@@)
(1536782779@@graph2,1536782779@@g)
(1536782779@@EquivalenceComparator,1536782779@@EquivalenceComparator)
(1680773993@@,1680773993@@)
(1536782779@@vertexChecker,1536782779@@vertexChecker)
...
This method should currently not be used (please use toShortString())
This method should currently not be used (please use toShortString())
....
```

(BTW, `toShortString()` is not really available for any of the classes above)

Which version of GTD API are the examples using? Could you please specify that in the wiki page  [GumTree-API](https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API)? Because I could not really find any class called 'EditScriptGenerator', `SimplifiedChawatheScriptGenerator`, or `EditScript`, used in the second example ("Computing the edit script between two trees") in any of the source files of the GTD release 2.1.2.

**Comment by jrfaller** [comment]
Hi @s0nata and thanks a lot for your feedback.

As you have probably understood, the code on the wiki is for the latest commit, which is clearly unhelpful in case you download the release :(

However, it is very easy to compile it on your machine if you want to try. I should clarify his in the wiki document.

Cheers.

**Comment by jrfaller** [comment]
This is clarified in the document.

**Comment by s0nata** [comment]
hi @jrfaller , thanks for that clarification, though it does not really help people like me who work with releases and not the latest builds. 

Looking at the revisions of that wiki page, I'll make an assumption that either the version before or the version after the release should contain compatible  APIs.

**Comment by jrfaller** [comment]
Yes I know :(

Indeed, I guess you'll find the working version in the history of the Wiki

I will try to push a beta release really soon since there are a lot of improvements.

Cheers.

**Comment by s0nata** [comment]
just tried replicating the exampls from the 07.03.2019 - and it works! so happy right now :-)

Overall, it took me about a day to figure out that the  version of code on GitHub and the version in the release differ _that much_ in the APIs, so I believe (a) your earlier clarification does shorten some of that time (b) maybe it is still worth having a pointer to the working examples for the current stable release while you are working on the beta? E.g. something like "for API examples of the GumTreeDiff release 2.1.2 see the respective [version of this page](https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API/f4cdc598f4f1b768066d61a49ca3ae1d8818ab2c)"?

**Comment by s0nata** [comment]
also, IMO what was better in the version for the 2.1.2 - there were inline comments explaining a bit what is happening, like `// return the mapping store` or `// displays the tree in LISP syntax`

**Comment by jrfaller** [comment]
I have released a 3.0.0-beta1 :)

**Comment by jrfaller** [comment]
OK I added inline comments in all examples as you suggest!

It would be indeed a good idea to have documentation for the latest stable release, but I'm afraid I won't have enough time to do it 😭 Anyway it's probably not a good idea to use anything other than 3.0.0-beta1 now. Granted it looks scary, but in fact it's pretty stable. It's still beta because we might still break some small stuff before the final!

**Comment by s0nata** [comment]
I understand I might not be the target audience, and most of the people use the binaries, but for me the 2.1.2 is still the latest release on mavencentral: https://mvnrepository.com/artifact/com.github.gumtreediff

however, I see the packages separately at https://github.com/orgs/GumTreeDiff/packages . Let me try that, I'll get back to you if it does not work 8-)

**Comment by jrfaller** [comment]
Yes you're right, it's not very clear, but we have migrated to Github package to deploy our maven packages, since it is far easier to use :)

I have put a word about this in the wiki, Getting Started.

**Comment by s0nata** [comment]
it works, all good!

One, hopefully final, remark about the examples: to retrieve and apply the default parser for a file I can only use `TreeGenerators` and not `Generators`, how the mappings and edit script computation examples show now in lines like `src = TreeGenerators.getInstance().getTree(srcFile).getRoot();` (at 6dec8d7)

**Comment by jrfaller** [comment]
You're right, `Generators` has been renamed to `TreeGenerators`! Fixed the wiki.
