### ISSUE TITLE
axmldiff java.io.IOException No such file or director for python files

### ISSUE THREAD

**Issue by dayaad** [GumTreeDiff/gumtree#216]
Hello, gumtree throws an exception when I run it on two python files (Exception screen-shot attached) 
* The path of the files is correct 
* running on MacOS Catalina 
* Python files (before.py & after.py) have a simple python code:

**before.py:** 
class Gum:
	def my_function():
  		print("Hello from a function")

**after.py:**
class Gum:
	def my_function():
  		print("Hello from a function2")
 
 
<img width="945" alt="Screen Shot 2021-02-12 at 5 54 20 AM" src="https://user-images.githubusercontent.com/74029215/107776705-c226a800-6cf6-11eb-92d2-2c8ed7aa4fa6.png">

**Comment by jrfaller** [comment]
Hi!

You have to install pythonparser and make it available in the path (look here : https://github.com/GumTreeDiff/gumtree/wiki/Getting-Started)

On a the side note : any reason why you are using axmldiff ?

Cheers!

**Comment by dayaad** [comment]
@jrfaller  Thank you Jean. am just running some experiments  no specific reason.

**Comment by jrfaller** [comment]
OK, because axmldiff is a very specific command we introduced for a paper about the automated tracking of fault in the linux Kernel. You might wanna also look at the more traditionnal textdiff or webdiff.

Cheers.

**Comment by dayaad** [comment]
@jrfaller, I actually was hoping to get the difference tree output from GumTree in JSON format, I saw the xml format is the closest to reach JSON format. any advice here? 
Thank you

**Comment by jrfaller** [comment]
There is an option in the textdiff format to get a json output. Look in the help!
