### ISSUE TITLE
XML tree

### ISSUE THREAD

**Issue by Krosent** [GumTreeDiff/gumtree#218]
Hello guys, 

I want to add support for another backend. From what I understood I need to parse the tree and convert it to XML. Could you give information on what XML structure should I provide to Gumtree? I am working on adding the support of a tree-sitter parser to gumtree.

**Comment by monperrus** [comment]
> I am working on adding the support of a tree-sitter parser to gumtree.

oh nice!

**Comment by jrfaller** [comment]
Hi!

A tree-sitter backend would be really nice!

W.r.t. your question look at #164 

Also we discuss a tree-sitter backend in #148 

Cheers!

**Comment by Krosent** [comment]
Guys, I see System.getProperty("gt.cgum.path", "cgum"); lines to get parsed AST from external sources. Where can I find the assignment values? I want to add python based script that outputs tree in XML. The script is already implemented, but I do not know how to include it to the code base. Python generator has issues with build btw.

**Comment by Krosent** [comment]
> Guys, I see System.getProperty("gt.cgum.path", "cgum"); lines to get parsed AST from external sources. Where can I find the assignment values? I want to add python based script that outputs tree in XML. The script is already implemented, but I do not know how to include it to the code base. Python generator has issues with build btw.

This problem is kinda solved.

**Comment by Krosent** [comment]
Here is the link to the repo with a tree-sitter parser for java written in python (https://github.com/Krosent/GumtreeJavaLangXmlGenerator).

**Comment by jrfaller** [comment]
Hi @Krosent ! 

Thanks for the pointer, the code seems straightforward, making tree-sitter a great candidate for producing ASTs.

A quick question, when reading your code I had the impression that there nothing java specific about it, am I right? Maybe we could adapt the code to produce XML for all tree-sitter backends ?

Cheers.

**Comment by Krosent** [comment]
> Hi @Krosent !
> 
> Thanks for the pointer, the code seems straightforward, making tree-sitter a great candidate for producing ASTs.
> 
> A quick question, when reading your code I had the impression that there nothing java specific about it, am I right? Maybe we could adapt the code to produce XML for all tree-sitter backends ?
> 
> Cheers.

Yes, you can adapt it for other languages as well. Tree sitter is not absolutely language agnostic, but you can comparatively fastly add support for any language you want.

**Comment by jrfaller** [comment]
Hi @Krosent just to warn you, I have introduced the GumTree tree-sitter-parser (https://github.com/GumTreeDiff/tree-sitter-parser), which is inspired by your take on tree-sitter integration! Thanks a lot!

Cheers.
