### ISSUE TITLE
Inconsistent AST node matches for functions with a single statement

### ISSUE THREAD

**Issue by bronikkk** [GumTreeDiff/gumtree#220]
Consider the following `src.cpp`:
```
int main() {
  return 0;
}
```
and `dst.cpp`:
```
int main() {
  if (true) {
    return 0;
  }
}
```
I can see the following result of `textdiff` client: function block in `src.cpp` was matched with the `if` block in `dst.cpp`. 

However, if we slightly change the sample files `src.cpp`:
```
int main() {
  int x;
  return 0;
}
```
and `dst.cpp`:
```
int main() {
  int x;
  if (true) {
    return 0;
  }
}
```
we can see that the function block in `src.cpp` is matched with the the function block in `dst.cpp`. So it looks like matching depends on whether the function consists of a single or of multiple statement. This sounds inconsistent for me.

Moreover, the latter behavior (function block <-> function block) seems correct, while the former doesn't.

**Comment by jrfaller** [comment]
Hi!

Thanks for your report. Mappings are authorized between elements of same lexical type (here block and block, legit). For modified blocks, the mapping is established between the blocks having the greatest ratio of common descendants, based on the already established mappings. This explains the behavior you noticed and it can be weird in some cases. Maybe it would be useful to add option to constrain mappings to have also same type parents (e.g. function / block only mappable to function / block and not if / block), although I am not sure it's a good idea?

Cheers.

**Comment by bronikkk** [comment]
@jrfaller I am not sure about this idea as well. I want to sleep on it.
