### ISSUE TITLE
TextDiff Json Format Output Clarification

### ISSUE THREAD

**Issue by dayaad** [GumTreeDiff/gumtree#221]
In textdiff -f json of 2 python files I see something like this in the output:
```
"action": "move-tree",
   "tree": "comparison [96,102]",
   "parent": "if_stmt [53,178]",
   "at": 2
```

Would it be possible to get an explanation of what do these values mean?
for  example -> at:2 and  "tree": "comparison [96,102]"

Thank you :)

**Comment by jrfaller** [comment]
- `"action": "move-tree"` means that this is a move tree action (a tree inside source file is moved in destination file)
- `"tree": "comparison [96,102]"` is the root node of the subtree moved in the source file (with the corresponding character start and end positions).
- `"parent": "if_stmt [53,178]"` is the node where the tree is moved inside the destination file (with the corresponding character start and end positions).
- `"at": 2` means as the third child of the parent node.
