### ISSUE TITLE
TextDiff: Python Method Level Mapping 

### ISSUE THREAD

**Issue by dayaad** [GumTreeDiff/gumtree#222]
Hello, I am interested in python method level differencing/mapping; is there a way to know what changes/actions happened at the method level only? 
In other words, when the mapping happens between AST Nodes would we be able to know if we are mapping a method type? 

please note that am only interested in (Python) matching.  

Thank you :)

**Comment by jrfaller** [comment]
Hi!

You have to do that manually by browsing the list of edits I am afraid 😄 

Cheers.
