### ISSUE TITLE
Problem about ID of the node of ast

### ISSUE THREAD

**Issue by DJjjjhao** [GumTreeDiff/gumtree#225]
I find that in the latest version, the node of ast  doesn't have the **"ID"** member, which causes that there is no unique identifier for node of ast and it's not easy to map the node in ast to the node in action. However, I notice that in the previous version, there exists **"ID"**.

**Comment by jrfaller** [comment]
Hi!

Of which command are you talking about?

Cheers.

**Comment by DJjjjhao** [comment]
Hi!
I want to map the node of ast to the node in edit, but I notice that the **Tree** class(that is, the node of ast) doesn't have the "ID" member no longer and I cannot map the node.

**Comment by jrfaller** [comment]
Maybe you cas use the character range + type to map the nodes?

**Comment by jrfaller** [comment]
Any follow-up on this issue?

**Comment by DJjjjhao** [comment]
Thank you for your advice, I understand that,

**Comment by jrfaller** [comment]
OK closing this ;)

Cheers.
