### ISSUE TITLE
How to convert a AST to the code

### ISSUE THREAD

**Issue by mrczw** [GumTreeDiff/gumtree#226]
The first step of my work is converting the Java source to the data structure "ITree" you designed. And the last step of my work is converting the "ITree" node to Java source, but I didn't know whether there is the API to convert the "ITree" node to Java source.Could you tell me the API I asked? Thank you!

**Comment by Symbolk** [comment]
I think it is infeasible, as the ITree provides generality between different languages, but at the cost of losing key details about the original code.

**Comment by jrfaller** [comment]
Hi!

It's infeasible. However there is http://www.martinezmatias.com/project/gtspoodiff/ that does that for Java.

Cheers.
