### ISSUE TITLE
Missing some matches when using gumtree diff python

### ISSUE THREAD

**Issue by KingGoldXu** [GumTreeDiff/gumtree#229]
Gumtree is a fantastic project!
However, I got some unexpected results when using it diff python file.
For example, in the pic below, The name `Controller` should match, instead of delete and insert! is it a bug?
![GumTreeResult](https://user-images.githubusercontent.com/16099210/112296773-177baf00-8cd0-11eb-9abc-ce3d88ebffe1.png)

**Comment by KingGoldXu** [comment]
gumtree version: gumtree-3.0.0-beta2
cmd: gumtree webdiff 007a1856dd8b5a781a3abe312a023344995162d6\^a\^nova\^api\^openstack\^compute\^servers.py 007a1856dd8b5a781a3abe312a023344995162d6\^b\^nova\^api\^openstack\^compute\^servers.py

**Comment by jrfaller** [comment]
Hi and thanks for your feedback.

It is strange indeed. Do you have the files somewhere?

Cheers.

**Comment by KingGoldXu** [comment]
Files attached! thanks
[example.zip](https://github.com/GumTreeDiff/gumtree/files/6197745/example.zip)

**Comment by jrfaller** [comment]
OK this is a known problem happening when the size of the tree to match is too big to apply the optimal algorithm.

You have a lighter alternate matcher here : 

`gumtree webdiff 007a1856dd8b5a781a3abe312a023344995162d6^a^nova^api^openstack^compute^servers.py 007a1856dd8b5a781a3abe312a023344995162d6^b^nova^api^openstack^compute^servers.py -m gumtree-simple``

(with other drawbacks)

I am considering a hybrid version that should be released soon.

Cheers.

**Comment by KingGoldXu** [comment]
Hi,
I am using gumtree to process a large amount of code.
I need a matched statements and changed statements.
Can you recommend which matcher is more suitable and faster?

**Comment by jrfaller** [comment]
gumtree-simple is clearly much faster.

w.r.t. accuracy I think it's an open question ;)

**Comment by KingGoldXu** [comment]
Thanks!
