### ISSUE TITLE
NPE on CompleteMatcher caused by it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap

### ISSUE THREAD

**Issue by martinezmatias** [GumTreeDiff/gumtree#235]
Hi @jrfaller 

I have a NPE when executing the CompleteMatcher on some cases (in particular with the CliqueSubtreeMatcher sub-matcher).
I prepared a PR with a test case that exposes that issue: 
https://github.com/GumTreeDiff/gumtree/compare/main...martinezmatias:int2obt?expand=1#diff-879b5ceed7a568e20f026afbca18c8400113123c35f62ec17f5400912cdbcae1R462

```
java.lang.NullPointerException
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$KeyIterator.nextInt(Int2ObjectOpenHashMap.java:891)
	at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:43)
	at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:26)
	at com.github.gumtreediff.matchers.heuristic.gt.CliqueSubtreeMatcher.filterMappings(CliqueSubtreeMatcher.java:54)
	at com.github.gumtreediff.matchers.heuristic.gt.AbstractSubtreeMatcher.match(AbstractSubtreeMatcher.java:90)
	at com.github.gumtreediff.matchers.CompositeMatchers$CompositeMatcher.match(CompositeMatchers.java:59)
	at com.github.gumtreediff.matchers.Matcher.match(Matcher.java:50)
	at com.github.gumtreediff.gen.jdt.TestJdtMatching.testCase_1_20391_Complete_Int2ObjNPE(TestJdtMatching.java:476)
``` 

At the beginning, I usually had that issue when using our GumTreeSpoon parser (@monperrus) so I initially created some workaround  and temporal fixes  on our parser for avoiding the issue. In particular, I found that the problem appears when we added virtual nodes (i.e., those nodes that we add in the GumTree AST that do not exist in the Spoon model)
However, I then discover that the problem also is present when using the JDT representation.

My initial suspicious is related to the duplication of hashes from nodes: on GumTreeSpoon parser we have virtual nodes  that are duplicates (as they have no labels and typically the same types i.e., "Modifiers"). If I deduplicate the codes, i.e., to put an unique value for the type, the problem (NPE) seems to disappear (but that impact on the final edit script)

Tests on PR https://github.com/GumTreeDiff/gumtree/pull/234

Thanks! 
Regards
Matias

**Comment by jrfaller** [comment]
Hi Matias and thanks for the PR!

I observed on your fork that removing the line `cliques.remove(hash);` fixes the problem. This line is useless anyway because the `cliques` map is only processed once.

Can you confirm it works?

Cheers.

**Comment by martinezmatias** [comment]
Hi @jrfaller 

I update the PR branch: it removes the line `cliques.remove(hash);` and the NPE seems to disappear. 
However, the edit-script generated by the Complete seems not correct, i.e., too long. (I dont know if there is another problem or if simply the Complete fails to generate a "good" edit-script on certain cases.
I added some new test cases that show those cases. https://github.com/martinezmatias/gumtree/commit/779d3393d20178c0ef166ffe7605d2b9d57feb20#diff-879b5ceed7a568e20f026afbca18c8400113123c35f62ec17f5400912cdbcae1R596

(It could maybe another issue that focus on Complete)

Cheers
Matias

**Comment by jrfaller** [comment]
Hi @martinezmatias !

Thanks a lot. To be franck, the complete matcher was a trial for an idea, but I've never really evaluated it as it was not behaving really good on the examples 😃 I am not sure it's of a big interest. It seems there is a bunch of Checkstyle errors, you seem to have tabs configured instead of spaces in your editor 😆 

Cheers!

**Comment by martinezmatias** [comment]
Hi @jrfaller 

>  It seems there is a bunch of Checkstyle errors, you seem to have tabs configured instead of spaces in your editor

You are right. I have neither format the code nor running checkstyle before pushing. Sorry for that. 

> the complete matcher was a trial for an idea, but I've never really evaluated it as it was not behaving really good on the examples 😃 I am not sure it's of a big interest

There is no problem. Actually, with the DAT experiment we can pinpoint all cases where Complete works fine. I wanted to be sure that those results were not affected by a bug (i.e., exposed by the removal of`cliques.remove(hash)`)

So, I will proceed with a clean PR now.  (code style, changing failing assertions, etc)

Cheers
Matias

**Comment by martinezmatias** [comment]
Hi @jrfaller 

I fixed the code and squashed all commits into one single commit. Now it passes the checks. I think the PR is ready https://github.com/GumTreeDiff/gumtree/pull/234

Thanks
Matias
