### ISSUE TITLE
Position problem with JavaParser

### ISSUE THREAD

**Issue by jrfaller** [GumTreeDiff/gumtree#239]
(Probably more appropriate to be discussed in a separate issue)
I am wondering why we have the ` + 2;` here. In SwingDiff the highlighted area seems to be one character larger than it should be

https://github.com/GumTreeDiff/gumtree/blob/7c51bb8c3c3c6f149614765b25845578c03f7765/gen.javaparser/src/main/java/com/github/gumtreediff/gen/javaparser/JavaParserVisitor.java#L86-L96

Thanks!

_Originally posted by @TigerHuang98 in https://github.com/GumTreeDiff/gumtree/issues/237#issuecomment-816042162_

**Comment by jrfaller** [comment]
Hi! Thanks for the report.

Could you make a test case to see if it works or fails?

Cheers.

**Comment by TigerHuang98** [comment]
File cl.java has the following content:
```java
class Cl{void foo(){int i=1;}}
```
When comparing this file with itself using SwingDiff and JavaParser, I got the following result:
![Screenshot-GumTree](https://user-images.githubusercontent.com/23556099/114196292-22c61000-9949-11eb-9d8a-8deadc54dfb7.png)

the highlighted area for node`foo [14,18]` should not cover the following"`(`"

change the ` + 2;` to ` + 1;` would fix this
