### ISSUE TITLE
Incorrect Result

### ISSUE THREAD

**Issue by codinuum** [GumTreeDiff/gumtree#240]
Comparing source files taken from [spring-roo](https://github.com/spring-projects/spring-roo) yields an incorrect result shown in the attachment. Methods from line 104 of the left pane are untouched although they should be reported as deleted.
<img width="1732" alt="2021-04-21 13 57 18" src="https://user-images.githubusercontent.com/1852939/115499897-3bb8b480-a2ab-11eb-8aa3-e2b8d9c40615.png">

**Comment by jrfaller** [comment]
This is really strange!

Could you attach the files, please?

**Comment by codinuum** [comment]
Here you are.
https://raw.githubusercontent.com/spring-projects/spring-roo/ef31da258434b383ec4b8d9994924ea25e9ecf9f/addon-gwt/src/main/java/org/springframework/roo/addon/gwt/GwtUtils.java
https://raw.githubusercontent.com/spring-projects/spring-roo/bdfec1d841da7f55ef8db5e5726a66ed5edbe45c/addon-gwt/src/main/java/org/springframework/roo/addon/gwt/GwtUtils.java

**Comment by jrfaller** [comment]
Ok thanks a lot!

It seems to be a parser-related problem, because the case works fines with javaparser and srcml 
`gumtree webdiff v0.java v1.java -m gumtree-simple-id -g java-javaparser`
`gumtree webdiff v0.java v1.java -m gumtree-simple-id -g java-srcml``

Maybe there is a syntax error in the left file?

Cheers.

**Comment by jrfaller** [comment]
OK the jdt AST is all messed up and I don't understand why, from the `isOneMethodsEqual` method declaration, all other method declarations are contained in under this method node, and node under the class node.

I wonder if there is a problem with the syntax, with JDT or with my JDT to gumtree conversion code :(

**Comment by jrfaller** [comment]
After further investigation, it seems due to the vararg parameter. As it is not apparent inside JDT's AST I have a rewrite rule for this one, therefore I think it might come from that, because after removing the vararg, everything parses smoothly

**Comment by jrfaller** [comment]
OK found and fixed ;)

Thanks for the report!

**Comment by codinuum** [comment]
Thanks!
