### ISSUE TITLE
Unable to get the same "Available Commands" from source code as from the release bin“

### ISSUE THREAD

**Issue by s1530129650** [GumTreeDiff/gumtree#243]
as shown in #88.
I run `gumtree` in `gumtree-3.0.0-beta2/bin`, the output is:

        No command given.
        Available Options:
        -C <2>  Set system property (-c property value).
        -v      Verbose mode
        --help  Display help (this screen).
        
        Available Commands:
        * webdiff: Web diff client
        * cluster: Extract action clusters
        * dotdiff: A dot diff client
        * htmldiff: Dump diff as HTML in stdout
        * list: List matchers, generators, clients and properties
        * parse: Parse file and dump result.
        * swingdiff: A swing diff client
        * textdiff: Dump actions in a textual format.
        * axmldiff: Dump annotated xml tree

However, when I open eclipse 2020-06 --> import `gradle` --> run "Run.java" without parameters on Window 10, it outputs:

        Unknown sub-command './gradlew'.
        Available Options:
        -C <2>	Set system property (-c property value). 
        -v	Verbose mode
        --help	Display help (this screen).
        
        Available Commands:

When I pass the same command "webdiff f1.java f2.java " to the main() in Run.java, it says:

        Unknown sub-command 'webdiff'.
        Available Options:
        -C <2>	Set system property (-c property value). 
        -v	Verbose mode
        --help	Display help (this screen).
        
        Available Commands:

Could you help me solve it?

FYI:

I have built the source code with "gradlew build -x test" successfully.

**Comment by s1530129650** [comment]
![image](https://user-images.githubusercontent.com/34572118/122528817-53b07880-d04f-11eb-9064-34c0ea75b8e2.png)

When I use IntelliJ. It outputs

    4:06:19 PM: Executing task 'Run.main()'...
    
    > Task :core:compileJava UP-TO-DATE
    > Task :core:processResources NO-SOURCE
    > Task :core:classes UP-TO-DATE
    > Task :core:jar UP-TO-DATE
    > Task :client:compileJava UP-TO-DATE
    > Task :client:processResources NO-SOURCE
    > Task :client:classes UP-TO-DATE
    
    > Task :client:Run.main()
    
    BUILD SUCCESSFUL in 589ms
    4 actionable tasks: 1 executed, 3 up-to-date
    No command given.
    Available Options:
    -C <2>	Set system property (-c property value). 
    -v	Verbose mode
    --help	Display help (this screen).
    
    Available Commands:
    * list: List matchers, generators, clients and properties
    * parse: Parse file and dump result.
    4:06:20 PM: Task execution finished 'Run.main()'.

**Comment by jrfaller** [comment]
Hi!

See #223 for a potential fix.

Cheers.

**Comment by s1530129650** [comment]
fixed, thanks

**Comment by NullException** [comment]
My son Denis Polikashin died at the 8th of April 2017 Здравствуйте. До свидания. С уважением, Поликашин Денис.тел. : 8 965 592 77 87   18.06.2021, 11:08, "Ensheng Shi" ***@***.***>: When I use IntelliJ. It outputs4:06:19 PM: Executing task 'Run.main()'...

> Task :core:compileJava UP-TO-DATE
> Task :core:processResources NO-SOURCE
> Task :core:classes UP-TO-DATE
> Task :core:jar UP-TO-DATE
> Task :client:compileJava UP-TO-DATE
> Task :client:processResources NO-SOURCE
> Task :client:classes UP-TO-DATE

> Task :client:Run.main()

BUILD SUCCESSFUL in 589ms
4 actionable tasks: 1 executed, 3 up-to-date
No command given.
Available Options:
-C <2>	Set system property (-c property value). 
-v	Verbose mode
--help	Display help (this screen).

Available Commands:
* list: List matchers, generators, clients and properties
* parse: Parse file and dump result.
4:06:20 PM: Task execution finished 'Run.main()'.

**Comment by s1530129650** [comment]
Sorry to hear about it
