### ISSUE TITLE
How to use gumtree comparing two commits to get diff?

### ISSUE THREAD

**Issue by wsczh** [GumTreeDiff/gumtree#247]
I only find compare two files, using gumtree. Is there a way to compare two commits?

**Comment by Symbolk** [comment]
AFAK, there is no such option in current gumtree.

However, implementing it is not hard, I implemented something to diff the working tree or a commit here: https://github.com/Symbolk/gumtree5/blob/91f733dab98d667f38834f11ddcbc3e5fc05a948/client/src/main/java/com/github/gumtreediff/client/smartcommit/GitServiceCGit.java#L87,

Comparing 2 commits and collect the old and new versions of diff files should not be hard, via git command or JGit library.

**Comment by jrfaller** [comment]
You can also try our documentation on Git integration : https://github.com/GumTreeDiff/gumtree/wiki/VCS-Integration

**Comment by wsczh** [comment]
thx, i will try them latter.
