### ISSUE TITLE
C++ Spurious Moves, Adds and Deletes

### ISSUE THREAD

**Issue by csiefer2** [GumTreeDiff/gumtree#248]
Using gumtree webdiff -m gumtree-simple, -m gumtree-hybrid, or no -m,  generates spurious add/deletes as well as spurious moves on the attached C++ header files.  gumtree htmldiff has similar pathologies.

[bugreport.zip](https://github.com/GumTreeDiff/gumtree/files/7138412/bugreport.zip)

**Comment by jrfaller** [comment]
OK this one is weird. They were some missing information in the AST that I gathered in the few last commits. However the file remains unadequately handled by the algorithms. I have to dig though the algorithms to understand if it's possible to do better :)

**Comment by zxylz** [comment]
I also use -m gumtree-simple and -m gumtree-hybrid.But I don't know what they mean. Where can I find explanations for these two options?

**Comment by jrfaller** [comment]
There are none at the moment, although I am trying to put an article together explaining them, but it keeps getting delayed because I prioritize new topics. In short they are faster algorithms than the default one, with a comparable accuracy.
