### ISSUE TITLE
Integrate with Visual Studio and make use of Roslyn

### ISSUE THREAD

**Issue by KOLANICH** [GumTreeDiff/gumtree#25]

**Comment by jrfaller** [comment]
Hi! I am not sure what you mean by make use of Roslyn ?

**Comment by jrfaller** [comment]
For the C# part, we now have support thanks to srcML. I think the support needs polishing but it's there and we can improve it incrementally. Using Roslyn might be better so if anybody wants to give it a try, please do :)

For visual studio, I am not planning to implement its support for now, the GumTree project focuses on the core tool, integration with IDEs will be done in external projects (that can be hosted on the GumTreeDiff organization of course).
