### ISSUE TITLE
how to display different types of edit actions using dotdiff?

### ISSUE THREAD

**Issue by wuyifan18** [GumTreeDiff/gumtree#251]
Thanks for the great work!
When I use 'gumtree dotdiff', only partial modifications are displayed without distinguishing types and some modifications have not been marked.
![image](https://user-images.githubusercontent.com/27428539/134451430-21135928-f831-41e6-8212-0c7fdafe07b3.png)

![image](https://user-images.githubusercontent.com/27428539/134451296-3810bf24-b963-4a0e-89c9-e2b1f419d413.png)

**Comment by jrfaller** [comment]
Hi!

In fact, I put this visualisation mostly for debugging so I did not polish it much, but you are completely right that we could display all the information w.r.t. to the edit actions inside, for instance by coloring the nodes. All it would take is to gather information about the MappingStore as well as the produced EditScript and use both to color the nodes  accordingly. This way we could know if a mapped node is an update, a move or nothing at all. Also on the right tree we could display the unmapped node in green and not in red. This is what you would want right?

Cheers.

**Comment by wuyifan18** [comment]
Thank you! I see.

**Comment by jrfaller** [comment]
Fixed by 1f7cba2
