### ISSUE TITLE
results of JAVA files are puzzling

### ISSUE THREAD

**Issue by zxylz** [GumTreeDiff/gumtree#256]
I compare two java files. The class name is the same. Some statements in the class are different. But I don't undertand why insert and delete are displayed in class name section.

**Comment by zxylz** [comment]
the java code
![图片](https://user-images.githubusercontent.com/41148314/147247315-30c4f4bc-97da-4c93-a2b7-9f4c119b3191.png)

**Comment by jrfaller** [comment]
Hi, and thanks for taking the time to contribute to GumTree.

This is a known problem of the classic gumtree algorithm. This should not happen with gumtree-simple.

Cheers!
