### ISSUE TITLE
How to make gumtree support parse tree?

### ISSUE THREAD

**Issue by zhangxiaosa** [GumTreeDiff/gumtree#257]
Hi, I plan to utilize gumtree for my research project, but I found gumtree is designed for AST and thus many tokens such as curlies and parenthesis are ignored. 
Is it easy to make it support parse trees?

**Comment by jrfaller** [comment]
Hi!

I believe there is nothing impossible about it. You have to provide a TreeGenerator that builds a parse tree from a stream.

Cheers!
