### ISSUE TITLE
Make a clear manual how to use it

### ISSUE THREAD

**Issue by KOLANICH** [GumTreeDiff/gumtree#26]
I have  dowloaded jar from releases page and then tried to launch and got nothing. Tried ```--help`` and aalso got nothing. Is it missing some modules? Please, give a clear manual how to install and use it.

**Comment by jrfaller** [comment]
Can you try with the tar.gz produced by building gumtree?

**Comment by KOLANICH** [comment]
>Can you try with the tar.gz produced by building gumtree?

I don't have any java toolchain. The tar.gz in releases is the source code. Maybe you should consider using travis-ci to create builds and put them somewhere (it allows providing secrets unvisible for users, which will be passed to scripts, which can be used to store auth credentials to put builds to remote servers)

**Comment by jrfaller** [comment]
OK, I managed to put a nightlies server in production thanks to your good suggestion.

Could you test from the binary that you can find at this URL?

https://bintray.com/jrfaller/GumTree/nightlies/99.99.99#files

**Comment by jrfaller** [comment]
I have added a page in the wiki, I will try to keep it up-to-date :)
