### ISSUE TITLE
gumtree Java inserting and deleting nodes of unchanged parts

### ISSUE THREAD

**Issue by nayeawon** [GumTreeDiff/gumtree#264]
Hello! Thanks for the amazing work on Gumtree!

I am currently working on analyzing patterns of AST changes of number of open source projects using EditScriptGenerator.
I have converted editScript to a List<Action> using asList() method.
Then, I found a little strange output when I tried to print the details provided as below.

![Screen Shot 2022-02-02 at 12 37 53 AM](https://user-images.githubusercontent.com/80326384/151999629-ad1bd2ab-f9ea-4060-894a-33fcec1d1cc2.png)

 
Above information is mined from a test repo with 6 commits, and above change is found in below URL
https://github.com/shine-jung/TodoListSQLApp/commit/834c578e1e0030701f4429b75fadecbab5e0d225

I find that 7th change is the only valid change, but the rest are meaningless.

I first suspected the commented block causing the strange output, but confirmed that it is not because of that.

![Screen Shot 2022-02-02 at 2 34 21 AM](https://user-images.githubusercontent.com/80326384/152020194-2720cf1c-78fe-4af0-a308-ad74afde9a46.png)
If the same nodes are deleted and inserted, it does not necessarily mean anything, or I might be missing out important parts.
There are 6 changes which are 3 pairs of meaningless deletion and insertion of same nodes.

Could anyone please help me explaining what these strange output means?

Thank you in advance.

**Comment by jrfaller** [comment]
Hi, and thanks a lot for the kind words, and for taking the time to help us improve the tool.

This is a known problem of the "classic" gumtree matcher (see for instance #256). It should not happen with the new "simple" matcher (see https://github.com/GumTreeDiff/gumtree/wiki/Commands to understand how to change the matcher).

Cheers!

**Comment by nayeawon** [comment]
It works well with the new simple matcher
Thank you that helps a lot :)

**Comment by xzm2000** [comment]
> Hi, and thanks a lot for the kind words, and for taking the time to help us improve the tool.
> 
> This is a known problem of the "classic" gumtree matcher (see for instance #256). It should not happen with the new "simple" matcher (see https://github.com/GumTreeDiff/gumtree/wiki/Commands to understand how to change the matcher).
> 
> Cheers!

How can I change matcher with APIs? Thanks~
