### ISSUE TITLE
Command line flag for specifying parser

### ISSUE THREAD

**Issue by nicolaskruchten** [GumTreeDiff/gumtree#265]
This is a feature idea that grew out of my comments in #263.

I think it would be helpful to have a cross-language command-line argument to specify which parser is to be used for a given set of inputs. It seems like today some parsers are in-process, like the ANTLR ones (I could be wrong about this) and some are separate programs, like the JS and Python ones. Given how sensitive the output is to the actual parsed input, it would be helpful to be able to create and tune external parsers for any language, not just JS and Python, and be able to optionally tell the `gumtree` executable via a command-line flag the path (and eventual arguments!) of a parser executable to run. This option's default value would basically be the current behaviour, for backwards-compatibility.

If this is something you would accept a pull-request for, I can take a look at actually doing this work :)

**Comment by jrfaller** [comment]
Hi!

Thanks for sharing your idea. Normally, there is something very similar to what you are proposing, namely the `-g` flag where you can supply a parser id. It is supposed to work with all gumtree subcommands.

For instance `gumtree parse test.java -g java-javaparser` will use the java parser backend to parse the java file.

You can use it also with `webdiff` but in this case avoid diffing whole folders with heterogeneous files as the given parser will be used for all the files.

Also, FYI, not very famous but sometimes handy you can try the `swingdiff` command that will get you a highly experimental GUI where you can browse the AST and the source code at the very same time!

A `gumtree list GENERATORS` will list all available backends, and some require external programs to be installed like you correctly guessed (they should perhaps signaled a little better). The current list is (priority id file_mask: class_name):

~~~
0	css-phcss	[\.css$]: com.github.gumtreediff.gen.css.CssTreeGenerator
0	java-jdt	[\.java$]: com.github.gumtreediff.gen.jdt.JdtTreeGenerator
0	js-acorn	[\.js]: com.github.gumtreediff.gen.jsacorn.JsAcornTreeGenerator
0	ocaml-treesitter	[\.ml$]: com.github.gumtreediff.gen.treesitter.OcamlTreeSitterTreeGenerator
0	php-treesitter	[\.php$]: com.github.gumtreediff.gen.treesitter.PhpTreeSitterTreeGenerator
0	python-pythonparser	[\.py$]: com.github.gumtreediff.gen.python.PythonTreeGenerator
0	python-treesitter	[\.py$]: com.github.gumtreediff.gen.treesitter.PythonTreeSitterTreeGenerator
0	ruby-jruby	[\.ruby$, \.rb$]: com.github.gumtreediff.gen.ruby.RubyTreeGenerator
0	ts-treesitter	[\.ts$]: com.github.gumtreediff.gen.treesitter.TypeScriptTreeSitterTreeGenerator
25	c-treesitter	[\.[ch]$]: com.github.gumtreediff.gen.treesitter.CTreeSitterTreeGenerator
25	java-treesitter	[\.java$]: com.github.gumtreediff.gen.treesitter.JavaTreeSitterTreeGenerator
25	js-rhino	[\.js$]: com.github.gumtreediff.gen.js.RhinoTreeGenerator
25	js-treesitter	[\.js$]: com.github.gumtreediff.gen.treesitter.JavaScriptTreeSitterTreeGenerator
25	r-treesitter	[\.[rR]$]: com.github.gumtreediff.gen.treesitter.RTreeSitterTreeGenerator
25	ruby-treesitter	[\.rb$]: com.github.gumtreediff.gen.treesitter.RubyTreeSitterTreeGenerator
50	antlr-antlr	[\.[gG]$]: com.github.gumtreediff.gen.antlr3.antlr.AntlrGrammarTreeGenerator
50	c-cocci	[\.[ch]$]: com.github.gumtreediff.gen.c.CTreeGenerator
50	c-srcml	[\.[ch]$]: com.github.gumtreediff.gen.srcml.SrcmlCTreeGenerator
50	cpp-srcml	[\.(CC?|cpp|cc|hh?|hpp)$]: com.github.gumtreediff.gen.srcml.SrcmlCppTreeGenerator
50	cs-srcml	[\.cs$]: com.github.gumtreediff.gen.srcml.SrcmlCsTreeGenerator
50	java-javaparser	[\.java$]: com.github.gumtreediff.gen.javaparser.JavaParserGenerator
50	java-srcml	[\.java$]: com.github.gumtreediff.gen.srcml.SrcmlJavaTreeGenerator
50	json-antlr	[\.json$]: com.github.gumtreediff.gen.antlr3.json.AntlrJsonTreeGenerator
50	php-antlr	[\.php.?$]: com.github.gumtreediff.gen.antlr3.php.PhpTreeGenerator
50	r-antlr	[\.[rR]$]: com.github.gumtreediff.gen.antlr3.r.RTreeGenerator
50	xml	[\.gxml$]: com.github.gumtreediff.io.TreeIoUtils.XmlInternalGenerator
50	xml-antlr	[\.xml$, \.xsd$, \.wadl$]: com.github.gumtreediff.gen.antlr3.xml.XmlTreeGenerator
100	java-cdjdt	[\.java$]: com.github.gumtreediff.gen.jdt.cd.CdJdtTreeGenerator
~~~

I guess I should better document these features :-)

Is this what you had in mind?

**Comment by nicolaskruchten** [comment]
Ah, that's all very helpful context! I had run `gumtree -h` and seen `list` as a command but hadn't understood that I had to add `GENERATORS` to get some kind of output out of it :) I've been using `swingdiff` and found it very helpful, but `webdiff` not so much. A tiny bit of extra info in the output of `gumtree -h` would probably go a long way here, notably around the `-g` option and the exact usage of `-C` which took me a little while to figure out.

Re the `-g` option, that's half of what I'm proposing here, but one thing that I can't do with it right now is use it to say "please use the executable at `path/whatever` with options `--a=b` to parse R or Python files". Maybe all I need to do to implement this is to add a new `GenericExternalExecutableGenerator` called `external` that accepts `*` files with low priority and which accepts some properties like `gt.external.*` or something. I could then run a command like `gumtree textdiff f1.R f2.R -g external -C gt.external.path path/whatever -C gt.external.options "--a=b --c=d"`. This would let me easily play with my own parser that's defined outside of the `gumtree` source/not in Java ;)

**Comment by jrfaller** [comment]
You're completely right, the help option has not received much love over the recent years, and was even broken on some commands. I tried to make a quick fix to resolve the broken issue problem, and I will create a new ticket to improve the message description. In the meantime, I improved a lot the wiki page that describes available commands : https://github.com/GumTreeDiff/gumtree/wiki/Commands.

Thanks for the clarification, I completely understand your feature request now and understand why it can be useful! I think your proposal is very good, and will be very easy to implement. The only concern I have with it is that in `webdiff` I check if files have tree generators associated to them, and deactivate structural diff if it's not the case. I use the following code for this: `TreeGenerators.getInstance().hasGeneratorForFile(file.first.getAbsolutePath())`. If we add a `*` generator, this would always answer `true` and this would be annoying because I would no longer have a mean to differentiate with parsable files and non parsable files.

I wonder if that it would perhaps be wiser to handle this directly at the level of the `TreeGenerators` with a  dedicated method such as `loadFromExternalCommand(String command)`?

**Comment by nicolaskruchten** [comment]
Thanks for the added documentation! I learned some stuff already :)

Re the overly-broad wildcard, I see the problem. For my use-case I'm not passing in entire directories so I hadn't thought of it. One very simple way out might be for this external-generator to accept another command-line option that indicates which file suffixes it can process for a given invocation, so it would be invoked with `gumtree textdiff f1.R f2.R -g external -C gt.external.path path/whatever -C gt.external.filematch '\.[rR]$'` or similar?

**Comment by jrfaller** [comment]
Fixed by 1abb75ebf5a2d602e0a293327a567a602da13819

**Comment by jrfaller** [comment]
https://github.com/GumTreeDiff/gumtree/wiki/Commands is up to date for the documentation

**Comment by jrfaller** [comment]
It's not ideal, but it is used for all files, regardless of the file extension 😄
