### ISSUE TITLE
How to obtain parent node info?

### ISSUE THREAD

**Issue by SherloqueChang** [GumTreeDiff/gumtree#269]
Hi!

I'm invoking `editScriptGenerator.computeActions(mappings)` to get edit actions in **C code file**.

For example, 
```
void func() {
 +   a = 1;
    printf("func");
}
```

As for the edit action, I get:
```
===
insert-tree
---
ExprStatement [33,39]
    Some [33,39]
        Assignment [33,38]
            Ident [33,34]
                GenericString: a [33,34]
            GenericString: = [35,36]
            Constant: 1 [37,38]
        GenericString: ; [38,39]
to
Compound [20,43]
at 0
```

The problem is I hope to get the name of its parent node, which should be `func`. But I can only get `Compound[20,43]`. Is there any solution to this? Thanks!

**Comment by jrfaller** [comment]
Hi!

I am not an expert of cgum's grammar, so the most easy way to get started is to also print the whole AST (`root.toTreeString()`), then you will understand how to get to the relevant parts. Beware that cgum has some known issues (see its bug tracker).

Cheers!
