### ISSUE TITLE
Consider convertation into C#

### ISSUE THREAD

**Issue by KOLANICH** [GumTreeDiff/gumtree#27]
ikvm and ilspy could be helpful for it.

**Comment by jrfaller** [comment]
C# is now supported thanks to srcML

**Comment by irajdeep** [comment]
Hi , could you please provide the steps to work on C# source files ? I have tried adding srcML to the system path and running gumTree , but it gives the following error.
`java.lang.UnsupportedOperationException: No generator found for file: /U`
`at com.github.gumtreediff.gen.Generators.getTree(Generators.java:47)
  at com.github.gumtreediff.client.diff.ui.web.views.DiffView.<init>(DiffView.java:49)
  at com.github.gumtreediff.client.diff.ui.web.DiffServer.serve(DiffServer.java:61)
  at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:953)
  at fi.iki.elonen.NanoHTTPD$1$1.run(NanoHTTPD.java:208)
   at java.lang.Thread.run(Thread.java:745)`

**Comment by KOLANICH** [comment]
I didn't meant C# AST in THIS issue. I meant that CLR is a better VM than JRE: it is less resource consuming. Because c# is rather similar to java [there exist](https://developer.xamarin.com/guides/android/advanced_topics/java_integration_overview/porting_java_to_csharp/) automatical converter tools.

**Comment by jrfaller** [comment]
Mmm ok I understand :)

Personnally, I really prefer to maintain the program in Java, therefore GumTree will remain developed in Java. However, if someone is interested in porting the code to C#, it would be really cool!
