### ISSUE TITLE
Suggestion for enhanching the edit script

### ISSUE THREAD

**Issue by algomaster99** [GumTreeDiff/gumtree#270]
Hi! I have a suggestion for an improvement in the edit script.

Consider these two files:
**left**
```java
import java.util.LinkedList;
import java.util.Queue;

class TreeTraversal {

    class TreeNode {
        public int val;
        public TreeNode left;
        public TreeNode right;

        public TreeNode(int val) {
            this.val = val;
        }
    }
}
```
**right**
```java
import java.util.LinkedList;
import java.util.Queue;

class TreeTraversal {

    class TreeNode {
        public int val;
        public TreeNode left;
        public TreeNode right;

        public TreeNode(int val) {
            this.val = val;
            left = right = null;
        }

        public TreeNode(int val, TreeNode left, TreeNode right) {
            this.val = val;
            this.left = left;
            this.right = right;
        }
    }
}
```
Its diff is shown as:
![Screenshot from 2022-02-18 15-23-12](https://user-images.githubusercontent.com/35191225/154700317-e8754e00-18a6-4699-a567-ac55a0c027ae.png)

I think the move operation of `this.val = val;` is not necessary. It should be kept as-is for the first constructor. Can this be improved by fixing the `ChawatheScriptGenerator`?

**Comment by jrfaller** [comment]
Hi!

Thanks for the case.

It's awkward that's it's matching with the statement from the second constructor. I will investigate why.

Cheers.
