### ISSUE TITLE
How to debugging gumtree?

### ISSUE THREAD

**Issue by sws797** [GumTreeDiff/gumtree#272]
#223
> Okay I see what's going on. This is fixed in the latest commit. In your version you can get it to work using : `/gradlew :dist:run --args="..."`
> 
> Cheers!

Hi @jrfaller ,
The gumtree is very **cool**, as a person who has not formally studied Java, I want to learn about the implementation of gumtree at the code level, but I have some problems:
It can really run with `/gradlew run --args="webdiff D:/left/file1.java D:/right/file1.java"`, but it doesn't seems like a debugging way.
I've been trying to run the project in debugging mode these days, but all the schemes mentioned in issues failed.

I encountered the following errors while running `Client.Run` by IDEA:
1. No command given. (So next I added the command)
2. Unknown sub-command 'webdiff'. (Next I changed it to Available Commands: parse)
3. Error while running client 'parse'.... java.lang.UnsupportedOperationException: No generator found for file: D:/left/file1.java

This is my file1.java:
```
public class Test {
    public String foo(int i) {
        if (i == 0) return "Foo!";
    }
}
```

How should I run it in debug mode using IDEA, any suggestions?

_Originally posted by @sws797 in https://github.com/GumTreeDiff/gumtree/issues/223#issuecomment-1056073882_

**Comment by jrfaller** [comment]
Hi!

To debug using IDEA I use a gradle run configuration with the following run command : `run --args='webdiff left.java right.java'`, then I launch it in debug mode.

**Comment by sws797** [comment]
Thanks for your reply.
I don't understand how to "launch it in debug mode".
First run:
![image](https://user-images.githubusercontent.com/33458935/156345213-aaace066-2611-4ae2-9805-2f1c1dff8190.png)
then:
![image](https://user-images.githubusercontent.com/33458935/156345962-eb45d6d1-7539-4bc3-a604-285054d67c95.png)
and get:
![image](https://user-images.githubusercontent.com/33458935/156346132-f91ca8bd-ce6e-45f3-8cbd-5ae9a37e655c.png)

Did I miss something?

**Comment by sws797** [comment]
If I change webdiff to parse, the result is:
![image](https://user-images.githubusercontent.com/33458935/156346791-22b2881d-8353-4a56-adc3-184a22536aa7.png)

**Comment by jrfaller** [comment]
This is how I configure it :

<img width="950" alt="Capture d’écran 2022-03-02 à 12 32 49" src="https://user-images.githubusercontent.com/3370556/156354144-03755e01-3299-42be-9712-8b80f53778b2.png">

**Comment by sws797** [comment]
Oh, it works! Thank you very much! (o゜▽゜)o☆
