### ISSUE TITLE
C Struct Diff Not Recognized

### ISSUE THREAD

**Issue by SherloqueChang** [GumTreeDiff/gumtree#278]
Hi! 
I'm using GumTree Java API for C code file differencing. However, I found that the change inside **struct** ( adding a field variable, for example ) cannot be recognized. Is this a defection of GumTree or I'm not using it correctly?

**Comment by jrfaller** [comment]
Hi!

Do you know which parser you are using? cgum?

**Comment by jrfaller** [comment]
can you try using the `cgum` command is wrong inside the AST?

**Comment by jrfaller** [comment]
Yes I believe this is because of `cgum`. Maybe you could try with the brand new tree-sitter C parser or srcml ?

Cheers!

**Comment by SherloqueChang** [comment]
emmm... Another question here.

If I'd like to use tree-sitter C parser by invoking Java API, how should I code?

**Comment by jrfaller** [comment]
Look here : https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API#using-a-specific-generator

The one you are interested in is : https://github.com/GumTreeDiff/gumtree/blob/main/gen.treesitter/src/main/java/com/github/gumtreediff/gen/treesitter/CTreeSitterTreeGenerator.java

Also, you need [tree-sitter-parser](https://github.com/GumTreeDiff/tree-sitter-parser) installed

Cheers.

**Comment by SherloqueChang** [comment]
OK. Truly thanks!
