### ISSUE TITLE
Wrong position info of tree node

### ISSUE THREAD

**Issue by SherloqueChang** [GumTreeDiff/gumtree#280]
Hi! I'm using GumTree on Ubuntu. 

When I obtained the whole tree structure of the program in `xml` format, I found there was something wrong with the starting position of certain tree node. For example:
```
<tree type="Definition" pos="242689" length="9158">
```
But in fact, `pos` of the "Definition" should be 242569.

I couldn't figure out why this went wrong.

**Comment by jrfaller** [comment]
Hi!

With which parser?

Cheers.

**Comment by SherloqueChang** [comment]
cgum

**Comment by jrfaller** [comment]
Sorry it's highly possible. Cgum is not really maintained at the moment. Maybe you could try with tree-sitter C parser?

Cheers.

**Comment by SherloqueChang** [comment]
Ah, I'm invoking GumTree Java API in a maven project. As far as I'm concerned, tree-sitter C parser doesn't provide maven dependency. Is that so?

**Comment by jrfaller** [comment]
You're right, it's not released yet on Maven central.

Cheers.
