### ISSUE TITLE
webdiff issue

### ISSUE THREAD

**Issue by yehyaali151989w** [GumTreeDiff/gumtree#282]
Hello dear all, 

Thanks for the amazing work.

I am trying to use this command: gumtree webdiff old.js new.js but it never displays the web results as seen in the figure:

help please.

![Screenshot_1](https://user-images.githubusercontent.com/104826790/169109728-04551e52-b259-4f87-ad81-6a93d52ef5cf.png)

**Comment by jrfaller** [comment]
Hi!

After running this command, you can just enter the `http://127.0.0.1:4567` URL in your browser, and you should see the diff.

Cheers.
