### ISSUE TITLE
no ast 

### ISSUE THREAD

**Issue by zqudm** [GumTreeDiff/gumtree#283]

**Comment by zqudm** [comment]
String str1="code=this(duration, null, null);";
                String str2 = "code = super();";
                String left="./time_22_buggy/src/main/java/org/joda/time/base/BasePeriod.java";
                String right="./time_22_fix/src/main/java/org/joda/time/base/BasePeriod.java";
                final Diff result = new AstComparator().compare(str1,str2,left,right);
                 System.out.println(result.toString());
                for (Operation o :result.getRootOperations())
                    System.out.println(o.toString()+" ------ " + o.getNode().toString());
--------------------------------------------------------------------
When i run the code above, its output is "no AST change"
What is wrong?

**Comment by algomaster99** [comment]
Hi @zqudm ! This should be fixed in 1dc99ffbc4516fd6a4660ec67a25bc3c13cd3698.
