### ISSUE TITLE
Diff is not fine-grained

### ISSUE THREAD

**Issue by algomaster99** [GumTreeDiff/gumtree#285]
The AST diff for the patch - https://github.com/khaes-kth/drr-execdiff/commit/0a8a5d1d5fc3a6d0681e7344ddd773acdea27dda - is not fine-grained. It shows the deletion and insertion of the constructor. Ideally, it should show that `DEFAULT_MAXITERATIONS` has been updated to `DEFAULT_CHECKFEASABLECOUNT`. This could be a potential bug in `ChawatheScriptGenerator`?

![Screenshot from 2022-06-15 17-55-52](https://user-images.githubusercontent.com/35191225/173872164-94c5e49f-b84a-4c03-bbfb-1b33c3839afc.png)

**Comment by jrfaller** [comment]
Hi! Which algorithm produces that?

**Comment by jrfaller** [comment]
OK I think this is the default one. Can you try with `-m gumtree-simple-id` ?

Cheers.

**Comment by jrfaller** [comment]
I think it's not the case because this algorithm also uses `ChawatheScriptGenerator` without having problems. Therefore I suspect it's more a matching problem.

Cheers.

**Comment by algomaster99** [comment]
> Therefore I suspect it's more a matching problem.

It indeed is a matching problem. I realised that `gumtree-spoon` uses `ClassicGumtree` by default which results in the above non-optimal AST diff. I could just replace the matcher, but it breaks some test case pm gumtree-spoon. One of which I feel would be a regression.
**left**
```java
String padding =
                "                                          "
                	.substring(0, indent);
            BufferedReader reader =
                new BufferedReader(new FileReader(file));

            // Skip the <?xml... first line
            String line = reader.readLine();
```
**right**
```java
try {
            String padding =
                "                                          "
                	.substring(0, indent);
            BufferedReader reader =
                new BufferedReader(new InputStreamReader(new FileInputStream(file), "UTF-8"));

```
Using `gumtree-simple-id` results in a match which is much more coarse-grained. It returns an insertion and deletion of a local variable. However, using `ClassicGumtree` results in operations on the `ConstructorCall`. I am not sure which one is more optimal. If there is a documentation for it, please let me know.

**Comment by jrfaller** [comment]
Hi @algomaster99!

The whole problem of finding the shortest possible edit script is a NP-hard problem, therefore all mapping algorithms are heuristics, therefore some work better than other for a given input unfortunately. There is also the Hybrid matcher that should combine both.
