### ISSUE TITLE
Option for disabling move operation

### ISSUE THREAD

**Issue by algomaster99** [GumTreeDiff/gumtree#286]
Hi! Is there an option to disable the move operations? My use case requires that I get the edit script that only contains `Insert`, `Delete`, and `Update`. I was checking the documentation for [`webdiff`](https://github.com/GumTreeDiff/gumtree/wiki/Commands#webdiff) command, but I could not find something relevant.

**Comment by jrfaller** [comment]
Yes there is : https://github.com/GumTreeDiff/gumtree/blob/main/core/src/main/java/com/github/gumtreediff/actions/InsertDeleteChawatheScriptGenerator.java.

I believe that you need to use it via the Java API I don't think there is an option for the CLI.

**Comment by algomaster99** [comment]
Thank you for the prompt response! Yes, I intend to use it with gumtree-spoon.

**Comment by algomaster99** [comment]
The script worked well with gumtree-spoon, but I am not integrating this API there for some other reason. Thanks for answering,  again!
