### ISSUE TITLE
Feature request: Markdown support

### ISSUE THREAD

**Issue by JensRantil** [GumTreeDiff/gumtree#314]
I am struggling to find a semantic diff tool for Markdown files. In essence I want to see the diff, independent of at which I wrap my lines in the markdown paragraphs.

For example the Markdown
```md
This is a text.
```
and
```md
This is
a text.
```
should be equivalent.

**Comment by monperrus** [comment]
FYI, there is https://github.com/davidar/pandiff/

**Comment by jrfaller** [comment]
Hi,

I don't think that GumTree's algorithm would be a good fit for markdown documents where there is a lot of text... I think the tool provided by @monperrus is a much better fit!

Cheers.
