### ISSUE TITLE
Gumtree usage for c# source files 

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#32]
I am trying to use Gumtree to get source code differences between c# files. As mentioned in the Quickguide I have downloaded scrML and added it to the system path.
When I execute the command - 
`./gumtree-20160905 webdiff left.cs right.cs`
It shows `java.lang.UnsupportedOperationException: No generator found for file: ` 
How to resolve this issue ?
Thanks

**Comment by irajdeep** [comment]
Hi , one of my friend has found the fix for this issue, We need to add the following line to the dependencies section of the `build.gradle` file -
`compile project(':gen.srcml')`
I think this should be added to the wiki

**Comment by jrfaller** [comment]
Great, well done for the fix.

Just to be sure, the correct file is the `build.gradle` from the dist module right?

**Comment by irajdeep** [comment]
Yeah

**Comment by jrfaller** [comment]
BTW, C# support is in early stages, and needs testing. I think the AST is correctly built, but there might be glitches in the line numbers information, so use it carrefully ;)

**Comment by irajdeep** [comment]
Sure :)
