### ISSUE TITLE
Error while running gumtree with textdiff option

### ISSUE THREAD

**Issue by nimisha-agarwal** [GumTreeDiff/gumtree#322]
![Screenshot from 2023-11-07 13-02-22](https://github.com/GumTreeDiff/gumtree/assets/10176876/67f07fde-4710-4ff0-9472-c9bdb7c193d7)

How to resolve this error?

**Comment by jrfaller** [comment]
Hi! You have to install and put in the path tree sitter parser.

Cheers

**Comment by nimisha-agarwal** [comment]
Do I need to install the java-tree-sitter parser? Can you share the link that contains instructions for installing it?

**Comment by jrfaller** [comment]
It's all on the tree sitter parser repo, located in the same organization.

**Comment by nimisha-agarwal** [comment]
Thank you so much. I got it.

**Comment by nimisha-agarwal** [comment]
![Screenshot from 2023-11-07 15-40-42](https://github.com/GumTreeDiff/gumtree/assets/10176876/83cf45ac-ea53-460f-a934-9209e9b1c5ef)

After installing the tree sitter and adding it to the system path, I got this new error. Can you help me in resolving it?

**Comment by jrfaller** [comment]
Apparently, there is a syntax error in your file.

**Comment by nimisha-agarwal** [comment]
Do you mean the error is in the GumTree code, as its binary is extracted from the zip file generated after the build?

**Comment by jrfaller** [comment]
Could you attach the files you are trying to diff? The syntax error should be in one of those

**Comment by nimisha-agarwal** [comment]
I am using the same file for both arguments. Here are the contents:
[solution.txt](https://github.com/GumTreeDiff/gumtree/files/13296376/solution.txt)

**Comment by jrfaller** [comment]
Could you provide me the command? It works for me

**Comment by jrfaller** [comment]
OK it's definitively working on my side, although the result is not very interesting ;-)

Something is not right with your install. Could you try `tree-sitter-parser.py solution.c` ?

**Comment by nimisha-agarwal** [comment]
I am getting the following error on running this command:
![Screenshot from 2023-11-20 18-28-57](https://github.com/GumTreeDiff/gumtree/assets/10176876/59e881cf-fa50-4e10-9e4d-c15cb41023bc)

**Comment by nimisha-agarwal** [comment]
I have checked them out, and GumTree is also working now. Thanks for all the help :)

**Comment by jrfaller** [comment]
if you don't need the dependent packages, you can install GumTree without them, it will work, if not you need to find how to compile manually the required native packages.
