### ISSUE TITLE
3.0 jdt tree generator does not handle the type arguments of MethodInvocation

### ISSUE THREAD

**Issue by tsantalis** [GumTreeDiff/gumtree#323]
MethodInvocation:
     [ Expression . ]
         **[ < Type { , Type } > ]**
         Identifier ( [ Expression { , Expression } ] )

For more details have a look at [issue](https://github.com/pouryafard75/RM-ASTDiff/issues/92)
Bug found by @pouryafard75

**GumTree jdt generator 3.0**
<img width="1439" alt="290710646-c40542ef-b86d-4b7b-936d-8ad9361fdc9d" src="https://github.com/GumTreeDiff/gumtree/assets/1483516/82e25d52-cc42-431c-bc40-252e5ce799a4">

**GumTree jdt generator 2.1**
<img width="1435" alt="290710681-ec1d22ae-b5c2-4951-a143-bc32d98c98ec" src="https://github.com/GumTreeDiff/gumtree/assets/1483516/809818bb-c967-4f40-af3c-9d9da41baf1f">

**Comment by jrfaller** [comment]
Thanks for the report @tsantalis, @pouryafard75! I will look into it! Cheers

**Comment by tsantalis** [comment]
Thank you @jrfaller 
We are hoping for a new version of jdt tree generator fixing this issue.

**Comment by tsantalis** [comment]
@jrfaller 
Pouria made a PR fixing this issue. Please have a look at it #327

**Comment by jrfaller** [comment]
Fixed by #327 !
