### ISSUE TITLE
Order ignored?

### ISSUE THREAD

**Issue by codinuum** [GumTreeDiff/gumtree#326]
The following should result in two updates (or less optimal move+delete+insert) because import_from_stmt is ordered.
<img width="750" alt="01-18-2024 9 47 26" src="https://github.com/GumTreeDiff/gumtree/assets/1852939/347ecb10-d630-44ef-ba31-b0165d4957c5">
[b0.py.txt](https://github.com/GumTreeDiff/gumtree/files/13970664/b0.py.txt)
[b1.py.txt](https://github.com/GumTreeDiff/gumtree/files/13970665/b1.py.txt)

**Comment by jrfaller** [comment]
I cannot reproduce this result, which parser are you using? With tree sitter I have one delete / insert which is due to the way the parser encode from statements.

Cheers!

**Comment by codinuum** [comment]
I tried the following.
`gumtree webdiff -m gumtree-simple -g python-treesitter b0.py b1.py`
