### ISSUE TITLE
How to get the linenumber of changes in GumTree ? 

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#33]
<img width="317" alt="right" src="https://cloud.githubusercontent.com/assets/7368670/18310462/9dbbdeb0-750f-11e6-88ca-5c9a022a011d.png">
<img width="473" alt="left" src="https://cloud.githubusercontent.com/assets/7368670/18310463/9dbcaa8e-750f-11e6-9924-442fc755c020.png">

So I want to print the changes along with line number 5,6 and 7 for the above 2 files when I run gumtree with diff argument.
Thanks

**Comment by jrfaller** [comment]
I guess you'll have to write a custom ActionSerializer to have the information you need. This should be easy, you can look at how the current serializer is done.

**Comment by irajdeep** [comment]
BTW Can you help me locate the class file for C# entity type changes , like for JAVA it's 
https://github.com/GumTreeDiff/gumtree/blob/develop/gen.jdt/src/main/java/com/github/gumtreediff/gen/jdt/cd/EntityType.java file
Thanks

**Comment by jrfaller** [comment]
Good question ;)

Types come from srcML implementation, so maybe you'll find it in their code/doc.

**Comment by irajdeep** [comment]
Thanks :)

**Comment by irajdeep** [comment]
The entity types available for C# can be found in [srcML](http://www.srcml.org/doc/cs_srcML.htmll)
and for Javascript it can be found in the Token.java file in the [Mozzila Rhino](https://github.com/mozilla/rhino)

**Comment by irajdeep** [comment]
I have a found a untidy hack to get the line line number changes , from the position (offset of changes) given by gumTree. As of now I wrote a python script which takes the offset as an input and outputs the line number. As @jrfaller mentioned a neat way would be to implement a Serializer. I will try to implement it when I get some time :)

**Comment by jrfaller** [comment]
I will mark it as closed for now. If you come up with a neat serializer don't forget to make a PR!

**Comment by irajdeep** [comment]
Sure , I will try to do it soon :)

**Comment by Symbolk** [comment]
@irajdeep Hi there, I am struggling on this too, for java files. Maybe you can give me a hand?
