### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by Sin-Mim** [GumTreeDiff/gumtree#337]
Hi,

I pulled the Docker image using ```docker pull gumtreediff/gumtree```, and then executed the command ```docker run -v /my/original-folder:/diff/left -v /my/modified-folder:/diff/right -p 4567:4567 gumtreediff/gumtree webdiff left/ right/``` as its mentioned in [documentation](https://github.com/GumTreeDiff/gumtree/tree/main/docker). However, I encountered the error ```Unknown sub-command 'webdiff'```. It seems that there are no available commands. Am I missing something : )?

**Comment by jrfaller** [comment]
Normally fixed by #87d9dcc
