### ISSUE TITLE
Gumtree showing wrong diff portions for c# source files

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#34]
<img width="655" alt="screen shot 2016-09-07 at 8 31 43 pm" src="https://cloud.githubusercontent.com/assets/7368670/18320261/25e84330-753a-11e6-965c-2927d97de43f.png">
<img width="650" alt="screen shot 2016-09-07 at 8 32 16 pm" src="https://cloud.githubusercontent.com/assets/7368670/18320279/38b6d666-753a-11e6-908a-d0c2b4fc3312.png">

Showing wrong diff for above 2 sample c# source files

**Comment by jrfaller** [comment]
Ok I was sure there was a problem. Maybe it's coming from srcml giving wrong positions to ast nodes... Could you check the raw result of the srcml command?

**Comment by irajdeep** [comment]
Sure,I will look into it and update the result here

**Comment by jrfaller** [comment]
OK, head of develop branch should fix this issue. Can you check?

**Comment by irajdeep** [comment]
<img width="1280" alt="screen shot 2016-09-12 at 4 12 48 pm" src="https://cloud.githubusercontent.com/assets/7368670/18435379/d4b616f4-7903-11e6-8826-afd6227e8854.png">
<img width="647" alt="screen shot 2016-09-12 at 4 12 39 pm" src="https://cloud.githubusercontent.com/assets/7368670/18435380/d4b69e80-7903-11e6-93ef-dffeb55294c2.png">
Awesome ! The command seems to have been resolved.
