### ISSUE TITLE
Steps to get AST Diff for Python Files

### ISSUE THREAD

**Issue by SagarBhatia** [GumTreeDiff/gumtree#342]
I have 2 .py files for which I need to get the AST Diff. I installed Gumtree and pythonparser in my Windows system but I couldn't find exact steps how to get Diff of python files. Can anyone tell me the detailed steps I need to follow to get AST Diff of python files.?

**Comment by jrfaller** [comment]
Anything not detailed enough in https://github.com/GumTreeDiff/gumtree/wiki/Getting-Started ?

**Comment by SagarBhatia** [comment]
I am currently getting this error. I have python parser and added that in PATH. Not getting any Output on Localhost stating 500 Internal Server error. 
![gumtreeError](https://github.com/GumTreeDiff/gumtree/assets/34151538/3e15cc10-e3b0-4128-a21a-adc1fbbd3048)

**Comment by jrfaller** [comment]
I am no Windows expert but it looks like a path problem!

**Comment by SagarBhatia** [comment]
If we run webdiff, it displays diff on web browser. How can I get the Diff code? I want to use/integrate Gumtree as tool and use  the Diff Output for further process. How can I be able to do it? In browser it displays Orange and green colour difference

**Comment by jrfaller** [comment]
Hi!

You need to use the Java API! https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API
