### ISSUE TITLE
Gumtree not showing comment diff for Javascript source files 

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#35]
<img width="686" alt="screen shot 2016-09-09 at 1 51 43 pm" src="https://cloud.githubusercontent.com/assets/7368670/18383018/99c307da-7694-11e6-90ce-4736cb114307.png">

**Comment by jrfaller** [comment]
Maybe this is because comments are not part of the Rhino AST? I will look into that.

**Comment by irajdeep** [comment]
Maybe , but I do see enum of "CommentType" (LINE , BLOCK ,JSDOC ,HTML) in the Token.java file of Rhino.

**Comment by jrfaller** [comment]
OK this seems possible to do : http://stackoverflow.com/questions/15658569/using-rhinos-javascript-parser-how-to-get-the-comments

I will push a fix soon

**Comment by irajdeep** [comment]
Cool , Thanks :)

**Comment by irajdeep** [comment]
Thanks the issue has been fixed :)
<img width="1270" alt="screen shot 2016-09-09 at 5 48 12 pm" src="https://cloud.githubusercontent.com/assets/7368670/18389159/9eeb7046-76b5-11e6-927d-d00113eb9e6c.png">

**Comment by jrfaller** [comment]
neat!
