### ISSUE TITLE
generate edit script through command

### ISSUE THREAD

**Issue by yikengboy** [GumTreeDiff/gumtree#351]
Can I generate editing scripts for two files through the command line?

**Comment by jrfaller** [comment]
Hi! use the `textdiff` command! Cheers.

**Comment by yikengboy** [comment]
ok thanks, I get it.
by the way, 
![image](https://github.com/GumTreeDiff/gumtree/assets/76463236/894e8fe5-bc9e-4e1f-9532-94fdd3421eb6)
What do the numbers in this range represent?

**Comment by jrfaller** [comment]
Start and end under character indexes of the node.
