### ISSUE TITLE
use gumtree diff two commit edit script

### ISSUE THREAD

**Issue by yikengboy** [GumTreeDiff/gumtree#353]
https://github.com/GumTreeDiff/gumtree/wiki/VCS-Integration#git-integration, I look up this reference
And can I use gumtree diff  edit script through two commitid?

**Comment by jrfaller** [comment]
Yes like you normally would with git diff!

**Comment by yikengboy** [comment]
I entered the container through `docker run --entrypoint "/bin/bash" -it gumtreediff/gumtree`, and executing the `git difftool -x gumtree webdiff --d` command seemed to have no effect. 
`
![image](https://github.com/GumTreeDiff/gumtree/assets/76463236/9e592539-4ceb-4cc1-9ae8-ff1b46110341)
`
Is there something wrong somewhere?
