### ISSUE TITLE
What is the difference between monaco, classic, monaco-native?

### ISSUE THREAD

**Issue by ty-bnn** [GumTreeDiff/gumtree#357]
Hello.
I just want to know the difference between monaco, classic and monaco-native in viewer.
Are these three viewers using different diff algorithms?

![image](https://github.com/GumTreeDiff/gumtree/assets/69183967/76f29899-c10f-4dda-bc55-c61b191d56c4)

**Comment by jrfaller** [comment]
Hi! Monaco and classic are ast diffs with a different html backend. Monaca-native is a text diff. Cheers!

**Comment by jrfaller** [comment]
> Thank you for your response!
> Do you mean the difference between monaco and classic is just UI and they are using same gumtree algorithm, right?
> I am a little bit confusing because of your new release about gumtree algorithm in ICSE 2024.
> Thanks!

Yes you're right! And the same command line parameters to change the algorithm / parser apply to both UIs. Cheers!
