### ISSUE TITLE
Why source deletion is shown for this js Source file ?

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#36]
![screen shot 2016-09-13 at 3 46 00 pm](https://cloud.githubusercontent.com/assets/7368670/18472571/570e970a-79c9-11e6-976a-6f49d8e73f64.png)

Why is the first line `this.getWebProxiesList = function (callback) {` is being shown as deletion in the left file , when there is no change (in addition to other deletions)

**Comment by jrfaller** [comment]
Can you attach the two files ?

**Comment by irajdeep** [comment]
Sure 
[left.js.zip](https://github.com/GumTreeDiff/gumtree/files/471861/left.js.zip)
[right.js.zip](https://github.com/GumTreeDiff/gumtree/files/471862/right.js.zip)

**Comment by jrfaller** [comment]
Ok same result here,

What's going on is that there are two many differences so GumTree do not recognize the function definition has being the same, therefore evertyhing seem to be moved even if it's not really the case.

There are some options that can make it better, with the following config it's way more accurate (pass to VM options): `-Dgumtree.match.bu.sim=0.7`

Of course it should be documented somewhere ;)

**Comment by irajdeep** [comment]
Can I pass this to the gumtree command , something like
`./gumtree webdiff left.js right.js -Dgumtree.match.bu.sim=0.7` (because it's not working like this :) ) or should I add it somewhere else ?

**Comment by jrfaller** [comment]
Good question, I will ask it to floreal.

**Comment by irajdeep** [comment]
Sure

**Comment by morandat** [comment]
I have no clue of who did this script (maybe gradle) but it has no chance to work like this.
You can try (let me know which one are working):
./gumtree -Dgumtree.match.bu.sim=0.7 webdiff left.js right.js
JAVA_OPTS="-Dgumtree.match.bu.sim=0.7" ./gumtree webdiff left.js right.js
or (but I'm not sure we have implemented it)
./gumtree "-c match.bu.sim=0.7" webdiff left.js right.js

If none work I'll try it tomorow

**Comment by irajdeep** [comment]
The second command 
`JAVA_OPTS="-Dgumtree.match.bu.sim=0.7" ./gumtree webdiff left.js right.js` worked.
Thanks

**Comment by irajdeep** [comment]
umm , at instances I am finding the `JAVA_OPTS="-Dgumtree.match.bu.sim=0.7"` flag is showing more differences than there actually are in the source files . Can someone explain why it might be ?

**Comment by jrfaller** [comment]
It's not a flag it's a threshold. If you want to know more, you can read our ASE paper where it is described.
