### ISSUE TITLE
Go language parsing

### ISSUE THREAD

**Issue by lyoubo** [GumTreeDiff/gumtree#375]
When I use the latest version of gumtree (v4.0.0-beta3), parsing go language files still throws a ClassCastException. Can you try to fix this and at least get GumTree working properly?

![exception](https://github.com/user-attachments/assets/3e8f57af-38b9-4b67-9802-8a73cb72ac0d)

**Comment by jrfaller** [comment]
Thanks for the reminder. Normally this is resolved.

**Comment by lyoubo** [comment]
> Thanks for the reminder. Normally this is resolved.

Is it possible to release a fixed maven version? I want to use GumTree as a maven dependency.
