### ISSUE TITLE
JAVA Comment change not getting detected

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#39]
![screen shot 2016-09-20 at 11 19 28 pm](https://cloud.githubusercontent.com/assets/7368670/18685356/be58fb2a-7f88-11e6-9a59-368e7a75bcfb.png)

**Comment by morandat** [comment]
Indeed they are not detected since comments are stripped out during parsing. Comments are not a structural/semantic change. Since now people are using Gumtree more and more as a daily usage tool, we should definitely consider them at least up to some point.

**Comment by irajdeep** [comment]
Yeah that would be a great help detecting comment changes.

**Comment by jrfaller** [comment]
This is clearly annoying, but it will be hard to fix because comments are not visited by the JDT visitor: [see here](http://www.programcreek.com/2013/03/get-internal-comments-by-using-eclipse-jdt-astparser/). It must be done manually but then it will be hard to know where to put them in the already generated AST

**Comment by pranet** [comment]
Hi. I am working with gumtree, and I came across this issue too. Is there any scope of this being fixed?
(I have worked with JDT before and was able to solve the problem of finding where to attach the comments nodes to the AST later.)

**Comment by jrfaller** [comment]
Hi pranet, nobody's working on it at the moment, so if you want to take a shot, you're more than welcome!

**Comment by jrfaller** [comment]
OK this there are no news on this subject, and since it does not seems that Java comment are going to change in JDT, we drop this for the moment. Please reopen if new information comes up.
