### ISSUE TITLE
C# Detailed Source Code change

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#40]
Ran GumTree on the following two source files 

[left.cs.zip](https://github.com/GumTreeDiff/gumtree/files/550363/left.cs.zip)
[right.cs.zip](https://github.com/GumTreeDiff/gumtree/files/550364/right.cs.zip)

Got the following output.
<img width="1275" alt="screen shot 2016-10-25 at 4 19 06 pm" src="https://cloud.githubusercontent.com/assets/7368670/19683172/c9f98290-9ace-11e6-85fd-7a9249d15cfe.png">

As one can see there is "Comment Change" (deletion) and "Condition Change" (deletion),GumTree labels both of them as "function/block". To my knowledge GumTree uses srcML for generating AST for C# , and I do see tags line "comment" , "condition" in their  [documentation](http://www.srcml.org/doc/cs_srcML.html) . Is it possible to show the changes in more details ?

**Comment by jrfaller** [comment]
Hi!

You can try with swingdiff which gives more details, you also have jsondiff to get all the actions.
