### ISSUE TITLE
Getting method and class in which a code change has occurred 

### ISSUE THREAD

**Issue by irajdeep** [GumTreeDiff/gumtree#42]
Hi all , I am trying to access the method name and the class name in which a code change has occurred (from left version to the right version).
Can someone give me an idea as how I can achieve this ?
Thanks

**Comment by jrfaller** [comment]
You can search for the first ancestor of type TypeDeclaration and look its SimpleName child, would it answer your question?

**Comment by jrfaller** [comment]
You need to have at hand the ITree corresponding to the file

Then simply go through the ancestors (getParents if I remember correctly) until you find a MethodDeclaration and a TypeDeclaration, and look for the direct SimpleName child of these nodes.

**Comment by irajdeep** [comment]
Thanks a lot , I will have a look

**Comment by morandat** [comment]
Note that if they are nested/anonymous classes and method you have to continue traversal and compose them in reverse order.

—F

**Comment by irajdeep** [comment]
Yeah figured it out , Thanks.
BTW will it be useful to show the classes and methods which have changes in the "listdiff" ? If yes I can work on it and send a corresponding PR.

**Comment by morandat** [comment]
IMO it seems hard to do something that may work for any language. The only way I can think about that is to provide a list of interesting points (class/methods for instance), and provide this list alongside every parser.  Maybe you or JR has a better idea.

**Comment by irajdeep** [comment]
I was thinking of providing something like classes and methods that have changed in a file (for it will be only JAVA file) from left to right version .

**Comment by jrfaller** [comment]
Maybe this would be best done via a dedicated client tailored for the analysis of a specific language?

**Comment by irajdeep** [comment]
Makes sense. I will list down a few parameters that we can output using GumTree for JAVA code change analysis and get it reviewed.
I can start working on the client thereafter.
