### ISSUE TITLE
Type Binding, Dependencies, and Line Binding

### ISSUE THREAD

**Issue by loren138** [GumTreeDiff/gumtree#43]
Hi,

Does gumtree bind types for an object in the AST?  If so, what is the correct way to load dependencies for it to bind to?

Is there a way to get from a node in the AST to the line in the source file?  I'm assuming there must be for IDEs to implement clicking on items.

Also, was there a particular reason you chose Eclipe's parser for Java over JavaParser (https://github.com/javaparser/javaparser)?

**Comment by jrfaller** [comment]
Hi!

I am not sure what you mean by "bind types", can you explain it a little further

To find nodes according to lines, you can use the getPos and getEndPos method on trees.

We used JDT because we were familiar with it, but you can integrate JavaParser as well because GumTree is modular in this aspect.

**Comment by loren138** [comment]
I think what I'm referring to is resolve bindings in JDT.
http://www.programcreek.com/2014/01/how-to-resolve-bindings-when-using-eclipse-jdt-astparser/

I couldn't tell if gumtree takes variable types into account when resolving differences.

IE:
 - Creating String someVar vs Object someVar
 - Calling a function with someVar (as a String vs as something else).

**Comment by jrfaller** [comment]
Hi Loren,

In this case I think the answer is that you cannot resolve binding from GumTree's nodes. However it is possible to do it because nodes have metadata associated to them so you can modify the jdt based parser to inject the binding objects into the node.
