### ISSUE TITLE
getting started

### ISSUE THREAD

**Issue by JuliaLawall** [GumTreeDiff/gumtree#44]
For a non Java person, the getting started web page is quite unhelpful.

"You will have a tar.gz distribution of GumTree in the dist/build/distributions folder."
Actually I got a .zip file.

"This server is accessible via the URL http://localhost:4754/."
Actually, I got http://127.0.0.1:4567

"java fr.labri.gumtree.client.Run webdiff file1.java file2.java"
This command doesn't work at all.  It says "Error: Could not find or load main class fr.labri.gumtree.client.Run".

"You can check out the help of this class to discover the main commands."
I have no idea how to check out the help of a Java class.  Running gumtree-20170215-2.1.0-SNAPSHOT/bin/gumtree --help did not really give any useful information.  It seems that more information is available if one actually gives an invalid command.

Is there any way to get output that contains only the differences?

thanks,
julia

**Comment by jrfaller** [comment]
Thanks for the comments Julia, I updated the help to fix the problems you discovered.

For the error, I think it's because the classpath is not set-up correctly, it needs to include the *.class of all gumtree's modules.

You can have the output with only the differences in a textual format for instance by using the  jsondiff command, try it to see if it suits your requirements.

**Comment by JuliaLawall** [comment]
On Wed, 15 Feb 2017, Jean-Rémy Falleri wrote:

>
> Thanks for the comments Julia, I updated the help to fix the problems you
> discovered.
>
> For the error, I think it's because the classpath is not set-up correctly,
> it needs to include the *.class of all gumtree's modules.
>
> You can have the output with only the differences in a textual format for
> instance by using the jsondiff command, try it to see if it suits your
> requirements.

Thanks!  Indeed, I tried some other options, but not that one :)

julia

**Comment by leusonmario** [comment]
I have a similar problem. Even setting up all dependencies, when I try to run the project, it always returns the same 'available commands.' 
Even for this limited list, if I request to use the 'parse' command, for example, 'No generator found for file' could be identified.

It would be nice if the "Getting Started" page could provide solutions or insights of how to deal with problems.
