### ISSUE TITLE
Strange diff output for C++

### ISSUE THREAD

**Issue by krobelus** [GumTreeDiff/gumtree#48]
I get a strange output when using gumtree diff on these input files. The output from gumtree jsondiff seems normal, so this is most likely a bug. Note that I didn't minimize the test example, so it could be smaller.

I'm using commit 786aa9fa807411b2ea4f9fcb6f2b6dc48f5f6138

left.cpp
```
class Foo {
  void bar() { ; }
};
```

right.cpp
```
class Foo {
  void bar() {
    if (1) {
      ;
    }
  }
};
```

`$ gumtree diff left.cpp right.cpp`
yields
```
Insert block(12) into function(13) at 3
Insert 3357(11) into block(12) at 0
Insert -861311717(7) into 3357(11) at 0
Insert 3558941(10) into 3357(11) at 1
Insert 3127797(6) into -861311717(7) at 0
Insert block(9) into 3558941(10) at 0
Insert 182460591: 1(5) into 3127797(6) at 0
Move empty_stmt(5) into block(9) at 0
Delete block(6)
```

**Comment by jrfaller** [comment]
Hi and thanks for trying out GumTree!

The strange thing in this diff is the lines such as `Insert -861311717(7) into 3357(11) at 0` right?

**Comment by krobelus** [comment]
yes, the output from `gumtree jsondiff` does not include huge numbers

**Comment by jrfaller** [comment]
I will investigate, thanks for noticing the problem!

**Comment by UlrichThomasGabor** [comment]
There are other problems as well in the C++ variant. For example given a change from
```
int main(int argc, char** argv) {
	int a = 5;

	a = argc;

	return a;
}
```
to
```
int main(int argc, char** argv) {
	int a = 6;

	a = argc;

	return a;
}
```
the changes are detected correctly, but it seems the positions are wrong, thus the webdiff view is showing weird results.

**Comment by jrfaller** [comment]
This have been fixed thanks to a pull request. However there might be some other clients that are affected in addition to the webdiff one.
