### ISSUE TITLE
Maven repository update

### ISSUE THREAD

**Issue by csiki** [GumTreeDiff/gumtree#51]
I've been using gumtreediff to generate Abstract Syntax Tree of JavaScript code. Now I'm exporting my project to Maven, but it seems the version you have uploaded there is not up to date (almost 2 years old) - https://mvnrepository.com/artifact/com.github.gumtreediff.
Could you please update the maven repo? Thanks!

**Comment by jrfaller** [comment]
Hi!

You're right the Maven version is pretty old, we did not update it since we move from Maven to Gradle.

I will try to refresh it.

**Comment by jrfaller** [comment]
Done! Fresh version 2.1.0 has been posted to maven central.

**Comment by Symbolk** [comment]
Hi Jrfaller, how to delpoy the latest jar compiled by develop branch to the local maven repo? @jrfaller
