### ISSUE TITLE
how to get mappings between TreeNode and Source file??

### ISSUE THREAD

**Issue by happyhappiness** [GumTreeDiff/gumtree#52]
My goal is to find matching line number of old file in new file. However, I go through the code base and read the apis, I fail to figure out any clue about source file location info. Can you be so nice to give me some recommendation ?

**Comment by jrfaller** [comment]
You have the getPos and getEndPos method in the ITree interface. This position is in absolute number of characters. If you need related line and column, you have a dedicated Reader for that in the utils package: LineNumberReader.

**Comment by happyhappiness** [comment]
thank you for your help * . *
