### ISSUE TITLE
Alternative XML Representations

### ISSUE THREAD

**Issue by indolering** [GumTreeDiff/gumtree#59]
Your paper noted some major performance issues WRT memory.  Have you considered using [VTD-XML](https://en.wikipedia.org/wiki/VTD-XML) or [binary XML](https://en.wikipedia.org/wiki/Efficient_XML_Interchange)?

**Comment by jrfaller** [comment]
Hi!

Most of the time the tree generators use in-memory data objects coming from Java parsers, therefore I am not sure that for this issue binary XML can be a solution.

**Comment by indolering** [comment]
The paper mentioned XML being a cause of memory bloat, VTD-XML actually stores everything as an offset and takes up a lot less space in memory.  Binary XML would at least reduce the IO bandwidth needed to move things from the cache....

Maybe this is only a problem when doing large-scale analysis?

**Comment by jrfaller** [comment]
Hi!

Currently, there is no caching in GumTree, but yes it would help in case of large scale analysis
