### ISSUE TITLE
org.reflections.Reflections dependency uses practically restrictive license

### ISSUE THREAD

**Issue by CaptainEmerson** [GumTreeDiff/gumtree#60]
gumtree.client depends on org.reflections.Reflections, which has been ambiguously licensed: https://github.com/ronmamo/reflections/issues/159. Companies can't use reflections (and arguably neither should other software), and consequently, companies can't use gumtree either. 

The dependency on gumtree appears in [one file](https://github.com/GumTreeDiff/gumtree/blob/3b563126ddd21265ea09f0a45e31342cfa0ea283/client/src/main/java/com/github/gumtreediff/client/Run.java#L26), so I'd guess it wouldn't be too much work to remove this dependency.

**Comment by morandat** [comment]
Reflections is used for registry. It may be replaced by a combination of classindex and ???. Others alternatives are so slow. Maybe something ad-hoc. I'll have a look this end of week.

**Comment by jrfaller** [comment]
ok reflections have been dropped in favor of classindex in last commit.
