### ISSUE TITLE
SiblingsMappingComparator

### ISSUE THREAD

**Issue by krobelus** [GumTreeDiff/gumtree#62]
I am probably mistaken here, but isn't the `siblingsJaccardSimilarity` always 0?

https://github.com/GumTreeDiff/gumtree/blob/develop/core/src/main/java/com/github/gumtreediff/matchers/heuristic/gt/SiblingsMappingComparator.java#L41

When used from GreedySubtreeMatcher, only unambiguous mappings are added (recursively) to `mappings`, therefore no descendant of a node with an ambiguous mapping is mapped.

Am I missing something?

**Comment by jrfaller** [comment]
Yes I believe you are mistaking ;). The similarity function is not applied on the nodes themselves, but on their parent (which by construction have not been ambiguously or unambiguously mapped).
