### ISSUE TITLE
Command: gumtree.bat parse "the attached file" never returns...

### ISSUE THREAD

**Issue by jawilliam** [GumTreeDiff/gumtree#67]
[OriginalAbstractBoardGame.zip](https://github.com/GumTreeDiff/gumtree/files/1236449/OriginalAbstractBoardGame.zip)

**Comment by jrfaller** [comment]
Hi!

It seems that you are right, but it seems to be due to a problem in our cs underying parser, srcML, (command srcml on your file does not return as well...). I recommend you to get in touch with srcML's authors since we are not familiar with its code...

**Comment by jawilliam** [comment]
In the mean time, there is a chance to enable GumTree based on Roslyn? I have been researching GumTree hard. In my opinion, there are some oddities of your algorithm in C# because srcml does not discriminate well incompatible constructions. For example, there are matches beween "this" or "base" instance expressions and variable names. Many times this is not the desired. Besides, Roslyn supports a domain more updated. C# 7.0 is not fully supported in srcml.

If you need, I can help to port the parsing from srcml to Roslyn.

**Comment by jrfaller** [comment]
Yes it would be really nice, I know that srcML primary focus is not to be a C# parser, so it is always better to integrate a real, actively maintained parser. However I am not familiar with Roslyn and I prefer to focus on maintaining GumTree's core, therefore I will not doing it myself. If you are willing to work on this, please do 👍 I will do my best to help you.
