### ISSUE TITLE
The resulting actions do not transform the original documento into the modified one

### ISSUE THREAD

**Issue by jawilliam** [GumTreeDiff/gumtree#68]
Hi,

I think this could be an implementation error. Focus the attention on the actions affecting the "Decode" method. They do not transform well the original source code into its modified version. The statement 

"result = Regex.Replace(result, "&amp;", "&", RegexOptions.IgnoreCase);" (line 106 in the original and 105 in the modified)

was deleted, but it was never recovered again (e.g., reinserted)

[Analysis.zip](https://github.com/GumTreeDiff/gumtree/files/1243254/Analysis.zip)

**Comment by jrfaller** [comment]
Hi and thanks for the feedback!

This issue comme from the fact that XML produced by srcML (that does parsing for C#) is not correctly parsed by GumTree when threre are special characters/ I will try to see how can I deal with the problem.

**Comment by jrfaller** [comment]
OK normally this have been fixed. It seems that there are still some problems concerning the location of the tokens in the text file though...
