### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by leusonmario** [GumTreeDiff/gumtree#69]
I cannot run the project since environment configuration problems have happened. Even setting up all dependencies, when I try to run the project, it always returns the same 'available commands.'
Even for this limited list, if I request to use the 'parse' command, for example, 'No generator found for file' could be identified.

It would be nice if the "Getting Started" page could provide solutions or insights of how to deal with problems.

**Comment by jrfaller** [comment]
Hi and thanks for your feedback.

Could you be more precise about the issues you ran over with?

Cheers.

**Comment by leusonmario** [comment]
Thanks for your reply.

So... When I run the project with or without the required dependencies, I always have the same message:

> ** No command given.
> Available Options:
> -c <2>	Set global property (-c property value). Properties do not need to be prefixed by gumtree.
> -v	Verbose mode
> --help	Display help (this screen)
>
> Available Commands:
> * list: List things (matchers, generators, properties, ...)
> * parse: Parse file and dump result
> 

According to [Getting Started page](https://github.com/GumTreeDiff/gumtree/wiki/Getting-Started) after adding the dependencies, all commands and parsers should be available.

Adding the dependencies and running the Run class with the command `webdiff f<fileNameOne>.java <fileNameTwo>.java`, I got:

> ** Unknown sub-command 'webdiff'.

**Comment by jrfaller** [comment]
Can you tell me how you installed GumTree?

**Comment by leusonmario** [comment]
I basically used Eclipse for configuring the project.
The project was imported as Github Repository. All projects worked well except 'benchmark'. Thus, I added a new dependency on its gradle file `compile group: 'org.openjdk.jmh', name: 'jmh-core', version: '1.19'`

Since all projects were configured and built correctly, I run the Run class with and without the dependencies introduced on the project classpath.

Adding all projects to the classpath, I got the following message.

> Exception in thread "main" java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException
>	at java.lang.Class.getDeclaredConstructors0(Native Method)
>	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
>	at java.lang.Class.getConstructor0(Class.java:3075)
>	at java.lang.Class.getConstructor(Class.java:1825)
>	at com.github.gumtreediff.gen.Registry.defaultFactory(Registry.java:129)
>	at com.github.gumtreediff.gen.Generators.newEntry(Generators.java:55)
>	at com.github.gumtreediff.gen.Generators.newEntry(Generators.java:1)
>	at com.github.gumtreediff.gen.Registry.install(Registry.java:74)
>	at com.github.gumtreediff.client.Run.lambda$0(Run.java:63)
>	at java.lang.Iterable.forEach(Iterable.java:75)
>	at com.github.gumtreediff.client.Run.initGenerators(Run.java:58)
>	at com.github.gumtreediff.client.Run.<clinit>(Run.java:80)
> Caused by: java.lang.ClassNotFoundException: org.antlr.runtime.RecognitionException
>	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
>	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
>	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
>	... 12 more

**Comment by leusonmario** [comment]
It was an issue with eclipse version.
I'll close this issue.

**Comment by Symbolk** [comment]
Have you tried IDEA? The same problem comes to me in IDEA so I wonder what you did to resolve it.
Thanks! @leusonmario

**Comment by Symbolk** [comment]
@leusonmario One solution is provided in #88, it seems the problem with ClassIndex, which replaces Reflections to scan all the generators.
