### ISSUE TITLE
Support TextMate Syntax Definition Format

### ISSUE THREAD

**Issue by indolering** [GumTreeDiff/gumtree#70]
[TextMate language definitions](https://manual.macromates.com/en/language_grammars) is probably the most common syntax description format out there (it's used by SublimeText, Atom, etc).  These aren't as complete as a ANTLR descriptions, but they are at least up-to-date.

**Comment by jrfaller** [comment]
Hi and thanks for pointing this out!

Is there any kind of tooling that allows converting these files into concrete parsers that produces a tree out of a text file?

**Comment by indolering** [comment]
> Is there any kind of tooling that allows converting these files into concrete parsers that produces a tree out of a text file?

_Pulls himself out of a rabbit hole._  Probably.

**Comment by jrfaller** [comment]
I looked quite a bit inside textmate tooling, but I did not see any tool that transforms the grammar into a parser :(
