### ISSUE TITLE
"The input line is too long." error on Windows 7 when trying to run built gumtree.bat

### ISSUE THREAD

**Issue by yeputons** [GumTreeDiff/gumtree#72]
I followed instructions from [here](https://github.com/GumTreeDiff/gumtree/wiki/Getting-Started), got `gumtree-20171214-2.1.0-SNAPSHOT.zip ` built, unzipped it in a folder and tried to run `gumtree.bat` without any arguments. That was the output:

```
The input line is too long.
The syntax of the command is incorrect.
```

While I was expecting to get some kind of a message from `gumtree` (e.g. help).

I believe that happens because of [Gradle issue 1989](https://github.com/gradle/gradle/issues/1989) - it basically appends all libraries used as a command line argument, which the maximal length of a command line in Windows is [capped by 8191](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd--exe-command-line-string-limitation).

**Comment by yeputons** [comment]
Workaround 1: unzip everything into a folder with a shorter absolute path, e.g. `C:\Soft\gumtree` and run script from `C:\Soft\gumtree\bin\gumtree.bat`

Workaround 2: if you know for sure that you'll run `gumtree.bat`  once or twice while `bin` is the current directory only, then you can change line 14 of `gumtree.bat` from `set APP_HOME=%DIRNAME%..` to `set APP_HOME=..`

**Comment by jrfaller** [comment]
Hi!

Anyone knows if it still happens using current Gradle version (5.2.1)?

Cheers.

**Comment by yeputons** [comment]
@jrfaller At the very least, `gumtree.bat` in `gumtree.zip` v2.1.2 download from [Release](https://github.com/GumTreeDiff/gumtree/releases/download/v2.1.2/gumtree.zip)  still suffers from "The input line is too long.". Haven't checked building from sources. The problem is still line 66 of the script which adds lots of stuff to `CLASSPATH` by absolute path and exceeds maximal command line length for Windows. I suspect it's tracked in https://github.com/gradle/gradle/issues/1989

**Comment by jrfaller** [comment]
OK thanks for the update on the status!

I hope they'll find a fix someday ;)

**Comment by jrfaller** [comment]
Just to confirm,

Can someone on Windows can confirm that our new shadow jar based distribution solves this problem ?

**Comment by yeputons** [comment]
@jrfaller I've just downloaded `gumtree-3.0.0-beta1.zip` from [the releases page](https://github.com/GumTreeDiff/gumtree/releases) and `gumtree.bat webdiff A.java B.java` worked for me from a directory with a pretty long path.

Same actions with v2.1.2 failed as reported originally.

So, yes, I think it fixes the problem.

**Comment by jrfaller** [comment]
Awesome!!! Thanks for taking the time to test!
