### ISSUE TITLE
node name

### ISSUE THREAD

**Issue by spyyes** [GumTreeDiff/gumtree#76]
Hello, could you please show me where I can get a node's name?
I mean, with jdt, I can use _getName()_ to get my method name, e.g.  _"((MethodDeclaration) m).getName()"_.
But how to get it with gumtree?

Thank you very much. I'm waiting for your reply anxiously.

**Comment by jrfaller** [comment]
Hi!

If I remember correctly, the first child of a MethodDeclaration is a SimpleName with value is the name of the method.
