### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder" on webdiff

### ISSUE THREAD

**Issue by HalleyYoung** [GumTreeDiff/gumtree#77]
I am unable to run webdiff from the binary, getting the following error:

>./gumtree webdiff tmp1.java tmp2.java

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

slf4j-api-1.7.25.jar and slf4j-simple-1.7.25.jar are in the lib folder, so I don't know what's going wrong.

Thanks!

**Comment by jrfaller** [comment]
OK this is not a real failure, just a debug message from slf4j which does not prevent GumTree to run, just click on the link furnished after. Anyway, I will fix it.
