### ISSUE TITLE
copy&paste error?

### ISSUE THREAD

**Issue by husttroy** [GumTreeDiff/gumtree#78]
In RootAndLeavesClassifier.java, the `fSrcMvTrees` variable is initialized but never used. 

Check this https://github.com/GumTreeDiff/gumtree/blob/29301b7c34c9486d88928c3bc0210fc2e1e51534/core/src/main/java/com/github/gumtreediff/actions/RootAndLeavesClassifier.java#L77-L82

**Comment by jrfaller** [comment]
Hi!

Sure this line is doing nothing, probably comes from a bad refactoring. Will remove it.

Cheers.

**Comment by husttroy** [comment]
Simply removing this line of code may not be the right thing to do. This class is to merge small diffs with the enclosing ones. For example, the following statements merge deleted code in the source tree.

https://github.com/GumTreeDiff/gumtree/blob/29301b7c34c9486d88928c3bc0210fc2e1e51534/core/src/main/java/com/github/gumtreediff/actions/RootAndLeavesClassifier.java#L70-L75

I think you should do the same thing for other types of diffs, e.g., move and update.

**Comment by jrfaller** [comment]
Hi!
Move operation is already performed at the level of maximum subtrees (whole subtree rooted at a node is moved when node is moved), in contrast with insert or delete which only apply to one node (and therefore can be tedious to represent when whole subtrees are added/deleted).

Normally there is nothing to do for moved trees.

By looking closely, I realize that there is a loop performed twice for no reason 😠 I will remove it as well.

**Comment by husttroy** [comment]
Aha, now I understand. Thanks!
