### ISSUE TITLE
How to set matcher's options from command line?

### ISSUE THREAD

**Issue by coder-chenzhi** [GumTreeDiff/gumtree#79]
I have built GumTreeDiff and run the 'gumtree' under 'dist' subproject. The complete command I used as follows.
```
./gumtree webdiff file1 file2
```
But the result with default parameter seems too fine-grained. So I want to change the matcher's options to tuning the result. Unfortunately, I don't figure out how to set the matcher's options from command line. 
Can you give me any hints?
Thanks!

**Comment by jrfaller** [comment]
Hi!

gumtree -c property_name value

It would be cool to have a summary page in the wiki with all property name, I will try to add it when I have time.

**Comment by jrfaller** [comment]
OK Done!

https://github.com/GumTreeDiff/gumtree/wiki/Parameters

Cheers!
