### ISSUE TITLE
Verbosity control

### ISSUE THREAD

**Issue by MichaelHilton** [GumTreeDiff/gumtree#8]
When running Gumtree, there should be a way to avoid having it send its output to standard out.
This is an issue when running it as a library as then the output must be filtered out of standard out

**Comment by jrfaller** [comment]
This has been done, normally on the tree_info branch nothing outputs on standard output except the web diff client to output the URL.
However, all errors are printed on the standard error.
Is this the behavior you expect?

**Comment by MichaelHilton** [comment]
That sounds great to me!
