### ISSUE TITLE
How to compare two Java Files and get the Diffs

### ISSUE THREAD

**Issue by digeo** [GumTreeDiff/gumtree#80]
Hello,
I have two revisions of one Java file (i.e. FilenameUtilsv0.java and FilenameUtilsv1.java) and I would like to use the gumtree in order to get the diffs between these two file (modifications, additions, deletions).
Could you please help by providing me a snippet?
Thank you in advance!

**Comment by jrfaller** [comment]
For instance

`gumtree jsondiff FilenameUtilsv0.java FilenameUtilsv1.java`

if you type in the `gumtree` command you will have the list of the possible options.

Best regards.

**Comment by digeo** [comment]
@jrfaller First of all, thank you very much for your response.
Actually, I would like to implement one java program that uses the gumtree, so I am wondering what is the proper way to load/read the two files, feed them to gumtree and get the diffs.
Thank you in advance!

**Comment by jrfaller** [comment]
Maybe something like that : https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API ?

**Comment by digeo** [comment]
Thank you very much @jrfaller that is what I was looking for!

**Comment by shreyjasuja** [comment]
Can you elaborate more on how to set up the environment for using GumTreeAPI

**Comment by jrfaller** [comment]
You can look into our Docker file @shreyjasuja.
