### ISSUE TITLE
Failed to run docker version on Linux and macOS

### ISSUE THREAD

**Issue by XBWer** [GumTreeDiff/gumtree#83]
Hi authors,

I try to run the docker version of gumtree but failed.

Here is the log of [Linux](https://drive.google.com/open?id=1J7Z0NRkh6djh_8zHeeZHQAJOjiLHWlDh) and [macOS](https://drive.google.com/open?id=1AD43vXkegBnvyXzlIfl-nzxkHnewj2s2). As you can see, I ran the same command but get different results.

Any suggestions? Please kindly advise.

Thanks!

**Comment by jrfaller** [comment]
Regarding the linux build it seems to be coming from not enough space on the computer doing the build, for mac os I see a Runtime Exception going on, but I have to try and reproduce the error

**Comment by jrfaller** [comment]
I have tried to build the docker image on latest mac os x and it works.
