### ISSUE TITLE
Figure out what exactly has changed between two Java files

### ISSUE THREAD

**Issue by digeo** [GumTreeDiff/gumtree#85]
Hello,

I have two revisions of the same Java file and I would like to figure out which parts of this file have been moved, updated, added.
So far I have written the following code:

```
TreeContext src = Generators.getInstance().getTree(srcFile);
TreeContext dst = Generators.getInstance().getTree(dstFile);
Matcher matcher = Matchers.getInstance().getMatcher(src.getRoot(), dst.getRoot());

ActionGenerator g = new ActionGenerator(src.getRoot(), dst.getRoot(), matcher.getMappings());
g.generate();
```

Could you please suggest me what should I do next?
Thank you in advance!

**Comment by jrfaller** [comment]
Hi!

Take a look at our dedicated wiki page :  https://github.com/GumTreeDiff/gumtree/wiki/GumTree-API
