### ISSUE TITLE
Unable to get the same "Available Commands" from source code  as from the release bin

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#88]
Hi, I was happy with the gumtreediff release v2.1.1, especially the "" it provides:
```sh
$ gumtree
** No command given.
Available Options:
-c <2>  Set global property (-c property value). Properties do not need
 prefixed by gumtree.
-v      Verbose mode
--help  Display help (this screen)

Available Commands:
* webdiff: a web diff client
* cluster: Extract action clusters
* diff: Dump actions in our textual format
* jsondiff: Dump actions in the JSON format
* list: List things (matchers, generators, properties, ...)
* parse: Parse file and dump result
* swingdiff: A swing diff client
* axmldiff: Dump annotated xml tree
```
However, when I want to run it from the source code by running Run.java without paramters, it outputs:
```sh
** No command given.
Available Options:
-c <2>	Set global property (-c property value). Properties do not need to be prefixed by gumtree.
-v	Verbose mode
--help	Display help (this screen)

Available Commands:
* list: List things (matchers, generators, properties, ...)
* parse: Parse file and dump result
```
The output is same for all available versions: the release v2.1.1 source code, the master branch, and the develop branch. I guess it has something to do with the initClients() in Run.java. When I pass the same command "webdiff base.java ours.java " to the main() in Run.java, it says:
```sh
** Unknown sub-command 'webdiff'.
Available Options:
-c <2>	Set global property (-c property value). Properties do not need to be prefixed by gumtree.
-v	Verbose mode
--help	Display help (this screen)

Available Commands:
* list: List things (matchers, generators, properties, ...)
* parse: Parse file and dump result
```
(BTW, I have built the source code with "gradlew build -x test" successfully.)

**Comment by Symbolk** [comment]
Thanks for the reply. 
I can build the zip, extract it, and run the binary in bin folder. But I am developing inside IDEA, so I wonder if I can run it directly from source code in IDEA and call available commands.

**Comment by jrfaller** [comment]
Hi!

It means that gumtree is not "seeing" the plugins, normally it was fixed by using the same class path as the dist gradle module when running a program for IDEAJ but it seems to be broken since we removed Reflections API and replaced it by ClassIndex for plugin management. Can you confirm this?

Regards.

**Comment by jrfaller** [comment]
Nice!

Quick question : you have to unzip the distribution zip first hand?

**Comment by coder-chenzhi** [comment]
Yes, I unzip the distribution zip manually.

**Comment by jrfaller** [comment]
Mmm ok this is might be a bit tedious to do to quickly test something after a modification. I will look if I can find a better method.

**Comment by Symbolk** [comment]
Yeah, it works for me, though being not elegant.

Thanks to all~

**Comment by TalentSSS** [comment]
Hi!

I'm new to GumTree and meet same trouble @Symbolk

In IDEA 2020.3.1, I added the `lib` directory from zip distribution of gumtree to classpath (unzip gumtree-3.0.0-SNAPSHOT.zip)

![image](https://user-images.githubusercontent.com/13519606/116645842-40672200-a9a9-11eb-98db-35d69a3f54c3.png)


But when I run the `client:Run.main()`，I still got only two available commands

![image](https://user-images.githubusercontent.com/13519606/116645863-49f08a00-a9a9-11eb-82cf-c558430b2a3a.png)


Did I miss any step or some new solution about it ?

**Comment by Symbolk** [comment]
Hi, @TalentSSS Did you try reload Gradle projects?

**Comment by TalentSSS** [comment]
> Hi, @TalentSSS Did you try reload Gradle projects?

You mean reload the whole project ? 

Yes, but the `gumtree.jar` get lost after reload it, which seems reasonable according to this warning

![image](https://user-images.githubusercontent.com/13519606/116651634-34ce2800-a9b6-11eb-8b32-19af1b8efb68.png)

So I tried to rebuild `gemtree:client` module by the task here

![image](https://user-images.githubusercontent.com/13519606/116651796-8b3b6680-a9b6-11eb-9a43-a8f42f312387.png)

Still not working, only `list` and `parse` available T.T

**Comment by Symbolk** [comment]
@TalentSSS Use the button here:
![image](https://user-images.githubusercontent.com/14107297/116652591-18cb8600-a9b8-11eb-8c2f-914159d8c0e4.png)

And before I proposed a workaround in a PR: https://github.com/GumTreeDiff/gumtree/pull/205, also remember to reload when you try it.

**Comment by TalentSSS** [comment]
> @TalentSSS Use the button here:
> ![image](https://user-images.githubusercontent.com/14107297/116652591-18cb8600-a9b8-11eb-8c2f-914159d8c0e4.png)
> 
> And before I proposed a workaround in a PR: #205, also remember to reload when you try it.

I have already done that, and still not working like I said before.

And I'm trying to figure out how commands to be loaded ... 

![image](https://user-images.githubusercontent.com/13519606/116657013-49afb900-a9c0-11eb-99b5-2b42ad65be0e.png)

It seems that command `WebDiff` was failed to load, and only the subclasses of `Client` in module `gumtree:client` success.

![image](https://user-images.githubusercontent.com/13519606/116657610-4d900b00-a9c1-11eb-8d57-cc3e4ff5aee4.png)

Any suggestions to konw whether classes in `gumtree.jar` is exactly loaded or not ?

**Comment by Symbolk** [comment]
@TalentSSS The problem is still that other subclasses of Client are not loaded when running Run.main().

When saying that you have already done that, did you try my solution in PR: #205? And another thing you may check is the Gradle in settings:

![image](https://user-images.githubusercontent.com/14107297/117596332-bd4a8680-b175-11eb-9cde-638bd076fe6f.png)

**Comment by TalentSSS** [comment]
@Symbolk Thanks a lot ! As you metioned in #205, I can get those available commands by including the jar files like this
```
dependencies {
      runtime fileTree(dir: '$IDEA_PREOJECTS_DIR/gumtree/dist/build/install/gumtree/lib', include: ['*.jar'])
}
```
It works exactly !

But I tried to add `client.diff` module to `client` by 
```
dependencies {
    runtime project(':client.diff')
}
```
It caused `circular dependency`, so I didn't try to include jars in `client` before.

Anyway, appreciate for your help !
