### ISSUE TITLE
Output the original line number of node in actions

### ISSUE THREAD

**Issue by Symbolk** [GumTreeDiff/gumtree#89]
Hi there,
I am trying to generate actions/edit script between two java files, but I get stuck in printing the ITree's line number in original java files.
It seems that the  getPos() and getEndPos() in ITree should output the line numbers, but their outputs are not what I expect.
I am still exploring the code about printing line numbers, but any help from the community is appreciated. #33 #85 
Thanks!

**Comment by coder-chenzhi** [comment]
Hi,
Gumtree use [Eclipse JDT](https://www.eclipse.org/jdt/) parse java source code to get the AST,  you can use [`CompilationUnit.getLineNumber(int position)`](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2Fdom%2FCompilationUnit.html) to get the line number of specific position.

`CompilationUnit` is the type of the root of an AST. The source range for this type of node is ordinarily the entire source file, including leading and trailing whitespace and comments. You can create a `CompilationUnit` by referring following code in [AbstractJdtTreeGenerator.java](https://github.com/GumTreeDiff/gumtree/blob/develop/gen.jdt/src/main/java/com/github/gumtreediff/gen/jdt/AbstractJdtTreeGenerator.java)
```
ASTParser parser = ASTParser.newParser(AST.JLS9);
parser.setKind(ASTParser.K_COMPILATION_UNIT);
Map pOptions = JavaCore.getOptions();
pOptions.put(JavaCore.COMPILER_COMPLIANCE, JavaCore.VERSION_9);
pOptions.put(JavaCore.COMPILER_CODEGEN_TARGET_PLATFORM, JavaCore.VERSION_9);
pOptions.put(JavaCore.COMPILER_SOURCE, JavaCore.VERSION_9);
pOptions.put(JavaCore.COMPILER_DOC_COMMENT_SUPPORT, JavaCore.ENABLED);
parser.setCompilerOptions(pOptions);
parser.setSource(readerToCharArray(r));
CompilationUnit cu = (CompilationUnit) parser.createAST(null);
```

**Comment by jrfaller** [comment]
Hi getPos and getLength are the absolute index in terms of character and lenght in number of characters.

**Comment by Symbolk** [comment]
Ok, that sounds reasonable and I am trying to keep the line number and replace the _StartPosition_ in AbstractJdtVisitor.java.

@jrfaller  But since it is a demanding feature(#33 #52 #31), maybe you can implement it inside gumtreediff?

**Comment by jrfaller** [comment]
Yes I could but it would be at the expense of performances since it will lead to some files being read twice. Maybe with an option to force it?

**Comment by Symbolk** [comment]
I did that by passing a CompilationUnit cu to createVisitor()(AbstractJdtTreeGenerator.java/createVisitor(CompilationUnit cu)), and call cu.getLineNumber(startPosition) to get the line number before pushing ITrees into the Deque(AbstractJdtVisitor.java/push(int type, String typeName, String label, int startPosition, int length)). 

In this way, I wonder if the file is read twice or not.

(BTW, I also see JavaParser backend in the project, is it fully ready to be used?)

**Comment by jrfaller** [comment]
Hi, no this way the file is read only once, but for some parsers it is not possible.

JavaParser backend is normally good enough to be tested, but might need some adjustements as it is very recent.

**Comment by Symbolk** [comment]
For now, I only focus on Java files, thus I only implement the Java line numbers output function. 

Maybe later I will dive into other languages(go&python first.) :-)

**Comment by sadjad-tavakoli** [comment]
Hi everyone, 

I'm working on the same feature, but I have a different and quite java-basic question. I'm not sure how to see the results of my changes. In other words, I don't know how to compile the new version of the project to be executable (./gumtree ...)

I appreciate your replies. 
Thanks!

**Comment by Symbolk** [comment]
@sadjad-tavakoli You're right, build it with `./gradlew build -x test` if under Windows, then find your jar under `gumtree/dist/build/distributions`.

**Comment by sadjad-tavakoli** [comment]
@Symbolk Thanks for your response! 
I'm on macOS, so the output would be in the zip file in gumtree/dist/build/distributions, right?

**Comment by Symbolk** [comment]
> @Symbolk Thanks for your response!
> I'm on macOS, so the output would be in the zip file in gumtree/dist/build/distributions, right?
Yes, after build success, it should generate many stuffs in `dist`.

If you just want an executable fat jar, you can find it under `gumtree/dist/build/install` or `gumtree/dist/build/libs`; if you want each submodule in a jar, unzip `gumtree/dist/build/distributions/gumtree-*.zip` and you will get all small jars.
