### ISSUE TITLE
Implement Custom Data for Parsers in Tree

### ISSUE THREAD

**Issue by MichaelHilton** [GumTreeDiff/gumtree#9]
It would be very helpful for certain applications for the Gumtree node to have a link back to the native tree.  This would be needed when someone wants to edit the original code based on what they have learned from the AST tree.

**Comment by jrfaller** [comment]
First question: this custom data would need to be serialized in your use case, or just alive during runtime?

**Comment by MichaelHilton** [comment]
The use case I am considering is this.
1) the user gets some code from an editor (i.e. eclipse)
2) the user then parses the code into a Gumtree AST.
3) the use then does some science and now wants to modify the original code.
4) the user uses the link back to the original tree and is able to modify the original code

I think that this would be ok for have it to be alive just during runtime.

**Comment by jrfaller** [comment]
OK I propose that we will implement this feature as a `public Object getMetadata(String key)` and `public void setMetadata(String key, Object obj)` that you can use on a ITree. It would do the trick?

**Comment by morandat** [comment]
Actually it was the purpose of the tree_info branch (before we messed it up).
Jean-Rémy’s proposition is still but subset of what is needed but can be easily implemented.

**Comment by MichaelHilton** [comment]
That seems like a great place to start!

**Comment by morandat** [comment]
I think the new API for metadata is close enough of what we were planning.
There are two levels on metadata, globals (on treecontext) and locals (on ITree). Locals may overrides globals.
Metadata can be serialized/unserialized quite easily (with lambda). Generators can provide on tree context serializers.

**Comment by MichaelHilton** [comment]
that sounds great to me.
