### ISSUE TITLE
C support in gumtree: what's the difference between cgum and gen.c?

### ISSUE THREAD

**Issue by monperrus** [GumTreeDiff/gumtree#92]
Hi @jrfaller , what's the difference between https://github.com/GumTreeDiff/cgum and https://github.com/GumTreeDiff/gumtree/tree/develop/gen.c?

Cheers, --Martin

**Comment by jrfaller** [comment]
No different,

cgum is the tool that produce the AST then used by gumtree. gen.c is where this magic happens.
