### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by SaliZumberi** [GumTreeDiff/gumtree#93]
I wanted to use the GumTree API example and got this issue:

java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;

is there any solution to this porblem here:

**Comment by jrfaller** [comment]
Can I have more information on what you were trying to do in order to be able to reproduce the bug?

Best regards.

**Comment by SaliZumberi** [comment]
got this issue when running: 
Run.initGenerators();
        String file1 = "./data/java_test_data/v1.java";
        String file2 = "./data/java_test_data/v2.java";
        ITree src = Generators.getInstance().getTree(file1).getRoot();
        ITree dst = Generators.getInstance().getTree(file2).getRoot();
        Matcher m = Matchers.getInstance().getMatcher(src, dst); // retrieve the default matcher
        m.match();
        m.getMappings(); // return the mapping store

with these dependencies in pom

        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>core</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.github.gumtreediff</groupId>
            <artifactId>client</artifactId>
            <version>2.1.0</version>
        </dependency>

**Comment by jrfaller** [comment]
Could you try with the develop version? I think this bug was due to a transitive dependency to guava that got fixed sometime ago.

I will try to refresh the version on Maven soon.

**Comment by SaliZumberi** [comment]
no i tried only with maven dep..

will try with dev version

**Comment by jrfaller** [comment]
any news with the develop version?
