### ISSUE TITLE
Update Maven Repo with current version

### ISSUE THREAD

**Issue by SaliZumberi** [GumTreeDiff/gumtree#94]
Hi Jean-Rémy

I want to build a tool on top of gumtree :)
and would really appreciate if you could update the maven repo

best
sali

**Comment by jrfaller** [comment]
Done ;)

**Comment by Symbolk** [comment]
> Done ;)

Hi, standing at 2021, I found that the maven repo (https://mvnrepository.com/artifact/com.github.gumtreediff/core, and https://search.maven.org/artifact/com.github.gumtreediff/core/2.1.2/jar) has not been updated since 2.1.2, do you have any plan to keep it up to date since now we have 3.0.0 version?

**Comment by jrfaller** [comment]
Maven packages are now released on github packages, there os a snapshot and 3.0.0-beta2.

Cheers

**Comment by Symbolk** [comment]
> Maven packages are now released on github packages, there is a snapshot and 3.0.0-beta2.
> 
> Cheers

Yeah, I kind of noticing that after the issue :->, I am just checking out how to configure gradle to use Github package.

**Comment by jrfaller** [comment]
Maybe you can provide a doc when you manage to get it working ;)

Cheers!

**Comment by Symbolk** [comment]
> Maybe you can provide a doc when you manage to get it working ;)
> 
> Cheers!

Yeah, I think it is not hard, the only extra step is to add the registry beside the mavenCentral(), with authentication, as you have done here: https://github.com/GumTreeDiff/gumtree/blob/961191bd9513faa962e3ee89a7fe091831b6f64c/build.gradle#L132-L141

By the way, how do you configure the username and token as the Gradle property (in command line, property file and IDEA)? I  looked at that but am still confused.

**Comment by jrfaller** [comment]
I use a property file locally and an environment variable in the CI

**Comment by jrfaller** [comment]
> Alright, I think I am figuring out how to do it, should I contribute a doc in wiki/Getting Started/Installation about how to consume the latest version from GitHub Packages with Gradle (and even Maven)?

If you could it would be awesome!!

Cheers

**Comment by Symbolk** [comment]
Wiki done here! @jrfaller

**Comment by jrfaller** [comment]
Awesome! Thanks
